### ISSUE TITLE
BleManagerDiscoverPeripheral no getting triggered

### ISSUE THREAD

**Issue by ssozonoff** [innoveit/react-native-ble-manager#100]
Using your example code and running as is I see lots of BLE discoveries in the Device Log but handleDiscoverPeripheral method is never called.

**Comment by ssozonoff** [comment]
Strange, seems to work now however its calling BleManager.scan() in componentDidMount() does not seem to work. No errors are reported and the scan takes place for the set duration but the BleManagerDiscoverPeripheral does not seem to get fired

**Comment by marcosinigaglia** [comment]
Try to bind handleDiscoverPeripheral in the constructor

**Comment by ssozonoff** [comment]
No luck :-(

**Comment by marcosinigaglia** [comment]
Maybe the module is not ready in componentDidMount, try to add some delay.

**Comment by ssozonoff** [comment]
Adding the delay works but it feels like a hack to me.

Thanks

**Comment by marcosinigaglia** [comment]
Can't you init the module before?
