### ISSUE TITLE
UI bugs in Example app

### ISSUE THREAD

**Issue by jzfre** [innoveit/react-native-ble-manager#1005]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**

**To Reproduce**
1. Run the example code
2. Have some peripheral, scan, click on connect
3. Peripheral background color is be green, but only for short amount of time, then it goes white

**Expected behavior**
Background color should stay green, as the peripheral is connected

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max (but really doesn't matter as this error happens in JS)
 - react-native-ble-manager version: 10.0.0
 - react-native version: 0.71.3

**Additional context**
I can create PR with updated behaviour if you want

**Comment by marcosinigaglia** [comment]
Hi @jzfre , your PR is welcome.
