### ISSUE TITLE
Excessive number of pending callbacks due to stopNotification()

### ISSUE THREAD

**Issue by anton25360** [innoveit/react-native-ble-manager#1006]
Happens on iOS and Android.

I poll my BT device to get the battery % every 10s, but after few minutes (or after a few writeWithoutResponses), the app cannot communicate with the BT device anymore and I get this error:

`
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"862":{"module":"BleManager","method":"stopNotification"},"902":{},"906":{},"907":{},"908":{},"909":{},"910":{},"911":{},"912":{},"913":{},"976":{"module":"BleManager","method":"stopNotification"},"977":{"module":"BleManager","method":"stopNotification"},"978":{"module":"BleManager","method":"stopNotification"},"979":{"module":"BleManager","method":"stopNotification"},"980":{},"981":{"module":"BleManager","method":"stopNotification"},"982":{},"983":{},"984":{"module":"BleManager","method":"stopNotification"},"985":{},"986":{},"1107":{"module":"BleManager","method":"stopNotification"},"1108":{"module":"BleManager","method":"stopNotification"},"1109":{"module":"BleManager","method":"stopNotification"},"1110":{"module":"BleManager","method":"stopNotification"},"1111":{"module":"BleManager","method":"stopNotification"},"1112":{},"1113":{"module":"BleManager","method":"stopNotification"},"1114":{},"1115":{},"1116":{"module":"BleManager","method":"stopNotification"},"1117":{},"1118":{},"1247":{"module":"BleManager","method":"stopNotification"},"1248":{"module":"BleManager","method":"stopNotification"},"1249":{"module":"BleManager","method":"stopNotification"},"1250":{"module":"BleManager","method":"stopNotification"},"1251":{"module":"BleManager","method":"stopNotification"},"1252":{"module":"BleManager","method":"stopNotification"},"1253":{},"1254":{"module":"BleManager","method":"stopNotification"},"1255":{},"1256":{},"1257":{"module":"BleManager","method":"stopNotification"},"1258":{},"1259":{},"1403":{"module":"BleManager","method":"stopNotification"},"1404":{"module":"BleManager","method":"stopNotification"},"1405":{"module":"BleManager","method":"stopNotification"},"1406":{"module":"BleManager","method":"stopNotification"},"...(truncated keys)...":451}
`

I have a few `BleManager.stopNotification`s in my app (see below), is the syntax incorrect?
```
              BleManager.startNotification(storedID, serviceID, notifyChar)
                .catch((err) =>
                  console.log("Error starting notification " + err)
                )
                .then(() => {
                  let responseArray = [];
                  bleManagerEmitter.addListener(
                    "BleManagerDidUpdateValueForCharacteristic",
                    ({ value }) => {
                      if (value[0] === 35) {
                        responseArray.push(1);
                        if (responseArray.length === 1) {
                          setDeviceInfoArray(value);
                        }
                        BleManager.stopNotification(
                          storedID,
                          serviceID,
                          notifyChar
                        ).catch((err) =>
                          console.log("Error stopping notification " + err)
                        );
                      }
                    }
                  );
                });
```

**Comment by ShongSu** [comment]
@anton25360 Thanks, you saved my day.
