### ISSUE TITLE
Bluetooth scans on debug but not release iOS

### ISSUE THREAD

**Issue by hypext1** [innoveit/react-native-ble-manager#1008]
**Describe the bug**
Bluetooth example app scans on debug but not release iOS

**To Reproduce**
1. Download and yarn/pod-install example app
2. Build for debug
3. Build for release

**Expected behavior**
Phone scans for devices on network regardless of being built for debug or release.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.3.1
 - react-native-ble-manager version: 10.0.2
 - react-native version: 0.70.3

**Comment by msl2000** [comment]
What was your solution?
