### ISSUE TITLE
OS call checkState() trigger BleManagerDidUpdateState event return {state: 'unknown'}

### ISSUE THREAD

**Issue by SimonRepo** [innoveit/react-native-ble-manager#1021]
iOS call checkState() trigger BleManagerDidUpdateState event return {state: 'unknown'}

code:
const didUpdateStateSub = this.#addListener(
          'BleManagerDidUpdateState',
          (args) => {
            this.#removeListener(didUpdateStateSub);
            BleLogger.info('ble:DidUpdateState:'+JSON.stringify(args));
            resolve(args.state === 'on' || args.state === 'unknown');
          },
        );
        BleManager.checkState();

**Smartphone (please complete the following information):**
 - Device: [iPhone8]
 - OS: [iOS14.1]
 - react-native-ble-manager version: 10.0.2
 - react-native version: 0.62.3

**Comment by marcosinigaglia** [comment]
As [documented](https://github.com/innoveit/react-native-ble-manager#blemanagerdidupdatestate)
