### ISSUE TITLE
iOS not supported Custom Event?

### ISSUE THREAD

**Issue by paolosantarsiero** [innoveit/react-native-ble-manager#1023]
Is there a possibility to implement custom events on iOS? While on android I have no problems and everything works fine implementing custom events launched via `bleManagerEmmiter.emit()` on iOS instead I get the error `${nameCustomEvent} is not supported event type for BleManager`.

Actually I see an array of supported events in iOS:
```
- (NSArray<NSString *> *)supportedEvents
{
    return @[@"BleManagerDidUpdateValueForCharacteristic", @"BleManagerStopScan", @"BleManagerDiscoverPeripheral", @"BleManagerConnectPeripheral", @"BleManagerDisconnectPeripheral", @"BleManagerDidUpdateState", @"BleManagerCentralManagerWillRestoreState", @"BleManagerDidUpdateNotificationStateFor"];
}
```
Is possible to extend this array when use:
```
declare module 'react-native-ble-manager' {
  // enrich local contract with custom state properties needed by App.tsx

  enum BleEventType {
    ExampleCustomEvent = 'ExampleCustomEvent',
  }
}
```

Also I wanted to ask: is there a possibility to have different instances of BleManager?

**Comment by marcosinigaglia** [comment]
Hi @paolosantarsiero , I don't understand why you need to create custom event through this, library. I think there is specific library for this purpose.
