### ISSUE TITLE
Bluetooth enable not working on android 12

### ISSUE THREAD

**Issue by ravindra3003** [innoveit/react-native-ble-manager#1028]
Hello team,

According to android api leavel 31 I have updated code. before I am trying to enable bluetooth using `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)`. for android 12 I have tried with multiple request like this `const granted = await PermissionsAndroid.requestMultiple([ PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN, PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT]);`.

I am getting error on only on android 12

**Error is :** 
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/c0493edd-ee29-4972-9148-16dd10f033e7)

**Code :**
### Old code that not compatible with android 12
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/a25551e2-7f46-4491-b620-a5392431804a)

**Old AndroidManifest.xml**
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/5a7c3966-f70e-4d9f-b57a-02a0b62db795)

**Android/build.gradle**
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/1c7eabfc-af7b-48c2-b9d5-63a344f1f9ca)

Versions :
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/74949ef5-4fcb-40c3-a943-7452f45e0d7b)

### After I updating this code for android 12 I got Permission is null Error
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/a9584cb3-c70a-42b4-8c80-1b8546f13129)
**Updated AndroidManifest.xml**

![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/be9cb46c-af0a-457d-b532-82dc515c6a92)
![image](https://github.com/innoveit/react-native-ble-manager/assets/96780748/1c40fce4-9698-446e-a2cc-e27450ed7ebc)

please let me know what I am missing, what i need to update or upgrade

**Comment by 1mike12** [comment]
1. I think this is more a question for react native and their `PermissionsAndroid` module. 
2. Why are you submitting images of text, instead of the text itself?
