### ISSUE TITLE
 iOS write error :  Unknown ATT error.

### ISSUE THREAD

**Issue by SiuyuenChow** [innoveit/react-native-ble-manager#1030]
Hello,

Successfully connected to the Bluetooth, I could also receive the information from the peripheral. When I received the information and sent the content back, an error was reported: Unknown ATT error.
---
**Here is write API & info**

BleManager.write(peripheral,
service,
characteristic,
value) 
 => 
write(
0c670f57-adfd-256f-7ade-90117cc77e20 
6e6b5c64-faf7-40ae-9c21-d4933af45b00 
477a2967-1fab-4dc5-920a-dee5de685a00 
[69, 79, 68])

**BLE info:**
----
{ service: '6e6b5c64-faf7-40ae-9c21-d4933af45b00',
  characteristic: '477a2967-1fab-4dc5-920a-dee5de685a00',
  properties: 
   { ExtendedProperties: 'ExtendedProperties',
     Read: 'Read',
     Write: 'Write',
     WriteWithoutResponse: 'WriteWithoutResponse',
     Notify: 'Notify' },
  isNotifying: false,
  descriptors: [ { uuid: '2900' }, { uuid: '2902' } ] }
----
Phone : iPhone X
OS : iOS 16.1.1

Thanks

**Comment by SiuyuenChow** [comment]
Hello again，

latest

Obviously did nothing, suddenly can send again, but error still appears.

But according to the log, 10 seconds have passed since it was received.

After appearing, the other paragraph received the message immediately

Error Domain=CBATTErrorDomain Code=241 "Unknown ATT error." UserInfo={NSLocalizedDescription=Unknown ATT error.}

[15:23:42.524] Prepared MTIzNDU2Nzg5 bytes with hash: 313233343536373839
[15:23:42. 527] Sending to BluetoothKit. BKRemoteCentral
[15:23:42. 533] Sent to BluetoothKit. BKRemoteCentral
[15:23:52.583] Received data of length: 9 with hash: 313233343536373839
 

Thanks

**Comment by glenne** [comment]
Are you using 10.1.0?  If so, I suggest switching to 10.0.2 until a new release is made.  10.1.0 has a bug where it only writes sequential numbers 012345... instead of the requested data.  This is fixed by pr #1026.

@marcosinigaglia Can you make a new release as everyone who uses 10.1.0 will be unable to write successfully?

**Comment by SiuyuenChow** [comment]
> Are you using 10.1.0? If so, I suggest switching to 10.0.2 until a new release is made. 10.1.0 has a bug where it only writes sequential numbers 012345... instead of the requested data. This is fixed by pr #1026.
> 
> @marcosinigaglia Can you make a new release as everyone who uses 10.1.0 will be unable to write successfully?

Hello glenne,

Yes, I'm using 10.1.0.

This question seems to have a lot to do with my problems , https://github.com/innoveit/react-native-ble-manager/pull/1026 

I tried 10.0.2,

Thanks

**Comment by marcosinigaglia** [comment]
You have the error because the ble device is not replying correct to your write, is not a library problem.
