### ISSUE TITLE
is a permission error?

### ISSUE THREAD

**Issue by jacopo-ferroni** [innoveit/react-native-ble-manager#1040]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**
I created project with Expo and React Native and when i try to set the bluetooth config something goes wrong... i tried to use all the solution in the web but i can't find answer.
I installed the library wit "npm i --save react-native-ble-manager" (obviusly i find it in the package.json), after i put all the requires permission in the AndroidManifest.xml, as you can see in the picture below (if you see others bluetooth permissions in a comment mode is because i m lazy) and i wrote the Start method, that is fundamental to run correctly the library, until now everything right.
As soon as i try to insert any new methods goes print error message that says me that there isn't connect permission (picture below),  despite there is already the BLUETOOTH_CONNECT permission.

**To Reproduce**
Follow the steps above, so install the library, put the permissions in the AndroidManifest.xml, and try to insert the methods.

**Expected behavior**
Obviously i expect that this error message doesn't appear

**Screenshots**
<img width="412" alt="permissions" src="https://github.com/innoveit/react-native-ble-manager/assets/85305712/272749d8-e861-4caa-bbf5-0738b1556826">
<img width="302" alt="work" src="https://github.com/innoveit/react-native-ble-manager/assets/85305712/403fd3ec-7f9f-4e23-9684-451f21bad857">
<img width="295" alt="not work" src="https://github.com/innoveit/react-native-ble-manager/assets/85305712/896823fa-cfad-4efb-b77f-303503f0ab16">
![Screenshot_20230712-091152](https://github.com/innoveit/react-native-ble-manager/assets/85305712/6f8df1b0-220e-4a10-b11d-149a35e3c045)

**Smartphone (please complete the following information):**
 - Device: BlackView BV4900 PRO
 - Android: "12"
 - react-native-ble-manager version: "^10.1.2"
 - react-native version: "0.71.8"

**Comment by marcosinigaglia** [comment]
Check the example, you have to use PermissionsAndroid to request permission runtime.
