### ISSUE TITLE
BleManager could not be started. [TypeError: Cannot read property 'start' of null]

### ISSUE THREAD

**Issue by scytye** [innoveit/react-native-ble-manager#1044]
**Describe the bug**
I downloaded the Github example to start my project, but it did not start successfully on the emulator. Error: Cannot read property 'start' of null. I tried to package it into an app and test it on a real phone, but the results were directly flashed back！！

**Expected behavior**

I hope to obtain the property  of  blemanager normally

**Screenshots**
This is my code
![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/2800410e-51ee-4172-a8ac-08394aaedd21)

![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/72b1391e-a071-4676-bfb9-20a676bfd8ce)

**Smartphone (please complete the following information):**
 - Device: [honor50SE]
 - OS: [android12]
 - react-native-ble-manager version: 10.1.2
 - react-native version:0.71.8

**Additional context**
I hope you can reply as soon as possible

**Comment by scytye** [comment]
This is my package and library, it's not null !!!!!
![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/0733873f-be01-43ba-b521-ac437ea0d4f2)
![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/cd8b59aa-d83a-43b6-a00b-5c26e63e83dd)

**Comment by scytye** [comment]
> If the library is null is not installed correctly.

Thanks for your reply. I tried reinstalling the library ,but the return value is still null. I printed the blemanager through console log, and the result was the constructor of  blemanager. Can I assume that I have installed it correctly? Here are my steps：
![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/141d95c6-512d-4d9c-be70-099a40f4b6c3)
![image](https://github.com/innoveit/react-native-ble-manager/assets/21376200/1c1b5d11-d531-47c5-9358-8a888dde2c3f)

**Comment by marcosinigaglia** [comment]
The js part is installed but probably the problem is the linking of the native part in you android project.

**Comment by scytye** [comment]
>

**Comment by scytye** [comment]
> The js part is installed but probably the problem is the linking of the native part in you android project.

hello sir
I checked my RN project and it was created by expo without the 'androidManifest' file. Can I modify it through the packaging tool? Or is there any way to monitor whether the native part is linked in my project
