### ISSUE TITLE
MTU Size is not Increasing

### ISSUE THREAD

**Issue by HamzaQayyumMST** [innoveit/react-native-ble-manager#1050]
requestMTU doesn't seem to be doing anything  also packages are still 20 bytes.
I'm trying to write a string in a single time by setting MTU to 512 bytes but it doesn't seem like it is working. Please help me resolve the issue 

My Code

`  connect(id) {
        this.isConnecting = true;
        return new Promise((resolve, reject) => {
            BleManager.connect(id)
                .then(() => {
                    setTimeout(() => {
                        BleManager.requestConnectionPriority(id, 1)
                            .then((status) => {
                                // Success code
                                console.log("Requested connection priority");
                                setTimeout(async () => {
                                    try {
                                        const mtu = await BleManager.requestMTU(id, 185);
                                        console.log('id-------------->', id);
                                        // Success code
                                        console.log("MTU size changed to " + mtu + " bytes");
                                        console.log('Connected success.');

                                        // Introduce another 2-second delay before retrieving services
                                        setTimeout(async () => {
                                            try {
                                                const peripheralInfo = await BleManager.retrieveServices(id);
                                                //console.log('Connected peripheralInfo: ', JSON.stringify(peripheralInfo));
                                                this.peripheralId = peripheralInfo.id;
                                                this.parseData(peripheralInfo);
                                                this.peripheralInfo = peripheralInfo;
                                                this.isConnecting = false;
                                                resolve(this.peripheralInfo);
                                            } catch (error) {
                                                // Failure code
                                                console.log(error);
                                                reject(error);
                                            }
                                        }, 500);

                                    } catch (error) {
                                        // Failure code
                                        console.log(error);
                                        reject(error);
                                    }
                                }, 500);
                            })
                            .catch((error) => {
                                // Failure code
                                console.log(error);
                            });
                    }, 500)

                    // Introduce a 2-second delay before MTU request

                })
                .catch(error => {
                    console.log('Connected error:', error);
                    this.isConnecting = false;
                    reject(error);
                });
        });
    }`

**Comment by marcosinigaglia** [comment]
The phone or the device is not supporting the mtu that are you set.
