### ISSUE TITLE
BleManagerDidUpdateValueForCharacteristic event does not work with iOS

### ISSUE THREAD

**Issue by ErinTran535** [innoveit/react-native-ble-manager#1054]
**Describe the bug**

Hi team, I've started the notification by this
`tempValueService?.map((characteristic) => {
          BleManager.startNotification(this.peripheral.id, characteristic.service, characteristic.characteristic);
        });`

then add listener 

`      bleManagerEmitter.addListener('BleManagerDidUpdateValueForCharacteristic', handleGetTemp)
`
then I pasted the handle get value from notify from you guys example 

```
`const handleGetTemp = useCallback(async ({
    value, peripheral, characteristic, service,
  }) => {
    // Convert bytes array to string
    const data = value;
    console.log(`============= Received ${data} for characteristic ${characteristic}`);
  }, []);
`

```

with Android device, it working well, got the value and displayed it with console log, but with iOS, I get nothing, do I miss anything ? I did add the NSBluetoothAlwaysUsageDescription key into my info.plist

**Comment by ErinTran535** [comment]
nevermind, I've able to solve it, I guess the  startnotification was too generic, it involved so many unnecessary characteristics, after fixing it with start notification with specifically the one I need, it works normally

**Comment by Srikanth-Enuguru** [comment]
@ErinTran535 I'm also facing a similar issue where Closed
BleManagerDidUpdateValueForCharacteristic event is not working in Android device. 

Please help me in understanding what's wrong with my code.
https://github.com/innoveit/react-native-ble-manager/issues/1055

**Comment by itsaliraxa** [comment]
I'm also facing the same issue not getting data in both Android & ios. But the notification started successfully. I am using an example code. anyone can help me here?
