### ISSUE TITLE
BleManagerDidUpdateState only triggers on checkState()

### ISSUE THREAD

**Issue by JonasWho** [innoveit/react-native-ble-manager#106]
I do not get any state changes through the BleManagerDidUpdateState listener unless I call BleManager.checkState(). 

Is this intentional? 

I am on Android.

**Comment by marcosinigaglia** [comment]
Hi, the purpose of checkState method is to force to read the current state, for example at the application start, then the event is fired when the state change.

**Comment by JonasWho** [comment]
@marcosinigaglia ok, but my question is, can I expect BleManagerDidUpdateState to update when the user switches Bluetooth on and off? Or do I have to call checkState to get the state?

**Comment by marcosinigaglia** [comment]
When the user change the bluetooth state the event si fired automatically

**Comment by JonasWho** [comment]
@marcosinigaglia yeah, thats what I would expect. But it is not happening. Not on my Android device.

**Comment by marcosinigaglia** [comment]
Which version of RN/Android do you use?

**Comment by JonasWho** [comment]
RN 0.38.1, react-native-ble-manager 2.4.3 and Android 5.1.1

**Comment by marcosinigaglia** [comment]
Sorry, I don't have a device to simulate your problem, try to check the permission in AndroidManifest.xml

**Comment by JonasWho** [comment]
I just tested it on an Android running 6.0.1. Same problem. 

I already had `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>` in my manifest.

**Comment by marcosinigaglia** [comment]
You have to also add `<uses-permission android:name="android.permission.BLUETOOTH"/>`

**Comment by JonasWho** [comment]
Sorry, yes I already had that one as well, forgot to mention.

**Comment by marcosinigaglia** [comment]
Try also `android.permission.BLUETOOTH_ADMIN`

**Comment by JonasWho** [comment]
no luck with that one either :(

**Comment by JonasWho** [comment]
DUH! I had not called .start() :( 
My bad, sorry for wasting your time @marcosinigaglia. The documentation could be a bit sharper IMO, but thanks for trying to get me going :)

**Comment by marcosinigaglia** [comment]
NP

**Comment by KayhanB** [comment]
Is there any example code  about checkState() ?
This is my code and not fired 


import BluetoothSerial from 'react-native-ble-manager'
const bleManagerEmitter = new NativeEventEmitter(BluetoothSerial);


  componentWillMount() {
    async function REQUEST_ACCESS_COARSE_LOCATION() {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION,
        )
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log("You can use the bluetooth")
          BluetoothSerial.start({ showAlert: false })
            .then(() => {
              console.log('Module initialized');
              BluetoothSerial.checkState()

            });
        } else {
          console.log("Bluetooth permission denied")
        }
      } catch (err) {
        console.warn(err)
      }
    }

    REQUEST_ACCESS_COARSE_LOCATION()



    bleManagerEmitter.addListener(
      'BleManagerDidUpdateState ',
      (res) => {
        console.log(res)
      }
    )
  }

**Comment by KayhanB** [comment]
Example Code  Usage checkState()

import BluetoothSerial from 'react-native-ble-manager'
const bleManagerEmitter = new NativeEventEmitter(BluetoothSerial)


BluetoothSerial.start({ showAlert: false })
            .then(() => {
              BluetoothSerial.checkState()
              console.log('Module initialized')

            });


bleManagerEmitter.addListener(
      'BleManagerDidUpdateState',
      (res) => {
        console.log(res)
      }
    )
