### ISSUE TITLE
Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@be0b165f:GattService resisterScanner

### ISSUE THREAD

**Issue by GokulKir** [innoveit/react-native-ble-manager#1066]
Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@be0b165f:GattService resisterScanner 
how to solve this issue   this code  

import { StyleSheet, Text, View , ScrollView , TouchableOpacity, PermissionsAndroid } from 'react-native'
import React, { useEffect, useState } from 'react'
import { responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions'
import Icon from 'react-native-vector-icons/MaterialIcons';
import useBluetooth from '../hooks/useBluetooth';
import BleManager from 'react-native-ble-manager';

export default function BluetoothList() {
  const [scanning, setScanning] = useState(false);
  const [devices, setDevices] = useState([]);
  const [connectedDevice , setConnectedDevice] = useState(null)

  useEffect(() => {
    // Function to scan for BLE devices
    const scanForDevices = () => {
      BleManager.scan([], 5, true) // Scans for 5 seconds, auto-connects to devices
        .then(results => {
          const scannedDevices = results.map(device => ({
            id: device.id,
            name: device.name || 'Unknown Device',
          }));
          setDevices(scannedDevices);
        })
        .catch(error => {
          console.error('Scan error:', error);
        });
    };

    // Start scanning for devices when the component mounts
    scanForDevices();

    // Clean up resources when the component unmounts
    return () => {
      BleManager.stopScan();
      if (connectedDevice) {
        BleManager.disconnect(connectedDevice.id)
          .then(() => {
            console.log('Disconnected from connected device');
          })
          .catch(error => {
            console.error('Disconnection error:', error);
          });
      }
    };
  }, []);

  const connectToDevice = (device) => {
    BleManager.connect(device.id)
      .then(() => {
        console.log('Connected to device:', device.name);
        setConnectedDevice(device);
      })
      .catch(error => {
        console.error('Connection error:', error);
      });
  };

  const disconnectFromDevice = () => {
    if (connectedDevice) {
      BleManager.disconnect(connectedDevice.id)
        .then(() => {
          console.log('Disconnected from device:', connectedDevice.name);
          setConnectedDevice(null);
        })
        .catch(error => {
          console.error('Disconnection error:', error);
        });
    }
  };

  return (
    <View style={styles.container}>

      <View style={styles.SecContainer}>

        <Icon name="bluetooth" color="blue" size={60}/>

      </View>

      <ScrollView>

        <TouchableOpacity  style={styles.ConnectioStyle}>

        </TouchableOpacity>

      </ScrollView>

    </View>
  )
}

const styles = StyleSheet.create({
  container : {
    flex : 1,
    backgroundColor:'#fff' ,
    alignItems:'center' , 
    marginTop:responsiveHeight(3)
  } ,
  SecContainer  : {
    width : responsiveWidth(15) , 
    height : responsiveWidth(12) ,
    backgroundColor:'#fff' ,
    borderRadius:5 , 
    elevation:5 , 
    alignItems:'center' ,
    justifyContent:'center'
  

  } ,
  ConnectioStyle : {
    width : responsiveWidth(96) ,
    height : 60 ,
    backgroundColor:"#fff" ,
    borderRadius:3 , 
    elevation:10 ,
    marginTop:10 ,
  }
})

**Comment by lucasmrau** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.package name"> // replace package name with yours

/* add the permissions below before the aplication tag */
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />

**Comment by lucasmrau** [comment]
or, in android 13:

<uses-permission android:name="android.permission.BLUETOOTH" 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" 
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" 
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" 
<uses-permission android:name="android.print.BLUETOOTH" 
<uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" 
<uses-permission android:name="android.permission.BLUETOOTH_DEBUG" 
<uses-feature android:name="android.hardware.bluetooth" android:required="true"

**Comment by AmilaJJ** [comment]
Request BLUETOOTH_SCAN permissions on run time from the user

**Comment by ReactRaylogic** [comment]
I am asking user for BLUETOOTH_SCAN permission and location permission on run time but until and unless i go into permission and click on Allow of already allowed permission of Near by devices the ble device does not show in listner of ble scan.
