### ISSUE TITLE
[Question] Does this lib allows to advertize services / exchange between smartphones ?

### ISSUE THREAD

**Issue by seba9999** [innoveit/react-native-ble-manager#1068]
Hi,

I may be off topic but I think I'm struggling with the overall understanding of the BLE technology even if it was really well explained [HERE](https://learn.adafruit.com/introduction-to-bluetooth-low-energy/gatt)

I'm wondering if with this lib I can both create a" Peripheral GATT Server" AND a "Central GATT Client" as they define ?

![image](https://github.com/innoveit/react-native-ble-manager/assets/14869447/32ba2d5e-44ca-4cb5-a54b-c3a50e6274d2)

How can I create ( / advertize ) a service then ? I only see read and write functions on characteristics.

My goal is to create this kind of topology :

![image](https://github.com/innoveit/react-native-ble-manager/assets/14869447/3b20d2d6-ae5f-451d-8247-c6bb3876e62e)

But each Peripheral and the central device are SmartPhones exchanging datas ... Like a chat to begin with... Is this possible ?

I read [this SO answer](https://stackoverflow.com/a/53350772/3636091) and also was wondering if the "Broadcaster" would be possible with this lib ?

**Comment by marcosinigaglia** [comment]
https://github.com/innoveit/react-native-ble-manager/discussions/1069
