### ISSUE TITLE
TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by Johno95CZ** [innoveit/react-native-ble-manager#1074]
**Describe the bug**
Every time I call BleManager.start() I get an error "TypeError: Cannot read property 'start' of null". I tried to reinstall the whole library, attempted to create a new expo project, and installed only this library, etc. But always the same error. I even tried every tips in already created issues on this GitHub repo.

**Screenshots**
<img width="417" alt="image" src="https://github.com/innoveit/react-native-ble-manager/assets/55092714/ba283435-0cff-4fbd-8b15-fe5f8b0087f1">

<img width="475" alt="image" src="https://github.com/innoveit/react-native-ble-manager/assets/55092714/ccb4c00b-14b4-4788-84ad-e5f4a2278e77">

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy A72
 - OS: Android 13
 - react-native-ble-manager version: ^10.1.3
 - react-native version: 0.72.4
 - expo: ^49.0.11

**Comment by Johno95CZ** [comment]
I'm sorry @marcosinigaglia but can you show me an open issue that addresses this or an issue where it shows how to fix this?

**Comment by marcosinigaglia** [comment]
@Johno95CZ  there are tons of similar issues, the library is not installed correctly.

**Comment by Johno95CZ** [comment]
Then what is the correct way? I feel like I tried all the ways already. Even read all similar issues. I even tried to install it manually.

**Comment by marcosinigaglia** [comment]
Read the expo docs, is not related to this library.

**Comment by kir1m1** [comment]
I was able to solve this by substitutin the file uri for the `react-native-ble-manager` dev dependency within the `example/package.json` with it's current npm version.
