### ISSUE TITLE
Android Permission

### ISSUE THREAD

**Issue by lucasmrau** [innoveit/react-native-ble-manager#1080]
I am using the permissions of the example. nut when open my app the first time it shows this issue:

![Screenshot_20230927_113221_One UI Home(1)](https://github.com/innoveit/react-native-ble-manager/assets/82839108/b409f471-7876-422e-b6e5-07a1724ee13f)

**Comment by marcosinigaglia** [comment]
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
