### ISSUE TITLE
Is writeValue required for iOS customized ble devices

### ISSUE THREAD

**Issue by Zoulindong999** [innoveit/react-native-ble-manager#1095]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - react-native-ble-manager version: 
 - react-native version:

**Additional context**

**Comment by Zoulindong999** [comment]
https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518747-writevalue

**Comment by marcosinigaglia** [comment]
Hi @Zoulindong999 , I don't understand your issue.
