### ISSUE TITLE
Issue with polling and cached values

### ISSUE THREAD

**Issue by calcazar** [innoveit/react-native-ble-manager#1096]
Hey all, if I do a standard write while listening to notifications, I get the same value over and over again but this value I assume has to be cached by the app.

If I use lightblue and spam the write, I get different values every time coming from the notification. if I disconnect/reconnect I get different values but if I call write functions back to back 1 second a part; I get the same value coming back. Is there a way to resolve that?

Thanks!

**Comment by marcosinigaglia** [comment]
Hi, probably you somehow cached the value.
