### ISSUE TITLE
NativeAppEventEmitter  is wrong

### ISSUE THREAD

**Issue by ysjiang4869** [innoveit/react-native-ble-manager#11]
AwersomeProjeect, one question,
 NativeAppEventEmitter should be DeviceEventEmitter according to the docs of react-native;

**Comment by marcosinigaglia** [comment]
Hi @ysjiang4869 , in the docs is not specified the difference between the two emitters so i choose the NativeAppEventEmitter with no reasoning. Why do you think the DeviceEventEmitter is better?

**Comment by ysjiang4869** [comment]
@marcosinigaglia   I  find NativeAppEventEmitter in earlier docs but now is DeviceEventEmitter, when i use NativeAppEventEmitter  it tells me not found,so i think may be the first one was deprecated

**Comment by marcosinigaglia** [comment]
It's not deprecated, maybe I can move to DeviceEventEmitter because the module has device related events.
