### ISSUE TITLE
isPeripheralConnected will crash

### ISSUE THREAD

**Issue by wangyixian** [innoveit/react-native-ble-manager#111]
I used the isPeripheralConnected function as example，but react native pop up a red view。
Maybe the error was occurred from getConnectedPeripherals.

The view content as follow: 
encode
Base64.java:494

encodeToString
Base64.java:456

byteArrayToJSON
Peripheral.java:196

asJSONObject
Peripheral.java:110

getConnectedPeripherals
BleManager.java 524

**Comment by marcosinigaglia** [comment]
Hi, I need more information.

**Comment by wangyixian** [comment]
Sorry, I made this mistake myself.
I solved this problem. 
Thank you.

**Comment by wangyixian** [comment]
The problem was reoccurred. 
BleManager.isPeripheralConnected(peripheralId, ["0000fff0-0000-1000-8000-00805f9b34fb"])
            .then((isConnected) => {
                if (isConnected) {...

was crash in android, version is 4.4 and 5.0.
But successful in ios.

**Comment by marcosinigaglia** [comment]
Is it a nullpoint exeption?

**Comment by wangyixian** [comment]
yes, the message is 'Attempt to get length of null array'.

**Comment by marcosinigaglia** [comment]
I add a check in the last release.
