### ISSUE TITLE
Eddystone beacons are not visible on Android 13

### ISSUE THREAD

**Issue by maksimLobachevskiy** [innoveit/react-native-ble-manager#1111]
Scanning does not find any Eddystone beacons, all other bluetooth devices are visible. Out of three real Eddystone devices none is discovered. I used the sample code to test it.

**Smartphone (please complete the following information):**
 - Device: Samsung XCover 5
 - OS: Android 13
 - react-native-ble-manager version:  11.0.0
 - react-native version: 0.73.13

**Comment by marcosinigaglia** [comment]
Hi @maksimLobachevskiy , check your manifest permission.

**Comment by maksimLobachevskiy** [comment]
@marcosinigaglia thank you for quick response
this is my Androidmanifest
` <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.hardware.camera.any"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-feature android:name="android.hardware.camera"/>
    <uses-permission android:name="android.permission.FLASHLIGHT"/>
    <uses-feature android:name="android.hardware.camera.flash" android:required="false"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="30"/>`

**Comment by marcosinigaglia** [comment]
I think the `neverForLocation` flag is filtering the beacon.

**Comment by maksimLobachevskiy** [comment]
@marcosinigaglia unfortunately without the flag the scanner does not see any devices at all.

**Comment by marcosinigaglia** [comment]
Do you see the beacons using the lighblue app?

**Comment by maksimLobachevskiy** [comment]
Yes I can see beacons using apps

**Comment by marcosinigaglia** [comment]
Can you try with older version?

**Comment by marcosinigaglia** [comment]
@maksimLobachevskiy can you put your manifest in the issue so it remains a trace for those who have the same problem?

**Comment by deCodeIt** [comment]
In my case when I wasn't able to scan any devices, "Turning on GPS" on my Android fixed the issue and I was able to see the devices
