### ISSUE TITLE
act as peripheral role

### ISSUE THREAD

**Issue by qpaolo** [innoveit/react-native-ble-manager#112]
is that supported?

**Comment by marcosinigaglia** [comment]
Hi, you mean to act as server?

**Comment by qpaolo** [comment]
Sorry if I did not make it clear enough.  
I mean to be able to send advertisements, handling connections is useful but not in my case.

**Comment by akoszegi** [comment]
I'm curious about this too.

**Comment by marcosinigaglia** [comment]
No, is not possible.

**Comment by qpaolo** [comment]
To be precise, it's not supported by this library.  
I rolled my own. Only for ios though. But Android support shouldn't be hard.

**Comment by marcosinigaglia** [comment]
@qpaolo you can make a PR with your changes for the advertisement.

**Comment by qpaolo** [comment]
Yeah, when I have the time.
I was just copying almost everything from apple's BLE sample app and wire it with an event emitter.

**Comment by marcosinigaglia** [comment]
Yep, thanks.
