### ISSUE TITLE
iOS advertising manufacturer data is null in version 11

### ISSUE THREAD

**Issue by vesstek-gytis** [innoveit/react-native-ble-manager#1122]
**Describe the bug**
After the library's version update (11.0.x), iOS advertising **manufacturerData** and **manufacturerRawData** are null. The previous version (10.1.x) had the correct value.

**To Reproduce**
1. Start the device scan
2. on the **peripheralDiscovered** event, log the peripheral

**Expected behavior**
A correct advertising manufacturer data.

**Logs**
Library version 11.0.4:
```
peripheral {"advertising": {"isConnectable": 1, "kCBAdvDataRxPrimaryPHY": 129, "kCBAdvDataRxSecondaryPHY": 0, "kCBAdvDataTimestamp": 723557148.359771, "manufacturerData": null, "manufacturerRawData": null, "serviceUUIDs": ["0e868900-f94a-11ed-be56-0242ac120002"]}, "id": "29872b51-7f76-8f7c-4c4d-3265008d611d", "rssi": -43}
peripheral.advertising.manufacturerData null
```

Library version 10.1.5:
```
peripheral {"advertising": {"isConnectable": 1, "kCBAdvDataRxPrimaryPHY": 129, "kCBAdvDataRxSecondaryPHY": 0, "kCBAdvDataTimestamp": 723556685.06918, "manufacturerData": {"CDVType": "ArrayBuffer", "bytes": [Array], "data": "VkwxWTIzUjAwUzAwMDAwMQA="}, "serviceUUIDs": ["0e868900-f94a-11ed-be56-0242ac120002"]}, "id": "29872b51-7f76-8f7c-4c4d-3265008d611d", "rssi": -35}
peripheral.advertising.manufacturerData {"CDVType": "ArrayBuffer", "bytes": [86, 76, 49, 89, 50, 51, 82, 48, 48, 83, 48, 48, 48, 48, 48, 49, 0], "data": "VkwxWTIzUjAwUzAwMDAwMQA="}
```

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 17.1.2
 - react-native-ble-manager version: 11.0.4
 - react-native version: 0.72

**Comment by enchorb** [comment]
@marcosinigaglia Any ETA on a release for this fix
