### ISSUE TITLE
Android receives only the first packet of notification

### ISSUE THREAD

**Issue by ghost** [innoveit/react-native-ble-manager#1124]
**Describe the bug**
When subscribing to the service's characteristic, android receives only the first packet of the notification (20 bytes), and other bytes are not received. iOS receives all the data from the notification.

**To Reproduce**
1. Subscribe to characteristic, which sends more than 20 bytes, using startNotification method
2. Log the received bytes

**Expected behavior**
All bytes from the notification should be received

**Logs**
Android, library version 11.0.4 and 10.1.5:
```
{"characteristic": "0e868931-f94a-11ed-be56-0242ac120002", "service": "0e868930-f94a-11ed-be56-0242ac120002", "value": [1, 40, 71, 176, 33, 73, 166, 42, 181, 11, 209, 180, 78, 2, 27, 61, 237, 152, 88, 233]}
```
Only 20 bytes are returned.

iOS, library version 11.0.4 and 10.1.5:
```
{"characteristic": "0e868931-f94a-11ed-be56-0242ac120002", "peripheral": "29872b51-7f76-8f7c-4c4d-3265008d611d", "service": "0e868930-f94a-11ed-be56-0242ac120002", "value": [1, 40, 172, 108, 94, 189, 10, 29, 99, 104, 160, 145, 250, 41, 127, 233, 24, 61, 99, 129, 209, 215, 63, 68, 218, 145, 143, 134, 118, 220, 211, 167, 87, 39, 138, 219, 170, 212, 76, 73, 237, 13]}
```
More than 20 bytes are returned.

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 12
 - react-native-ble-manager version: 10.1.5, 11.0.4
 - react-native version: 0.72

**Comment by marcosinigaglia** [comment]
Hi @vesstek-gytis did you change the MTU?
