### ISSUE TITLE
BluetoothGatt.writeDescriptor missing?

### ISSUE THREAD

**Issue by matheusjardimb** [innoveit/react-native-ble-manager#1147]
I'm trying to replicate an Android native app using ReactNative and react-native-ble-manager.

The code I'm replicating uses `android.bluetooth.BluetoothGatt.writeDescriptor()`, which I couldn't find any respective method here in the docs. Am I missing something? I'm using v11.0.8.

Only found one reference to such method at:
https://github.com/search?q=repo%3Ainnoveit%2Freact-native-ble-manager%20writeDescriptor&type=code

Besides that, the app is working just fine. Thanks for your help!

**Comment by marcosinigaglia** [comment]
Hi @matheusjardimb , the writeDescriptor method now is only used to enable the notification.

**Comment by marcosinigaglia** [comment]
Hi @matheusjardimb , can you test the [branch](https://github.com/innoveit/react-native-ble-manager/tree/feat/write-descriptor) to see if it's working?

**Comment by matheusjardimb** [comment]
Sure! I'll check it out and give you a feedback asap

**Comment by matheusjardimb** [comment]
@marcosinigaglia, I just tested it and it seems to be working just fine. Thanks
