### ISSUE TITLE
permission is null

### ISSUE THREAD

**Issue by deeps0903** [innoveit/react-native-ble-manager#1158]
Problem Statement : sometimes I am getting permission is null and sometimes i am getting Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQU
EST_ENABLE cmp=com.android.settings/ com.transsion.bluetooth.RequestPermiss ionActivity ) from ProcessRecord{a8efbc2
17840:com.DHPApp/u0a256}
(pid=17840, uid=10256) requires android.permission.BLUETOOTH_CONNECT

-----------------------------------------------------------------------------------------
RN : 
  react-native: "0.64.4", using class based component 
 react-native-ble-manager: "8.0.2",
minSdkVersion = 30
compileSdkVersion = 33
targetSdkVersion = 33
Check in Real Device having Android Version 12 

In AndroidManifest file :
  <uses-permission android:name="android.permission.BLUETOOTH" tools:remove="android:maxSdkVersion"/>
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" tools:remove="android:maxSdkVersion"/>
  <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28" />
   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
   ------- NOTE ---------
  by adding this line my app is crash and no error found in my Terminal  :        
   <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/>
  ----------------------------------------------------------------------------------------------------------------------------
  First Approach :- 
  
async componentDidMount(){
    const BleManagerModule = NativeModules.BleManager;
    const BleManagerEmitter = new NativeEventEmitter(BleManagerModule);

 // turn on bluetooth if it is not on
  BleManager.enableBluetooth().then(() => {
    console.log('Bluetooth is turned on!');
  });

 // start bluetooth manager
  BleManager.start({ showAlert: false }).then(() => {
    console.log('BleManager initialized');
    this.handleGetConnectedDevices();
  });

  this.stopDiscoverListener = BleManagerEmitter.addListener(
    'BleManagerDiscoverPeripheral',
    (peripheral:any) => {
      const { peripherals } = this.state;
      peripherals.set(peripheral.id, peripheral);
      this.setState({ discoveredDevices: Array.from(peripherals.values()) });
    },
  );

  this.stopConnectListener = BleManagerEmitter.addListener(
    'BleManagerConnectPeripheral',
    (peripheral:any) => {
      console.log('BleManagerConnectPeripheral:', peripheral);
    },
  );

  this.stopScanListener = BleManagerEmitter.addListener(
    'BleManagerStopScan',
    () => {
      this.setState({ isScanning: false });
      console.log('Scan stopped');
    },
  );

// Ask to grant it access to turn on your location
  if (Platform.OS === 'android' && Platform.Version >= 23) {
    console.log('In verifyBluetoothAuthorization...',
    Platform.OS, Platform.Version)

    PermissionsAndroid.check(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
    ).then(result => {
      if (result) {
        console.log('Permission is OK');
      } else {
        PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        ).then(result => {
          if (result) {
            console.log('User accepted');
          } else {
            console.log('User refused');
          }
        });
      }
    });

  PermissionsAndroid.check(
      PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
    ).then(result => {
      if (result) {
        console.log('Permission is OK 2');
      } else {
        PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
        ).then(result => {
          if (result) {
            console.log('User accepted');
          } else {
            console.log('User refused');
          }
        });
      }
    });
  }
}

Second Approach : 

 handleAndroidPermissions = async () => {
  if (Platform.OS === 'android' && Platform.Version >= 31) {
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN)
  .then(result => {
    console.log('BLUETOOTH_SCAN permission result:', result);
  });
  
    try {

      const result = await PermissionsAndroid?.requestMultiple([
        PermissionsAndroid?.PERMISSIONS?.BLUETOOTH_SCAN,
        PermissionsAndroid?.PERMISSIONS?.BLUETOOTH_CONNECT,
      ]);
      console.log("rrrrrr", result)
      if (
        result[PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN] ===
          PermissionsAndroid.RESULTS.GRANTED &&
        result[PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT] ===
          PermissionsAndroid.RESULTS.GRANTED
      ) {
        console.debug(
          '[handleAndroidPermissions] User accepts runtime permissions android 12+',
        );
      } else {
        console.error(
          '[handleAndroidPermissions] User refuses runtime permissions android 12+',
        );
      }
    } catch (error) {
      console.error('[handleAndroidPermissions] Error requesting permissions:', error);
    }
  } else if (Platform.OS === 'android' && Platform.Version >= 23) {
    try {
      const checkResult = await PermissionsAndroid.check(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      );

      if (checkResult) {
        console.debug(
          '[handleAndroidPermissions] runtime permission Android <12 already OK',
        );
      } else {
        const requestResult = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        );

        if (requestResult === PermissionsAndroid.RESULTS.GRANTED) {
          console.debug(
            '[handleAndroidPermissions] User accepts runtime permission android <12',
          );
        } else {
          console.error(
            '[handleAndroidPermissions] User refuses runtime permission android <12',
          );
        }
      }
    } catch (error) {
      console.error('[handleAndroidPermissions] Error checking/requesting permissions:', error);
    }
  }
};
------------------------------------------------------------------------------------------------------------------------------
  
<img width="454" alt="Screenshot 2024-01-22 at 10 37 16 AM" src="https://github.com/innoveit/react-native-ble-manager/assets/155453809/8ab229da-dbd1-4f9b-81a1-4cb2b03620f5">

**Comment by marcosinigaglia** [comment]
Is not a library issue.
