### ISSUE TITLE
In ios Expo is not suppose?

### ISSUE THREAD

**Issue by Arbeliwus** [innoveit/react-native-ble-manager#1164]
![image](https://github.com/innoveit/react-native-ble-manager/assets/75787992/32a96515-8be1-42e0-a05e-005cec62d85f)

This is a problem I encountered in Expo.
 It can run normally in Expo in Android, but it cannot run in EXPO in IOS.
 This is the error code from IOS.
![image](https://github.com/innoveit/react-native-ble-manager/assets/75787992/fff25a91-77da-4c3a-9d73-6839f7ada917)
Can help me ?

**Comment by toni1703** [comment]
Hello, i think you need to make a development build before starting the app.

**Comment by marcosinigaglia** [comment]
https://github.com/innoveit/react-native-ble-manager/discussions/1079
