### ISSUE TITLE
How to clear cached BLE devices ?

### ISSUE THREAD

**Issue by rahulp9538** [innoveit/react-native-ble-manager#1165]
I am working with Bluetooth in react native. I just took the ble-manager example app, to see how it works and took some example code for BLE on my App. I have now somehow understand BLE and wanted to make it to my own. So I have changed the example code a lot, like new name. But the old name appears on my device, and not the new one. 

 - Device: Any Android phone
 - OS: Android
 - react-native-ble-manager version: 10.1.5
 - react-native version: 0.65 or above

**Comment by marcosinigaglia** [comment]
Can you explain in more detail? I don't understand your problem; if I relaunch the app, the 'cache' is already cleared.
