### ISSUE TITLE
Implement BleManager.disableBluetooth() ?

### ISSUE THREAD

**Issue by matheusjardimb** [innoveit/react-native-ble-manager#1174]
I see there is an `BleManager.enableBluetooth()` option in the docs, but I'd like to be able to disable BT as well (I'm implementing a toggle in my app). 

I couldn't find any related code nor previous issues about this. Would it be possible to implement?

Amazing lib, btw :)

**Comment by marcosinigaglia** [comment]
The enable/disable function is deprecated, the method `enableBluetooth` uses `ACTION_REQUEST_ENABLE`.  https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()
