### ISSUE TITLE
Android version under 21

### ISSUE THREAD

**Issue by anton-aleksandrov** [innoveit/react-native-ble-manager#118]
Hi
First of all, thank you for this library!

As far as i know, android versions under 21 support BLE only partially: able to scan but unable to advertise. Also, androids under 21 cover about 30% of all devices out there. 

1. What do you do about it?
2. Will other devices (both iphones and androids) be able to discover androids < 21 if they are using regular bluetooth in "discoverable" mode? Transferring data isn't needed, only discoverability. If so, do you know any cons against "simulating" BLE advertising with regular bluetooth in order to get mac address (or whatever device identification) from incapable androids? 

At least, android (v19) is able to discover both BLE advertising and regular bluetooth of an iphone in "Beacon toy" app. But ios 10 wasn't able even to discover regular android's bluetooth - perhaps it just wasn't displayed, as ios has restriction from transferring data with androids. I hope it will be able to get android's identifier at least.

Thanks :)

**Comment by marcosinigaglia** [comment]
Hi, you can't use this library for advertising.
