### ISSUE TITLE
BLE manager library not supporting API level 34. 

### ISSUE THREAD

**Issue by NikitaBH-Druck** [innoveit/react-native-ble-manager#1186]
Steps to reproduce
In Android 14(SDK 34) scan function is not working

Expected behavior
it should work as previous android versions

Actual behavior
App crash when call the BLE Scan 

Environment
React Native version: 0.73.6.
React Native platform + platform version: Android 14.0 

![MicrosoftTeams-image (7)](https://github.com/innoveit/react-native-ble-manager/assets/109963692/bf11a4b4-dad8-41c5-8136-e4a159d120c3)

**Comment by Sofrosine** [comment]
i also have this issue

**Comment by lucaswitch** [comment]
That should have a easy fix.

**Comment by NikitaBH-Druck** [comment]
I have made changes as per ([https://github.com/innoveit/react-native-ble-manager/pull/1188/files/e60195660ec1faa2a65eb9b35710abcdba853b91..9924eb4aa0f4691ad6c85d448c6c66ff67266d53)]) and tested on real device with android 14  but getting same error as attached screenshot.

**Comment by lucaswitch** [comment]
> I have made changes as per ([https://github.com/[/pull/1188](https://github.com/innoveit/react-native-ble-manager/pull/1188)/files/e60195660ec1faa2a65eb9b35710abcdba853b91..[9924eb4](https://github.com/innoveit/react-native-ble-manager/commit/9924eb4aa0f4691ad6c85d448c6c66ff67266d53))]) and tested on real device with android 14 but getting same error as attached screenshot.
> 
> We will need urgent support for this as users are using the Application for Android 14 also.

Added a change again, can you gently test it again?

**Comment by NikitaBH-Druck** [comment]
I have tested but not working, Does we also need to change TargetSDK version in build.gradle of react-native-Ble-manager from 33 to 34 for supports android 14...

**Comment by lucaswitch** [comment]
Just bought a Android 14 device. And can confirm https://github.com/innoveit/react-native-ble-manager/pull/1188/commits/dd29fa7bc5ae5d39a3346706c28143af53eae570 solves it.
