### ISSUE TITLE
Hundreads of logs while scanning

### ISSUE THREAD

**Issue by matheusjardimb** [innoveit/react-native-ble-manager#1187]
I'm getting dozens of logs "ReactNativeBleManager DiscoverPeripheral: null" (as seen below). I can reproduce the same behavior in many Android versions.

![image](https://github.com/innoveit/react-native-ble-manager/assets/468794/dce0796b-3bcb-43a7-999f-c4fe5ba8831d)

Would this massive amount of lots reduce performance in my app? 

To reproduce, I'm starting scan like this:

```
BleManager.scan([], 0, true, {
      matchMode: BleScanMatchMode.Sticky,
      scanMode: BleScanMode.LowLatency,
      callbackType: BleScanCallbackType.AllMatches,
  })
```

Should I be using other values in the scan method?

**Comment by marcosinigaglia** [comment]
Hi, it is normal. You have to filter the scan to have less result.
