### ISSUE TITLE
Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by morioniot** [innoveit/react-native-ble-manager#12]
Hi, 

Thanks for this excellent job. I was trying to scan for devices with this module but I can not make it work. I am developing an Android app using a Samsung Galaxy S3 phone with Android 4.3. I am also using the last version of React Native (0.29). I did all the configurations described in the README file, but when I try to run the application appears the error: "cannot read property 'scan' of undefined". Could you please help me with this problem?
![question](https://cloud.githubusercontent.com/assets/20360777/16859092/9e49e88e-49f1-11e6-81fb-42c9fe89227f.png)

**Comment by marcosinigaglia** [comment]
Hi, are you sure you add the BleManagerPackage in MainApplication?

**Comment by morioniot** [comment]
Hi Marco,
I am sure I did that. I modify the file android/app/src/main/java/com/{nameOfMyProject}/MainApplication.java Here is a screenshot:
![mainapplication](https://cloud.githubusercontent.com/assets/20360777/16874960/22b1aa88-4a62-11e6-8d3a-255c7ea1642e.png)

**Comment by marcosinigaglia** [comment]
Have you try to clean the node_modules dir and install the modules again?

**Comment by morioniot** [comment]
I cleaned the node_modules and installed them again. The error did not disappear.

**Comment by marcosinigaglia** [comment]
Is null the BleManager variable?

**Comment by morioniot** [comment]
Hi,
I think that the problem is in the root file of the module. The variable bleManager is undefined. So, maybe there is a problem in this line:

`var bleManager = React.NativeModules.BleManager;`

Here is the screenshot of the developer tools:
![developertools](https://cloud.githubusercontent.com/assets/20360777/16879400/0df1d456-4a76-11e6-9fdd-fd72b17464b0.png)

**Comment by marcosinigaglia** [comment]
Check in the device logs if it appears "BleManager initialized"

**Comment by morioniot** [comment]
Hi Marco,
I found what was the cause of the error. First, I had not re-compiled the entire project with "react-native run-android". When I did that I also found that i had to change the minSdkVersion in the build.gradle file. Now, everything is working just fine. I apologize if I represented a waste of time. Thanks a lot for all your help.
