### ISSUE TITLE
Characteristic beb5483e-36e1-4688-b7f5-ea07361b26a8 not found.

### ISSUE THREAD

**Issue by SulthanYS** [innoveit/react-native-ble-manager#1208]
**Describe the bug**
I have a BLE device, a temperature sensor that pushes data to a queue. I tried to connect the BLE device and send some data to the sensor from my react-native mobile app but when sending the data it logs the Characteristic beb5483e-36e1-4688-b7f5-ea07361b26a8 not found.. 

Steps I followed
  1. Initialize with (BleManager.start) and (BleManager.enableBluetooth)
  2. Scan for device using (BleManager.scan)
  3. Connect the device using (BleManager.connect)
  4. After connection success try to retrieve data using (BleManager.retrieveServices)
  5. During retrieve I check the connection status with (BleManager.isPeripheralConnected)
  6. After all this I send a data (for eg, a name) using (BleManager.write) with the device data retrieved from retrieveServices

**Screenshots**
![image](https://github.com/innoveit/react-native-ble-manager/assets/108971782/81fb4351-9fa6-41d1-bed6-7cf6719a562e)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M30s
 - OS: Android 11
 - react-native-ble-manager version: 11.5.1
 - react-native version: 0.73.6

**Comment by SulthanYS** [comment]
What else must I add to this issue to make it more understandable?

**Comment by lucaswitch** [comment]
Please download the app Ble Scanner on Playstore and check if the device characteristic is writable.

**Comment by SulthanYS** [comment]
Yeah, I checked that. It is both readable and writeable


![PXL_20240423_035451475 MP~2](https://github.com/innoveit/react-native-ble-manager/assets/108971782/c0eb0dbe-a8d5-42da-9e1a-959cda58c422)

**Comment by lucaswitch** [comment]
This is not a library issue. As i can see i'm still able to write characteristics without problem. But can you provide the code which you are calling "retrieveServices" and writing that characteristic?

**Comment by SulthanYS** [comment]
I found the issue and it is in the hardware part. Thanks for responding @lucaswitch 

I'll close this issue
