### ISSUE TITLE
[BleError: Cannot write to characteristic beb5483e-36e1-4688-b7f5-ea07361b26a8 with invalid data format: [248,0,0]]

### ISSUE THREAD

**Issue by Simeonhm** [innoveit/react-native-ble-manager#1223]
Hello,

I'm trying to send data (a color) from react native app to TTGO microcontroller.

Sometimes it works and sometimes I get this error:

[BleError: Cannot write to characteristic beb5483e-36e1-4688-b7f5-ea07361b26a8 with invalid data format: [r,g,b]]

Can somebody help me?

**Comment by marcosinigaglia** [comment]
There is stackoverflow for these questions, it is not a library problem.

**Comment by Simeonhm** [comment]
Could you still help me?
