### ISSUE TITLE
How to get all available ble as a list ?

### ISSUE THREAD

**Issue by Symous** [innoveit/react-native-ble-manager#124]
Hi,I am working on Android Platfrom(Android Studio).each time in the handleDiscoverPeripheral method it only return one ble instead of all available ble.is there any way to get all available ble ?
Thanks.

**Comment by marcosinigaglia** [comment]
Hi, the event is fired when the ble service find a new peripheral so you have the new peripheral in the event. If you want all the peripherals you can use getDiscoveredPeripherals.

**Comment by Symous** [comment]
Thank you! :D
