### ISSUE TITLE
Can't identify device ( Name is null for all devices )

### ISSUE THREAD

**Issue by aliwaqar981** [innoveit/react-native-ble-manager#1240]
**Describe the bug**
Name and Local name is null for all scanned devices

**To Reproduce**
1. Just run the example given in the repo

**Expected behavior**
Name should be available for most of the devices.

**Screenshots**
![WhatsApp Image 2024-06-21 at 12 23 39 AM](https://github.com/innoveit/react-native-ble-manager/assets/43547698/d0ba9645-23db-43d2-b306-9eb54faac640)

**Smartphone (please complete the following information):**
 - Device: Vivo v21e
 - OS: Android12
 - react-native-ble-manager version: ^11.5.5
 - react-native version: 0.74.2

**Additional context**
Mac address of device I'm trying to find is like 00:9C:C0:33:XX:XX but I'm not getting this while scanning through the example app. Although it's available when search from native bluetooth app of my phone.

**Comment by aliwaqar981** [comment]
@typester @seigel @quatrix @Volcore any help would be appreciated.

**Comment by varun761** [comment]
You can add a check if the device name is null don't display that. It will solve the issue that you are facing now.

**Comment by aliwaqar981** [comment]
name is null for all devices. If I place this check then there won't be any device left

**Comment by andreiwow2** [comment]
I think I might have the same issue, there is one device that I can find in the phone bluetooth list, but using react-native-ble-manager, not. On iOS it does work. The android permissions are correct, I can find other BLE devices, just this one not. So I assume it might find it but with a null name

**Comment by brianwachira** [comment]
I am also experiencing the same issue but with another library. ( react-native-ble-plx ) 
I came to issues just to see whether this lib has the same issues

**Comment by brianwachira** [comment]
> I am also experiencing the same issue but with another library. ( react-native-ble-plx ) I came to issues just to see whether this lib has the same issues

Update,  I ended up using React Native Bluetooth Classic. [https://kenjdavidson.com/react-native-bluetooth-classic/react-native/rn-bluetooth-classic/](https://kenjdavidson.com/react-native-bluetooth-classic/react-native/rn-bluetooth-classic/) In my use case, I am expected to send data between mobile devices & device name is needed ( inorder to identify device ). It seems Bluetooth low energy only allows smallest bytes of device information to be sent, hence name may miss at times

**Comment by timmyjose** [comment]
> > I am also experiencing the same issue but with another library. ( react-native-ble-plx ) I came to issues just to see whether this lib has the same issues
> 
> Update, I ended up using React Native Bluetooth Classic. https://kenjdavidson.com/react-native-bluetooth-classic/react-native/rn-bluetooth-classic/ In my use case, I am expected to send data between mobile devices & device name is needed ( inorder to identify device ). It seems Bluetooth low energy only allows smallest bytes of device information to be sent, hence name may miss at times

Hey @brianwachira, just curious -  I too have a usecase where I need to communicate between devices (`iOS` and `Android`). Did you manage to get the communication done using the library you linked to? If you have some demo app or pointers, that'd be great!
