### ISSUE TITLE
Does it not support low-power Bluetooth serial communication? I connected the IoT device through this plug-in, but I still can’t get the data returned by the IoT device.

### ISSUE THREAD

**Issue by 2096406288** [innoveit/react-native-ble-manager#1245]
Does it not support low-power Bluetooth serial communication? I connected the IoT device through this plug-in, but I still can’t get the data returned by the IoT device.

**Comment by marcosinigaglia** [comment]
There is no serial communication in Bluetooth, it is usually simulated by writing and receiving notifications as a response.
