### ISSUE TITLE
Hou can I do to improve Receive bluetooth Data speed?

### ISSUE THREAD

**Issue by zhanguangao** [innoveit/react-native-ble-manager#125]
Android 5.0 and Android 6.0 receive bluetooth data faster than Android 7.0 more than twice as fast, IOS10  is also slow.Hou can I do to improve receive bluetooth data speed for high version of the system.

**Comment by zhanguangao** [comment]
Android 5.0 and Android 6.0 log:
04-01 16:13:32.030  ReactNativeJS: 'Write success: ', 'FEFD810EFCFB'
04-01 16:13:32.105  ReactNativeJS: 'BluetoothUpdateValue', 'FEFDA18E000000000000005045502D4843303031'
04-01 16:13:32.137  ReactNativeJS: 'BluetoothUpdateValue', '04803B110000000000030201450C2E02FCFB'

Android 7.0 log:
04-01 16:44:11.278  ReactNativeJS: 'Write success: ', 'FEFD810EFCFB'
04-01 16:44:11.465  ReactNativeJS: 'BluetoothUpdateValue', 'FEFDA18E000000000000005045502D4843303031'
04-01 16:44:11.599 ReactNativeJS: 'BluetoothUpdateValue', '04803B110000000000030201450C2E02FCFB'

**Comment by marcosinigaglia** [comment]
Hi, I don't think you can improve the speed rate, which write mwthod do you use?

**Comment by zhanguangao** [comment]
writeWithoutResponse

**Comment by marcosinigaglia** [comment]
Is the fastest method, try to search in the android documentation for hints.

**Comment by zhanguangao** [comment]
I see. Thank you!

**Comment by McDreamy** [comment]
How to get the data from writeWithoutResponse on another device?
