### ISSUE TITLE
[IOS] App not requesting permission

### ISSUE THREAD

**Issue by barakataboujreich** [innoveit/react-native-ble-manager#1275]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**
A user using Iphone 14 with IOS 17 reported that the app is not requesting permission for bluetooth and getting blocked by the app. After reviewing the logs, the event from BleManagerDidUpdateState fired is **"unauthorized"**. 

I did the testing on Iphone 15 pro max with IOS 18. The bluetooth permission is asked automatically on App start. even if i deny the permission, i am able to enable it again from the settings. Weirdly enough the user is not able to enable it from the settings, since it does not appear there. 

After some research in the issues here, i understood that the IOS automatically requests the bluetooth permission when bluetooth added to the infoplist. 

No where in the documentation the bluetooth permission for the IOS is mentioned. Does anyone have an idea why the user iphone is not requesting the bluetooth permission? i already asked the user to reset location or privacy but it did no work.

**To Reproduce**
I am not able to reproduce the issue not on a physical device nor emulator

**Expected behavior**
The app should ask for bluetooth permission os start up. If the user denies the permission, he can enable it in the settings.

**Screenshots**
screenshots sent from the user
![IMG_0293 (1) (2)](https://github.com/user-attachments/assets/5537b7a5-100c-4712-984e-076069d832eb) ![IMG_0294 (1) (2)](https://github.com/user-attachments/assets/abba66fd-8f47-49d4-a7cb-1720e516fa1c)

**Smartphone (please complete the following information):**
 - Device: Iphone 14
 - OS: iOS 17
 - react-native-ble-manager version: 10.0.0
 - react-native version: 0.71.14

**Comment by marcosinigaglia** [comment]
The start method request the permission on ios
