### ISSUE TITLE
`NativeModules.BleManager` is null

### ISSUE THREAD

**Issue by Starman3787** [innoveit/react-native-ble-manager#1295]
I am getting the following error when trying to use this module:

```
`new NativeEventEmitter()` requires a non-null argument.
```

which happens here (app/components/ScanDevices.tsx:39)
```
console.log(NativeModules.BleManager);
const BleManagerModule = NativeModules.BleManager;
const bleManagerEmitter = new NativeEventEmitter(BleManagerModule);
```

i believe the issue is because the module is not linked correctly, but i've spent a long time trying to link the module and have had very little success. i'm not sure if auto linking is not working, since this is the first time i've used react native and don't know what behaviour i should expect from it.

i've tried the following:

- running `npm install --save react-native-ble-manager`
- adding `pod 'RNBleManager', :path => '../node_modules/react-native-ble-manager'` to `Podfile` followed by `cd ios && pod install` (i believe autolinking should have done this?? it didn't)
- adding `libRNBleManager.a` to "Link Binary With Libraries"

and then separately, i've tried adding `BleManager.xcodeproj` from the ios folder in this repo to "Libraries" in xcode and adding `libBleManager.a` to "Link Binary With Libraries", but this resulted in various errors when trying to import the react headers

i don't really know what i'm doing. i've never used react native, or native modules before, and can't really find any up to date information on what i should actually be doing beyond the docs.

the full code is here:

https://github.com/TeamSunride/tracie-app

any guidance on what i should try, or what i may have missed, would be greatly appreciated.

thanks!

**Comment by marcosinigaglia** [comment]
The autolink is working, you only need to run pod install. If is not working is a problem in your project.

**Comment by Starman3787** [comment]
@marcosinigaglia  thank you, appreciate the response. are you able to give me any guidance on what i should try or look into further? i've spent the last 2 days trying to get this working and am genuinely confused.

**Comment by thompsonnoah** [comment]
Hi @Starman3787,

I think this is because you may have installed the release candidate ([12.0.0-rc.3](https://www.npmjs.com/package/react-native-ble-manager/v/12.0.0-rc.3)). I ran into the same issue on this version, try downgrading to 11.5.7, and run this command:

`RCT_NEW_ARCH_ENABLED=0 bundle exec pod install`

This will disable the new architecture on your project, so just keep that in mind. I believe @marcosinigaglia and @lucaswitch are working on a new version that support the default architecture as of 0.76.

Hope this helps!

Noah

**Comment by Starman3787** [comment]
> Hi @Starman3787,
> 
> 
> 
> I think this is because you may have installed the release candidate ([12.0.0-rc.3](https://www.npmjs.com/package/react-native-ble-manager/v/12.0.0-rc.3)). I ran into the same issue on this version, try downgrading to 11.5.7, and run this command:
> 
> 
> 
> `RCT_NEW_ARCH_ENABLED=0 bundle exec pod install`
> 
> 
> 
> This will disable the new architecture on your project, so just keep that in mind. I believe @marcosinigaglia and @lucaswitch are working on a new version that support the default architecture as of 0.76.
> 
> 
> 
> Hope this helps!
> 
> 
> 
> Noah

thank you so so much, this fixed everything 

really appreciate the help

**Comment by Starman3787** [comment]
@thompsonnoah i seem to be getting the following error when trying to install pods with `RCT_NEW_ARCH_ENABLED=0 bundle exec pod install` now. any chance you're aware of a workaround for this?

the error:

```
[!] Invalid `Podfile` file: exit.

 #  from /....../APP/ios/Podfile:20
 #  -------------------------------------------
 #  target 'main' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

[!] The command: 'node -e process.argv=['', '', 'config'];require('@react-native-community/cli').run()' returned a status code of 1
    - In order to autolink using Cocoapods, this framework uses @react-native-community/cli to discover
    React Native native modules
    - Please either add it: yarn add -D @react-native-community/cli or consult your framework's
    documentation.
```

**Comment by suhitaga** [comment]
@Starman3787 I was facing the same issue, and it turned out that I have the event listener module declared as such:
```ts
const BleManagerModule = NativeModules.BleManager;
export const bleEmitter = new NativeEventEmitter(BleManagerModule);
```

It just needed some null checks to behave properly.

```ts
const BleManagerModule = NativeModules.BleManager || {};
export const bleEmitter = BleManagerModule
  ? new NativeEventEmitter(BleManagerModule)
  : null;
```

**Comment by cena001plus** [comment]
> Hi [@Starman3787](https://github.com/Starman3787),
> 
> I think this is because you may have installed the release candidate ([12.0.0-rc.3](https://www.npmjs.com/package/react-native-ble-manager/v/12.0.0-rc.3)). I ran into the same issue on this version, try downgrading to 11.5.7, and run this command:
> 
> `RCT_NEW_ARCH_ENABLED=0 bundle exec pod install`
> 
> This will disable the new architecture on your project, so just keep that in mind. I believe [@marcosinigaglia](https://github.com/marcosinigaglia) and [@lucaswitch](https://github.com/lucaswitch) are working on a new version that support the default architecture as of 0.76.
> 
> Hope this helps!
> 
> Noah

Therefore, a new architecture cannot be used; otherwise, there would be a huge problem.
