### ISSUE TITLE
App Crashes On Low End Devices

### ISSUE THREAD

**Issue by vancityAyush** [innoveit/react-native-ble-manager#1298]
`java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0xac0790c4
                                                                                                    java_vm_ext.cc:577]     from void com.facebook.jni.NativeRunnable.run()`
I am Using Android version 11 and BleManager in causing crash.
I have used react-native-ble-manager v12.0.0
I have also attached the crash logs 
[
[log.txt](https://github.com/user-attachments/files/18082919/log.txt)
](url)

**Comment by marcosinigaglia** [comment]
Are you using the new RN architecture?

**Comment by vancityAyush** [comment]
Yes, I am using the new RN architecture

**Comment by vancityAyush** [comment]
> Are you using the new RN architecture?

Yes, I am using the new RN architecture

**Comment by marcosinigaglia** [comment]
I tried today with and Android 11 and is working, check your app configuration.
