### ISSUE TITLE
Add option for scanning duplicates

### ISSUE THREAD

**Issue by rclai** [innoveit/react-native-ble-manager#13]
Currently, all scanning filters out duplicates.

https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBCentralManager_Class/index.html#//apple_ref/doc/constant_group/Peripheral_Scanning_Options

**Comment by marcosinigaglia** [comment]
Try [1.1.0](https://github.com/innoveit/react-native-ble-manager/releases/tag/v1.1.0)
