### ISSUE TITLE
ios BleManager.connect Exception

### ISSUE THREAD

**Issue by panmin** [innoveit/react-native-ble-manager#134]
i used(run ios device):
BleManager.connect('EA:EC:6B:1B:5D:98')
            .then((peripheralInfo) => {
                // Success code
                console.log('Connected');
            })
            .catch((error) => {
                // Failure code
                console.log('error');
            });
but it don't go to  Success code and  Failure code，it has an error:
ExceptionsManager.js:71 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking connect on target BleManager with params (
    "EA:EC:6B:1B:5D:98",
    23
)

please help me!!

**Comment by catherinessssss** [comment]
Same problem.

**Comment by catherinessssss** [comment]
Same Problem. 


let peripheralId = this.state.ble.id;
BleManager.connect(peripheralId).then((peripheralInfo) => {
	console.log('Connected');
	console.log(peripheralInfo);
})
.catch((error) => {
        console.log('error');
});

It don't go to Success code and Failure code.

**Comment by marcosinigaglia** [comment]
Versions?

**Comment by catherinessssss** [comment]
My version is 3.1.2

**Comment by catherinessssss** [comment]
It doesn't  work after I've updated the version to 3.2.0.

**Comment by panmin** [comment]
@catherinessssss did you run ios?

**Comment by catherinessssss** [comment]
Yes.

**Comment by panmin** [comment]
@catherinessssss  “this.state.ble.id” the value is?

**Comment by catherinessssss** [comment]
"this.state.ble.id" is the id of my sensor device. Have you solve this problem?

**Comment by panmin** [comment]
@catherinessssss in android the id is "EA:EC:6B:1B:5D:98"，but in ios the id is not the value,the same device.

**Comment by catherinessssss** [comment]
I have not run my program on android before. But I can get the id when it running on ios. 
Have you import the BleManager.xcodeporj to your ios libraries?

**Comment by panmin** [comment]
@catherinessssss yes,i had import it to my ios libraries with xcode，i use 3.2.0 . what's you error info

**Comment by catherinessssss** [comment]
There was not error show up. It's just do go success code and failure code.

**Comment by panmin** [comment]
@marcosinigaglia i write the mac address wrong,when i write it right,it works success.can you solve the bug? when the mac address error,it can go to failure code.

**Comment by marcosinigaglia** [comment]
Fix in 3.2.1
