### ISSUE TITLE
Customizing ScanSettings (Android)

### ISSUE THREAD

**Issue by comann** [innoveit/react-native-ble-manager#142]
### Version

Tell us which versions you are using:

- react-native-ble-manager v3.2.0
- react-native v0.44.0

### Feature
The ability to control the [ScanSettings flags](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder.html) on android. If y'all are accepting pull requests I can make this one happen.

Essentially, I have a requirement that needs to ability to change the [number of matches](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder.html#setMatchMode(int)) before a device is considered discovered. In additional plus would be to set the scan mode type and match mode.  Are these flags something that I could incorporate into the options when creating the BleManager instance in JS (BleManager.start({}) and thus be passed to the ScanManager implementation.

Cheers,

**Comment by marcosinigaglia** [comment]
Hi @comann, if you mantain the flag optional there isn't problem if you want to add this option.
Thanks.
