### ISSUE TITLE
Question about Write in hex

### ISSUE THREAD

**Issue by stephenjen** [innoveit/react-native-ble-manager#146]
The write function expects data to be in Base64 format, however, my BLE module expects all writes to it to be in hex.  I'm currently not getting a response when I write to my module and I'm wondering if I'm sending data in the wrong format.  Is there a way to get this to work with data in hex?

Thanks!

**Comment by Philipwzj** [comment]
How did you solve this?

**Comment by stephenjen** [comment]
This worked for me on version 5.0.3:

`var url = "WHAT_YOU_WANT_TO_WRITE";`
`            var data1 = [];`
`            for (var i = 0; i < url.length; i++){`
`                data1.push(url.charCodeAt(i));`
`            }`

Then

`BleManager.write(id, service, characteristic, data1)`
`.then(() => {`
`              })`
