### ISSUE TITLE
Send data

### ISSUE THREAD

**Issue by marwakhalil** [innoveit/react-native-ble-manager#147]
Hello,
Does this library allow me to connect and sending data to DA14680 chip (a ble device) through my react native app ? 
Thanks

**Comment by marcosinigaglia** [comment]
Hi @marwakhalil , if the chip support the BLE you can connect and write/read data.

**Comment by marwakhalil** [comment]
Hi @marcosinigaglia   Thanks, and how about connecting to an advertised smartphone, i'm actually advertising my android phone for testing as an iBeacon i couldn't connect, will that be possible cause i've noticed that the mac id is generated, so will it be possible to connect to a smartphone advertised as beacon

**Comment by marcosinigaglia** [comment]
No, you can only act as a client, if you have experience you can implement the advertsing part.

**Comment by marwakhalil** [comment]
A okay thanks for that man
