### ISSUE TITLE
Bluetooth connection examples

### ISSUE THREAD

**Issue by tarang9211** [innoveit/react-native-ble-manager#15]
Could you post some more examples on how to connect to a device?

I tried using the examples from the README.md to connect my iphone to my mac using the UUID and MAC address, but none of them worked.

Thanks!

**Comment by marcosinigaglia** [comment]
Hi, you have to scan for the peripherals and then use the id of the peripheral to connect.

**Comment by tarang9211** [comment]
So first I would call `BleManage.scan()` and then `connect` right? So will the `scan()` method return a list of UUID or MAC addresses of active bluetooth devices?

**Comment by marcosinigaglia** [comment]
First you have to handle BleManagerDiscoverPeripheral event, then start the scan and you receive the peripheral finded.

**Comment by tarang9211** [comment]
Hi Marco, I tried that. Does this code look right?

`DeviceEventEmitter.addListener('BleManagerDiscoverPeripheral', (args) => {
        console.log(args);
    });

    BleManager.scan([], 5, true)
    .then(() => {
        console.log('here');
    })
`

**Comment by marcosinigaglia** [comment]
Try this:

```javascript
componentDidMount() {
  this.handleDiscoverPeripheral = this.handleDiscoverPeripheral.bind(this);

  NativeAppEventEmitter.addListener(
    'BleManagerDiscoverPeripheral',
    this.handleDiscoverPeripheral
  ); 
}

btnPress() {
  BleManager.scan([], 5);
}

handleDiscoverPeripheral(data){
  console.log(data);
}
```

**Comment by DarrylD** [comment]
That example would be awesome for documentation example
