### ISSUE TITLE
Trouble in reading write's response promise

### ISSUE THREAD

**Issue by alexandrapersea** [innoveit/react-native-ble-manager#150]
Hello,

I'm trying to read write's response. The documentation says that write returns a Promise object. From what i see there's no example on how to read it. Can you read the device's response after the write command?

**Comment by WillDent** [comment]
+1

**Comment by marcosinigaglia** [comment]
Hi, the 'response' is only the confirmation that you write the value. If you expect some in return from the device maybe you have to use the notification.

**Comment by alexandrapersea** [comment]
From what i see `startNotification`  returns a fulfilled promise with no value. I'm a bit confused on how to get to the actual response of the device after write.

**Comment by marcosinigaglia** [comment]
After you started the notification you retrieve the values from `BleManagerDidUpdateValueForCharacteristic` event.
