### ISSUE TITLE
write() never succeed while notification on

### ISSUE THREAD

**Issue by w8choi** [innoveit/react-native-ble-manager#154]
### Version
- react-native-ble-manager v3.2.1
- react-native v0.44.0

### Expected behaviour

- BleManager.write(peripheralId, serviceUUID, characteristicUUID, data) should successfully write to BLE device while receiving notification regularly at PRIORITY_HIGH (interval=12)

### Actual behaviour

- Throwing "Write failed" every time I try to write something to the device. Tried solution #103 but didn't solve the problem either.

### Steps to reproduce

1. start notification
2. try writing to ble device

**Comment by marcosinigaglia** [comment]
Hi, iOS or Android? Have you tried to add an higher timeout delay?

**Comment by w8choi** [comment]
on both actually.. I've tried adding 1- 5000 with no success :(

**Comment by w8choi** [comment]
actually I think it's working on iOS if I remove the event listener and write and then add the listener again but that didn't solve it on android

**Comment by marcosinigaglia** [comment]
Hi, check on the device documentation, unfortunately each device has some difference and behaviors.
