### ISSUE TITLE
Connected to the iOS app with bonding

### ISSUE THREAD

**Issue by yedeba** [innoveit/react-native-ble-manager#16]
It's possible that device connected to the iOS app with bonding?
Thanks

**Comment by marcosinigaglia** [comment]
Hi, what do you mean?

**Comment by yedeba** [comment]
For example: method bond
https://github.com/randdusing/cordova-plugin-bluetoothle
thanks

**Comment by marcosinigaglia** [comment]
I don't think you can pair a ble device on iOS. The cordova plugin don't support the bond command on iOS.
