### ISSUE TITLE
Scanning for service-uuids not working on Android

### ISSUE THREAD

**Issue by vikeri** [innoveit/react-native-ble-manager#161]
### Version

Tell us which versions you are using:

- react-native-ble-manager v5.0.3
- react-native v0.44.0
- Android 7.1.2

### Expected behaviour

When scanning only for specific service UUID's it should find all devices with those ids.

### Actual behaviour

It finds no devices at all.

### Steps to reproduce

1. Start scan and specify a service UUID in the array
2. Have an available BLE unit with that service UUID
3. See that nothing is found in the scan

### Stack trace and console log

No errors thrown. I checked the native logs and the UUID is printed correctly [here](https://github.com/innoveit/react-native-ble-manager/blob/b7a3e44656f85e67b23474af5acd5fc9bc63eeb1/android/src/main/java/it/innove/LollipopScanManager.java#L55)

**Comment by marcosinigaglia** [comment]
I think the code is wrong.

**Comment by marcosinigaglia** [comment]
Can you try this change?
`ScanFilter filter = new ScanFilter.Builder().setServiceUuid(new ParcelUuid(UUIDHelper.uuidFromString(serviceUUIDs.getString(i)))).build();`

**Comment by marcosinigaglia** [comment]
There are some issues with the scanning:
https://github.com/iDevicesInc/SweetBlue/wiki/Android-BLE-Issues

**Comment by vikeri** [comment]
Changed it and it still doesn't work... Even opened it in the debugger and it the UUID is correct there. Maybe an Android issue as you suggested

**Comment by vikeri** [comment]
The SweetBlue library seems pretty sweet (pun intended). Maybe migrate to that as a backend in the future if these issues persist?

**Comment by marcosinigaglia** [comment]
Yes, is not a bad idea.

**Comment by vikeri** [comment]
This was an internal bug. Someone accidentally stopped broadcasting our services...
