### ISSUE TITLE
[Question] Pairing/Bonding support

### ISSUE THREAD

**Issue by ericschaal** [innoveit/react-native-ble-manager#169]
Hi,

Does this library support bonding/pairing? That is, if you try to write to a protected characteristic, will iOS and Android start a bonding procedure?

Thanks!

**Comment by whitedogg13** [comment]
Hi @ericschaal ,
Yes, this library can be used with bonding procedure.
You simply call BleManager's `connect` to the peripheral, and if the peripheral itself requires Bluetooth SM (security manager) feature such as bonding, the OS itself will prompt the user with the confirm dialog. It works on both iOS and Android per my experience.
