### ISSUE TITLE
Android Integration Issues

### ISSUE THREAD

**Issue by Zafeer** [innoveit/react-native-ble-manager#17]
**I have been unable to get the module working in a demo android app.**

Can you confirm 
1. The current module stands compatible with the latest versions of react and react-native (
e.g. on close inspection in the latest version of react-native to call NativeModules one has to use 
import { NativeModules } from 'react-native'; ) ??

**The following is a simple code written in index.android.js but BleManager always returns undefined..**

`
import React, { Component } from 'react';
import { BleManager } from 'react-native-ble-manager';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class bluetooth extends Component {

  componentWillMount () {
    //BleManager returns undefined//
    console.log(BleManager.checkState())
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  }
});

AppRegistry.registerComponent('bluetooth', () => bluetooth);
`

I have followed all the steps of adding code in 
1 . app/build.gradle
2. android/settings.gradle
3. MainApplication

**But The BleManager always returns undefined...**

**Comment by marcosinigaglia** [comment]
Hi, I test the last version with RN 0.29, try look on this [post](https://github.com/innoveit/react-native-ble-manager/issues/12)
