### ISSUE TITLE
Clarify why one shouldn't read/write/connect during scan

### ISSUE THREAD

**Issue by Looveh** [innoveit/react-native-ble-manager#177]
The Readme states (https://github.com/innoveit/react-native-ble-manager#note) that one should avoid to read/write/connect while scanning but this is a trait I've never encountered while working with Bluetooth previously and looking at the code I don't find it self evident why this should be avoided.

A clarification to this would be much appreciated.

**Comment by marcosinigaglia** [comment]
Hi @Looveh, I do not remember where exactly but I found this information in many forum discussion about old devices problem. Probably with the newest devices and OS there are not the same problems. I change the doc with different terms, thanks.
