### ISSUE TITLE
Android Bluetooth data analysis

### ISSUE THREAD

**Issue by songxiaoliang** [innoveit/react-native-ble-manager#182]
At the moment I have already read the data on my Android phone via Bluetooth, but the data is an array, such as: [10,34,26,98,75,56,82], how can I convert this array to a string or correct Data? Ask the author to reply.

**Comment by marcosinigaglia** [comment]
https://stackoverflow.com/questions/3195865/converting-byte-array-to-string-in-javascript

**Comment by songxiaoliang** [comment]
@marcosinigaglia thanks~
