### ISSUE TITLE
I can't write the message to another Bluetooth

### ISSUE THREAD

**Issue by Eleven1108** [innoveit/react-native-ble-manager#184]
when i use the Module of write it always tell me that Writing is not permitted. why i can't write the message to Bluetooth? thanks

**Comment by Eleven1108** [comment]
when i use the Module of write it always tell me that  Writing is not permitted. why i can't write the message to Bluetooth? thanks

**Comment by marcosinigaglia** [comment]
Probably the characteristics is not writable.
