### ISSUE TITLE
Getting error "The callback connect() exists in module BleManager, but only one callback may be registered to a function in a native module

### ISSUE THREAD

**Issue by Philipwzj** [innoveit/react-native-ble-manager#186]
![screen shot 2017-07-10 at 4 33 48 pm](https://user-images.githubusercontent.com/22140215/28038832-2c7e733c-658e-11e7-9c28-e4ce8d940304.png)

![screen shot 2017-07-10 at 4 34 14 pm](https://user-images.githubusercontent.com/22140215/28038835-33704210-658e-11e7-924c-da8c757a6923.png)

Thank you!

**Comment by marcosinigaglia** [comment]
Hi, the second connect probably was call in the catch block. Try to add a timeout before retry.
