### ISSUE TITLE
List of devices

### ISSUE THREAD

**Issue by sergei-zelinsky** [innoveit/react-native-ble-manager#19]
Hi everyone! 
How can I get the list of all available bluetooth devices?

**Comment by marcosinigaglia** [comment]
Hi, https://github.com/innoveit/react-native-ble-manager/issues/15

**Comment by sergei-zelinsky** [comment]
I tried this examples. But there was no devices in time of scanning.

**Comment by marcosinigaglia** [comment]
Try to use an app like SmartDisover or LightBlue to verify the presence.
