### ISSUE TITLE
Error with reactNative version 0.47.1

### ISSUE THREAD

**Issue by Philipwzj** [innoveit/react-native-ble-manager#195]
Error happens when I run Android, and it gave me the following information:
`:react-native-ble-manager:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/philipwang/Desktop/Sidekick/node_modules/react-native-ble-manager/android/src/main/java/it/innove/BleManagerPackage.java:26: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: /Users/philipwang/Desktop/Sidekick/node_modules/react-native-ble-manager/android/src/main/java/it/innove/LegacyScanManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
`
It works perfectly fine with reactNative 0.46.4 and below

**Comment by whitedogg13** [comment]
Hi @Philipwzj @marcosinigaglia ,

This one is related to an breaking change of RN47:
* https://github.com/facebook/react-native/releases/tag/v0.47.0
* https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

I just make a PR #197 

Thanks!

**Comment by marcosinigaglia** [comment]
Thanks
