### ISSUE TITLE
I have troubles migrating to new version which has no support for base64 strings anymore.

### ISSUE THREAD

**Issue by unlabeled** [innoveit/react-native-ble-manager#196]
I have strings like "vol=1\n" which were converted to base64 lately. Need some hints how to convert them to the new data format.

**Comment by marcosinigaglia** [comment]
Now you have a byte array, are you reading the value?

**Comment by unlabeled** [comment]
I was writing the data. I solved my case and made a pull request with minor README update, which I guess can help others.
