### ISSUE TITLE
‘allowDuplicates’ is not an argument of function 'start'

### ISSUE THREAD

**Issue by adyanced** [innoveit/react-native-ble-manager#199]
### Version

Tell us which versions you are using:

- react-native-ble-manager v5.1.1
- react-native v0.47.1
- Android v7.0

In example file 'app.js' there is a mistake
`BleManager.start({showAlert: false, allowDuplicates: false});`
I read the documents and source code and found 'allowDuplicates' is not an option of 'start' but 'scan'. It should be corrected.

And question is
`  componentWillUnmount() {

    this.handlerDiscover.remove();

    this.handlerStop.remove();

    this.handlerDisconnect.remove();

    this.handlerUpdate.update();

  }`
why is not `this.handlerUpdate.remove();` ?

**Comment by marcosinigaglia** [comment]
Hi, it's an error, I'll correct it.
