### ISSUE TITLE
Disconnect to device before app shuts down

### ISSUE THREAD

**Issue by henninghall** [innoveit/react-native-ble-manager#20]
Hi! Is there any way to disconnect to a device when the app shuts down? Since we don't want any leaking open connections. How do you other guys deal with it? I have tried to put the the disconnection request in the componentWillUnmount function but it doesn't work. 
Thanks.

**Comment by marcosinigaglia** [comment]
Hi, have you try in the AppState change?

**Comment by henninghall** [comment]
Oh, I found out that the device always disconnected automatically when the app shut down. The problem seems to only occur when I reloaded the app during development. AppState works as well if you for instance want to close the connection when the screen turns off.
