### ISSUE TITLE
Can I take 'XXXX' as the parameter of serviceUUID and characteristicUUID?

### ISSUE THREAD

**Issue by zhanguangao** [innoveit/react-native-ble-manager#202]
start the notification：
`BleManager.startNotification(peripheralId, serviceUUID, characteristicUUID)
`

![image](https://user-images.githubusercontent.com/13374669/29605293-e9e6eade-881c-11e7-90be-48ece91d5cb7.png)

Can I take '1801' as  the parameter  of serviceUUID , take '2A23' as  the parameter  of characteristicUUID, because the returned UUID parameters  are four strings.
I try it，but fail.

**Comment by marcosinigaglia** [comment]
Hi, are you sure that the notification is supported on this characteristic?

**Comment by zhanguangao** [comment]
@marcosinigaglia  All of the serviceUUID and characteristicUUID I got are the type of 'XXXX',I can't start notification and write.does it support this bluetooth?

**Comment by marcosinigaglia** [comment]
In your example the 2A50 characteristic is only writable, you have to check the 2A23 characteristic.

**Comment by zhanguangao** [comment]
but get error when I execute the BleManager.write().

**Comment by KarthickCSK** [comment]
Im using BLE simulator and im getting serviceUUID and characteristicsUUID of type XXXX. When i try to call a read funct with characteristics belongs to readable it throws error. ie, Chracteristics not found.

**Comment by abikalwa** [comment]
I too face the same error. Unable to Read the characteristic Data.

**Comment by zhanguangao** [comment]
I See.They are the base UUID '0x0000xxxx-0000-1000-8000-00805F9B34FB',So we can replace 'xxxx' manually.If we get '1801', the UUID is '0x00001801-0000-1000-8000-00805F9B34FB'.
