### ISSUE TITLE
BleManager.removePeripheral(peripheral.id) is not a function error?

### ISSUE THREAD

**Issue by AshokICreate** [innoveit/react-native-ble-manager#206]
"react-native-ble-manager": "6.0.0",

`BleManager.removePeripheral(peripheral.id) is not a function error?`

**Comment by stephenjen** [comment]
@AshokICreate I just tried this and it seems the error is only in iOS for me.  Looking at the merge I'm not sure if it was implemented for iOS.

**Comment by marcosinigaglia** [comment]
In iOS is not implemented.

**Comment by stephenjen** [comment]
I'm having the issue where reconnect does not work in iOS when the my code follows these steps:

1 Scan
2 Connect
3 Get and save peripheral ID
4 StopScan
5 Disconnect
6 Connect
7 WriteWithoutReponse

In Android, the when I turn off the BLE device and then turn it back on, it reconnects.  In iOS, however, it does not reconnect.  iOS if I restart the app, which starts fro step 6 above, it can connect and reconnect without problem.  

What might be the problem?

**Comment by marcosinigaglia** [comment]
Do you have some error?

**Comment by stephenjen** [comment]
The steps I described generates no error, just cannot reconnect in iOS if scanning occurred first.  I thought BleManager.removePeripheral might do the trick, but as you said it's not implemented in iOS.

**Comment by marcosinigaglia** [comment]
Did you saw something in the device log?

**Comment by stephenjen** [comment]
After the disconnect listener is handled there's nothing else.

**Comment by kf729ik** [comment]
Same issue like @stephenjen, IOS cannot reconnect, if I restart the app it works fine.

**Comment by stephenjen** [comment]
@kf729ik my issue was due to calling start() more than one times.  I had to restructure all my BLE operations to within one action file so I wouldn't need to call start() more than once.

**Comment by kf729ik** [comment]
@stephenjen I think that I'm facing the same issue, so I'm going to try out this approach, thanks for the comment.
