### ISSUE TITLE
Device name 

### ISSUE THREAD

**Issue by vincenzoiacovone** [innoveit/react-native-ble-manager#21]
Why device name is always null? I tried with iOS

Bluetooth.scan([], 5, false)
    .then(() => {
      // Success code
      console.log('Scan started');
    });

NativeAppEventEmitter.addListener(
      'BleManagerDiscoverPeripheral',
      (args) => {
          console.log(args)
      }
    );

args is object like this:
{ id: 'C92C740D-A084-FAB7-7A44-251D12F7D099',
  advertising: { kCBAdvDataIsConnectable: true } }
2016-08-05 18:43:12.399 [info][tid:com.facebook.react.JavaScript] { id: 'C92C740D-A084-FAB7-7A44-251D12F7D099',
  advertising: 
   { kCBAdvDataServiceData: 
      { '8EB5': 
         { CDVType: 'ArrayBuffer',
           data: 'AZAGmKhr6ZF2x0/EiSpVGs8Hx3wADgK7+ANY' } },
     kCBAdvDataIsConnectable: true } }

**Comment by marcosinigaglia** [comment]
Hi, maybe the BLE device has no name.

**Comment by vincenzoiacovone** [comment]
The name exists, if i search devices in bluetooth section, i found it with his name..

**Comment by marcosinigaglia** [comment]
Do you see any error on XCode log?

**Comment by vincenzoiacovone** [comment]
No errors. It is possible that my device is not low energy or the version is Lower then 4.0? I read that corebluetooth framework is working only with low energy and an uuid is required for scan.

http://stackoverflow.com/questions/10178293/how-to-get-list-of-available-bluetooth-devices

Il 08/ago/2016 10:28, Marco Sinigaglia <notifications@github.com> ha scritto:

Do you see any error on XCode log?

**Comment by marcosinigaglia** [comment]
Try an app like SmarDiscover or LightBlue and see the scan results.

**Comment by vincenzoiacovone** [comment]
No results with this apps too. It supported only ble peripherals?

Il 08/ago/2016 11:20, Marco Sinigaglia <notifications@github.com> ha scritto:

Try an app like SmarDiscover or LightBlue and see the scan results.

**Comment by marcosinigaglia** [comment]
On iOs you have limitation by [MFI](https://mfi.apple.com/MFiWeb/getFAQ.action).

**Comment by RameshAmzur** [comment]
Hi 
In android also getting name as null. Tested with another application and it is showing device names.

**Comment by EduardoRicardez** [comment]
In android also getting name as null too
