### ISSUE TITLE
Unable to find any devices. IOS

### ISSUE THREAD

**Issue by Sprit3Dan** [innoveit/react-native-ble-manager#217]
Hello! Tried to use the plugin, figured how to subscribe to events, that have to be spawned while scanning via `BleManagerDiscoverPeripheral`. Everything went well, though, no events were dispatched. Tried to use your example project from repo, same thing. No exceptions, no logs, just no devices discovered, though through IOS settings I can see few available to connect. Have seen issue https://github.com/innoveit/react-native-ble-manager/issues/215, however it doesn't look handy in my case.

Is there any suggestion where to explore further? Thanks in advance!

"react-native": "0.48.3",
"react-native-ble-manager": "^6.1.1",
tested on Iphone 7 IOS 11 & Iphone 5s IOS 10.3.3

**Comment by marcosinigaglia** [comment]
Did you see peripherals If you use LightBlue app?

**Comment by Sprit3Dan** [comment]
@marcosinigaglia, Yeah, LightBlue found devices, though I had to restart my bluetooth on app launch, since app didn't catch that my BT is enabled. Could this be the case and the issue is somewhere here?

**Comment by Sprit3Dan** [comment]
Well, it certainly helped. Looks like there's an issue with Bluetooth status on app startup, and it prevents plugin to perform well. Thanks for pointing me out to LightBlue!

**Comment by marcosinigaglia** [comment]
Check that you have to call the `start` function before other calls and only one time.

**Comment by Sprit3Dan** [comment]
Truth is that I found this issue earlier and developed the bluetooth-service the right way as I understand. Here's the code.
```
import { Observable } from 'rxjs/Rx';
import * as BleManager from 'react-native-ble-manager'
import { NativeEventEmitter, NativeModules } from 'react-native'

import { injectable } from '../';

abstract class BluetoothServiceApi {
	abstract searchDevice(services?: Array<any>, seconds?: number): Observable<any>
}

@injectable()
export class BluetoothService {
	private bluetoothReady: Promise<BluetoothServiceApi>;
	private bleManagerEmitter: NativeEventEmitter;

	private api = {
		searchDevice: this.searchDevice.bind(this),
	};

	constructor() {
		this.bleManagerEmitter = new NativeEventEmitter(NativeModules.BleManager);

		this.bluetoothReady = new Promise((res, rej) => {
		BleManager.start({ showAlerts: true, forceLegacy: true })
			.then(() => {
				res(this.api);
				console.info('bt started');
			});
		});
	}

	public get ready(): Promise<BluetoothServiceApi> {
		return this.bluetoothReady;
	}

	private searchDevice(services: Array<any> = [], seconds: number = 5): Observable<any> {
		let scanEmitter;
		
		BleManager.scan(services, seconds)
			.then(() => console.info('scan started'));
			
		this.bleManagerEmitter.addListener('BleManagerDiscoverPeripheral', (data) => {
			console.log(data);
		});
			
		return new Observable<any>(emitter => scanEmitter = emitter);
		// return Observable.fromEvent(this.bleManagerEmitter, 'BleManagerDiscoverPeripheral');
	}
}
```

and the usage of it.

```
@inject(BluetoothService) btService: BluetoothService;
  
  componentWillMount() {
    this.btService.ready.then(api =>
      api.searchDevice().subscribe(data => console.log(data))
    );
  }
```

Though, it didn't help much

**Comment by Ilario17** [comment]
@Sprit3Dan how did you solve this issue?
