### ISSUE TITLE
this module can support  bluetooth 2.0 device  and 4.0 device

### ISSUE THREAD

**Issue by ninjai001** [innoveit/react-native-ble-manager#227]
in android ,this module can support  bluetooth 2.0 device  and 4.0 device  ?

**Comment by marcosinigaglia** [comment]
Hi, theoretically the Bluetooth is backward compatible but I never try.

**Comment by ninjai001** [comment]
I read the code ，it cant support bluetooth 2.0

**Comment by marcosinigaglia** [comment]
Ok, thanks.
