### ISSUE TITLE
BleManager.enableBluetooth "Bluetooth Permission Request" pop up behind Android alert dialog

### ISSUE THREAD

**Issue by peconia** [innoveit/react-native-ble-manager#229]
### Version
- react-native-ble-manager v6.2.0
- react-native v0.48.3
- Android v.6.0.1

I am using BleManager.enableBluetooth() to show a dialog to enable Bluetooth. This is working as in the dialog appears, but the problem is that there is an additional pop up text "Bluetooth Permission Request" partially visible behind the alert dialog. The text is dismissed when the dialog is dismissed. How can I prevent the "Bluetooth Permission Request" text from showing?
 
Here is an image of the issue:
![image](https://user-images.githubusercontent.com/7756669/31456916-1b62b540-aeb3-11e7-930e-2e45eed6f469.png)

**Comment by marcosinigaglia** [comment]
Hi, Is a privacy notification from the OS so I don't think is possible to disable it.
