### ISSUE TITLE
Configure the connection interval of Bluetooth GATT to speed up the data transfer rate (Question)

### ISSUE THREAD

**Issue by SivaRapolu** [innoveit/react-native-ble-manager#231]
### Version

Tell us which versions you are using:

- react-native-ble-manager v : 5.0.3
- react-native v : 0.44.0
- iOS/Android v. Android M 6.0

### Expected behaviour

In my app, i am transferring almost 20 Mb of data from my master to client. i want to speed up the data transfer by setting the connection interval priority to high. Is it possible configure the connection interval parameter of Bluetooth GATT. If not possible, can i get to know, what is the option by default set our react native packager?

### Actual behaviour

Would like to set to the connection interval of Bluetooth GATT.

### Steps to reproduce
NA
1.
2.
3.

### Stack trace and console log

Hint: NA

**Comment by marcosinigaglia** [comment]
Hi, is not possible to set the connection interval in this library, is only possible on Android with API > 21.
