### ISSUE TITLE
illegal callback error

### ISSUE THREAD

**Issue by Tekumalla** [innoveit/react-native-ble-manager#239]
### Version

Tell us which versions you are using:

- react-native-ble-manager v^5.0.3
- react-native v0.44.0
-Android v6.0
- iOS 10+

### Expected behaviour

We should be able to connect to multiple headsets without callback errors.

### Actual behaviour

In our application we connected with one headset and given it a name. Later when connecting to another headset we got the callback error. In this process we were resetting the stack navigator and the componentWill mount function has the code that connects to the device to read the data. 
![img_0263](https://user-images.githubusercontent.com/33369371/32404185-085f284a-c171-11e7-92fc-5d5163e182ca.PNG)
![img_0263](https://user-images.githubusercontent.com/33369371/32404188-1b906f00-c171-11e7-92f5-631a298db9e8.PNG)
![androiderror](https://user-images.githubusercontent.com/33369371/32404207-71aec83c-c171-11e7-8f6e-263af9709ec3.png)```

**Comment by marcosinigaglia** [comment]
Hi, I think you are calling the connection method multiple time without waiting the response.

**Comment by Tekumalla** [comment]
Hello,

Is it possible to fix it from the BLE Manager library? I see a issue with the react-native navigation which is trying to bring up all the views when it is reset.
Due to the dispatch reset event, all views componentWillMount() function of the navigation stack views is getting triggered. We have the device connection in the componentwillmount() which is leading to multiple connections.


With Regards,
Sai

**Comment by marcosinigaglia** [comment]
No, you have to handle this things in your app.
