### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): "Peripheral not found or not connected"

### ISSUE THREAD

**Issue by kf729ik** [innoveit/react-native-ble-manager#243]
### Version

Tell us which versions you are using:

- react-native-ble-manager: "react-native-ble-manager": "^6.1.1",
- "react-native": "0.48.3",
- iOS/
Hi all,
### Expected behaviour

I would like to scan, connect, disconnect to a bluetooth device for x times.

### Actual behaviour

Sometime if I repeat the above mentioned process it crash with: 
Possible Unhandled Promise Rejection (id: 0): "Peripheral not found or not connected"

### Steps to reproduce

1. Scan for device and connect, rerouting to an another view
2. Receiving datas, process them; disconnect from the device after specific time e.g after 10s of live data OR disconnecting by pressing the back navigation button
3. After I pressed the back button (it reroutes me to the previous screen, where I can connect to the device)
4. Pressing scan, connect
5. Sometimes it works 4,5,6 times without problem, sometimes it crash on the 2nd attempt.

### Stack trace and console log
In my log everything seems to be ok, every time when I scan it's searching for the device > I get a list of Devices (where I only have 1 specific what I'm working with), if I press the connect button the log updates that I connected or disconnected (if I press disconnect). 

This process repeat all the time, also if the app crash, but in that case after connecting to the device I got that message in yellow messagebox in the bottom of the phone screen. After that it's dead, it's not opening the new screen and also do not receive any information from the device.

Thanks for any help,
I really appreciate it :)

**Comment by robseaman** [comment]
I'm seeing the same issue with IOS with react-native 51 and react-native-ble-manager 6.2.4. My failure rate is higher on reconnects but the sequence is the same.

**Comment by kf729ik** [comment]
@robseaman  try to call the BleManager.start() method only once, if you place it to the BleManager class it will call every time when this class is called and that's why it crashes in the app.

**Comment by robseaman** [comment]
Thank you @kf729ik for the response. That is exactly what I was doing, calling BleManager.start() each time my component was mounted.

**Comment by Poukai** [comment]
@robseaman Do you have a sample code that i can look at ?

**Comment by soadtech** [comment]
I have the same problem, I see that they only close the issues but there is no response
