### ISSUE TITLE
pairing and auto connect to paired devices [Question]

### ISSUE THREAD

**Issue by himelbrand** [innoveit/react-native-ble-manager#246]
### Version

Tell us which versions you are using:

- react-native-ble-manager v^6.2.4
- react-native v0.50.3
- iOS 10 and above
-Android sdk23

##Help
I couldn't find any information in the docs about this, 
I would like to use my RN app to connect to BLE peripheral and pair with it (both on IOS and Android) so every time this peripheral is in range and available to pair my app will connect to it,
just like the way your computer knows your BL speaker , your car speaker and your phone etc.

Is there a way to do it? if so then how?
 I saw the restoreIdentifierKey and forceLegacy options that I didn't understand, but suspects they are related to the issue, but again no info about what they do in the docs or how to use the IOS one.

thanks

**Comment by marcosinigaglia** [comment]
Hi, [here](https://stackoverflow.com/questions/25254932/can-you-pair-a-bluetooth-le-device-in-an-ios-app) I think you find the answer.
