### ISSUE TITLE
Support BLE in the browser

### ISSUE THREAD

**Issue by circuitry2** [innoveit/react-native-ble-manager#251]
It would be great to have BLE support in the browser as well, using Bluetooth Web API

**Comment by marcosinigaglia** [comment]
If you use the Bluetooth Web API you don't need a module.

**Comment by circuitry2** [comment]
@marcosinigaglia the Bluetooth Web API is not supported in webviews, so this will not work without a module.

**Comment by marcosinigaglia** [comment]
I don't get you point, why is better to use a fake Bluetooth Web API instead the module directly?

**Comment by marcosinigaglia** [comment]
Hi @circuitry2 , only chrome support BLE on the browser in experimental way so i don't get you point.

**Comment by IjzerenHein** [comment]
It would be useful though to have the web-bluetooth API available on react-native, so we can write cross platform code that will work on the browser as well
