### ISSUE TITLE
BleManagerDidUpdateValueForCharacteristic event is not triggering after "Start Notification" fun

### ISSUE THREAD

**Issue by ManiSol9** [innoveit/react-native-ble-manager#256]
### Version

Tell us which versions you are using:

- react-native-ble-manager v?.?.?^6.2.4
- react-native v?.?^0.48.0
- iOS/Android v.?Android

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1. Scan and Connect
2. Start Notification
3. BleManagerDidUpdateValueForCharacteristic event

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

I am Using BLE watch and their native android code. It producing the values when we running in native android app, but when we are react native it's connecting , showing start notification log but it's not triggaring the data but when we run the  native app in forground here the react native app also showing the data.

Can you any one help on this thing ?

**Comment by marcosinigaglia** [comment]
Hi, are you sure that the device is sending something?
