### ISSUE TITLE
"BleManagerStopScan" and "BleManagerDiscoverPeripheral"

### ISSUE THREAD

**Issue by peiyc** [innoveit/react-native-ble-manager#258]
"dependencies": {
		"buffer": "^5.0.8",
		"iconv-lite": "^0.4.19",
		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-ble-manager": "^6.2.4",
		"react-native-storage": "^0.2.2",
		"react-redux": "^5.0.6",
		"redux": "^3.7.2",
		"redux-thunk": "^2.2.0",
		"stream": "0.0.2"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0",
		"redux-devtools": "^3.4.1",
		"redux-logger": "^3.0.6"
	}

I run it on Android.
I listened "BleManagerStopScan" and "BleManagerDiscoverPeripheral" , but it trigged "BleManagerStopScan" first before "BleManagerDiscoverPeripheral"  when I start scan, and it Re trigged "BleManagerStopScan" when scanning for peripherals is ended.

An other question is I found is after it connected bluetooth device,  I turn off the bluetooth, then I turn on the bluetooth it can not trigger "BleManagerDiscoverPeripheral"  until it trigged "BleManagerStopScan" I can not found buletooth device.

**Comment by marcosinigaglia** [comment]
Sorry, I don't understand the problem. Do the BleManagerDiscoverPeripheral triggered always after the BleManagerDiscoverPeripheral?

**Comment by peiyc** [comment]
@marcosinigaglia I`m sorry, my English is soso.

Look at this:

I connected the device.It`s no problem.
![634ee9d5-c3c5-44ac-a402-7ba69a8c40eb](https://user-images.githubusercontent.com/15152562/34371363-7d2a53d8-eb07-11e7-9ed9-10b4771b0de8.png)

After connected  I turn off the bluetooth, and disconnect the device.
![6cffe391-5acd-4c62-a24b-03c798a86d34](https://user-images.githubusercontent.com/15152562/34371390-b1583dbe-eb07-11e7-9c9d-e714bf3124f0.png)

Then I turn on the bluetooth, I can not find the bluetooth.
![4e251ba7-cbac-420b-aa12-61a698f8fa3c](https://user-images.githubusercontent.com/15152562/34371434-104490ac-eb08-11e7-8e1f-d793404a533a.png)

**Comment by marcosinigaglia** [comment]
If you turn off the bluetooth is strange that you don't find the peripheral, I have to test on Android.

**Comment by peiyc** [comment]
After I turn off the bluetooth, I turn on and scan again, but I can`t find the peripheral.
