### ISSUE TITLE
warning on ios

### ISSUE THREAD

**Issue by MonkeyInWind** [innoveit/react-native-ble-manager#262]
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-ble-manager": "^6.2.4"

I run it on ios.
![12fbb711-bf1e-43c3-b31a-aa57b83e4ebb](https://user-images.githubusercontent.com/34543887/34637237-9913ce8e-f2ec-11e7-9021-dae47109315e.png)

**Comment by marcosinigaglia** [comment]
Will be fix in the next release.
