### ISSUE TITLE
IOS notification error

### ISSUE THREAD

**Issue by zjsczzt** [innoveit/react-native-ble-manager#265]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.4
- react-native v0.44.3
- iOS/Android v.ios

### Expected behaviour

android and ios can communicate with ble

### Actual behaviour
only android can communicate with ble 

run in android can open this notification, but run in ios can't open this notification.
ffe0 and ffe4 is my chose nofity.in android this can be open ,but in ios it't not working.

### Steps to reproduce

1.
2.
3.

### Stack trace and console log
nofityServiceUUID 0000FFE0-0000-1000-8000-00805F9B34FB nofityCharacteristicUUID 0000FFE4-0000-1000-8000-00805F9B34FB
BleModule.js:248 Notification error: Could not find service with UUID 0000FFE0-0000-1000-8000-00805F9B34FB on peripheral with UUID B71449BD-4F8E-A526-4381-C410A3F9E198

```
```

**Comment by marcosinigaglia** [comment]
Try with an app like LightBlue if the notification is working.

**Comment by zjsczzt** [comment]
LightBlue can working. but in react-native app  ,the same of notification can't working

**Comment by marcosinigaglia** [comment]
Try to add a delay after the `retrieveServices` call.

**Comment by thomastao0215** [comment]
I have the same issue.Plz give the solution

**Comment by melkayam92** [comment]
I also had problems with notification on iOS. 

On different versions for iOS it's worked differently.. but in the end, the hardware needed to implement a descriptor notification in order to make it work. so I'm not sure it's a problem of the library.

Also, try to turn off and on the Bluetooth - that will clean the cache.

**Comment by nagaokashi** [comment]
I got the solution.
Use short id 'FFE1' instead of '0000FFE1-0000-1000-8000-00805F9B34FB';

**Comment by nikoWah** [comment]
@nagaokashi Thanks, you're a life saver. Was facing the same problem. :)
