### ISSUE TITLE
Each device's peripheralId is the only one?

### ISSUE THREAD

**Issue by longmingfeng** [innoveit/react-native-ble-manager#272]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.6
- react-native v0.44.3
- iOS/Android 10.3.3/7.0

1，Each device's peripheralId is the only one?
2，Why not add reactMixin (App) prototype, TimerMixin) this line, will not be able to receive the data?

**Comment by marcosinigaglia** [comment]
English please.

**Comment by stanleywijoyo** [comment]
Not sure if this is the same issue, but after compiling the example code on my android phone, I could only see the peripheral IDs. All the peripheral names are null.

**Version**

- react-native-ble-manager v6.2.6
- react-native v0.50.3
- Android 7.1.1

**Comment by marcosinigaglia** [comment]
@longmingfeng 
1) Yes but the ids are different in iOS and Android
2) I think you made other error in the changes.
