### ISSUE TITLE
RN error when disconnecting from BLE after readRSSI

### ISSUE THREAD

**Issue by jimji1005** [innoveit/react-native-ble-manager#274]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.4
- react-native v 51
- iOS/Android v.ios 10

### Expected behaviour

Tell us what should happen
BleManager.disconnect(bleID) should disconnect device properly

### Actual behaviour

Tell us what happens instead
Device is disconnected and error is thrown on RN

"Illegal callback invocation from native module. This callback type only permits a single invocation from native code."

### Steps to reproduce

1. connect to ble device
2. readrssi
3. disconnect ble device

### Stack trace and console log

Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
reactConsoleErrorHandler @ index.bundle:7010
console.error @ index.bundle:44646
logToConsole @ index.bundle:14848
logIfNoNativeHook @ index.bundle:14831
__callFunction @ index.bundle:2100
(anonymous) @ index.bundle:1929
__guard @ index.bundle:2071
callFunctionReturnFlushedQueue @ index.bundle:1928
(anonymous) @ debuggerWorker.js:72
14:58:54.278 

<img width="320" alt="screenshot" src="https://user-images.githubusercontent.com/5834998/35249315-5fb736c0-ff86-11e7-8740-8cc4c16e9781.png">

**Comment by jimji1005** [comment]
if i don't readrssi after connection, disconnect works without error. issue ONLY happens after i readrssi then disconnect.

FYI disconnect is put on a timer of 5seconds to avoid unfinished write commands, still no dice.

**Comment by jimji1005** [comment]
Steps to replicate 

1. scan for BLE
2. connect to BLE
3. get rssi
4. disconnect
=> error.


1. scan for BLE
2. connect to BLE
3. disconnect
=> no error.

**Comment by jimji1005** [comment]
#239

**Comment by timsatterfield** [comment]
+1
