### ISSUE TITLE
Get bonded devices and start notification on iOS issues

### ISSUE THREAD

**Issue by ducNgbk** [innoveit/react-native-ble-manager#275]
Hello, I'm developing app which uses secure connection
There are some missing features that I'm wondering if it's possible to add on iOS
- get boned device list
- start notification return specific error if bond is needed

Thank you, guys, for your awesome work

**Comment by marcosinigaglia** [comment]
Hi, I don't have a device to use to develope this things so a PR is welcome.

**Comment by whitedogg13** [comment]
Hi, as far as I know iOS doesn't expose any public API to get bonded devices, you can see discussions like [this SO link](https://stackoverflow.com/questions/48361435/ios-previously-bonded-ble-devices?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). So currently it's not possible to support this feature.

PS: I have committed the Android `getBondedPeripherals` for this library, and also searching solutions for iOS but sadly cannot find one~
