### ISSUE TITLE
Can't disconnect from device, isPeripheralConnected returning correct value

### ISSUE THREAD

**Issue by nivnahmias** [innoveit/react-native-ble-manager#276]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.6
- react-native v0.49.3
- Android v.?

After scanning for devices, i'm able to connect to my QC35 headphones.
Calling isPeripheralConnected('xxx',[]) returns false.
Calling getConnectedPeripherals([]) returns the headphones and i can't seem to remove them.

Am i using this library incorrectly?

**Comment by marcosinigaglia** [comment]
Hi, I think isPeripheralConnected need some fix. I don't understand the second problem, are you not able to disconnect?

**Comment by nivnahmias** [comment]
Yeah, calling "removePeripheral" returns a rejected promise and the device just stays connected.

**Comment by marcosinigaglia** [comment]
You have to use the `disconnect` method.

**Comment by nivnahmias** [comment]
i'm sorry i meant calling `disconnect`.
after calling `disconnect`, calling `getConnectedPeripherals` still returns my headphones.
only after manually turning off my headphones or disconnecting them through the bluetooth settings i get the correct answer from `getConnectedPeripherals`.

**Comment by vpfaulkner** [comment]
I think I'm running into this issue as well @marcosinigaglia. After shutting down the process acting as the peripheral, if I call `isPeripheralConnected` then `true` is still returned. Also the `BleManagerDisconnectPeripheral` did not get triggered. Am I missing something?

**Comment by diablourbano** [comment]
Same error, I'm even calling `removePeripheral` (I'm using an android device) and if I run `getConnectedPeripherals` I'll get the device, and I'll get `true` if I run `isPeripheralConnected`.

**Comment by NN01010101** [comment]
Can confirm exact same issue!

**Comment by yoshimoto8** [comment]
Same error.  it is not correct value when i call `isPeripheralConnected` before `disconnected`
