### ISSUE TITLE
The example folder doesn't exist

### ISSUE THREAD

**Issue by NaseebullahSafi** [innoveit/react-native-ble-manager#277]
I've followed the step and did the following:

```js
import App from 'react-native-ble-manager/example/App'
```
and it says the example folder doesn't exist. I went to the node modules and checked, only to find that the example folder doesn't exist.

**Comment by marcosinigaglia** [comment]
Hi @NaseebullahSafi , you are right, in the npm the example folder is filtered, you have to clone the project to use the example code.

**Comment by NaseebullahSafi** [comment]
Brilliant thanks, will do that now @marcosinigaglia
