### ISSUE TITLE
Stupid question, if connected can we transmit data from peripheral to the app?

### ISSUE THREAD

**Issue by NaseebullahSafi** [innoveit/react-native-ble-manager#278]
Currently, I have [`OpenBCI`](https://shop.openbci.com/collections/frontpage/products/cyton-biosensing-board-8-channel) microcontroller with BLE. If I was to connect with the microcontroller, will I be able to pass/transmit data from the microcontroller to the app?

**Comment by marcosinigaglia** [comment]
Yes, for example in my project I write and I receive data from the same characteristic using the notification.

**Comment by NaseebullahSafi** [comment]
Thank you :)
