### ISSUE TITLE
What is the reason for using setTimeout in examples?

### ISSUE THREAD

**Issue by sowdri** [innoveit/react-native-ble-manager#286]
In the example project setTimeout has been used in between api calls, but the reason/rational behind it has not been documented. I'm using this library and not quite sure

- when to use setTimeout
- If yes, what should be the delays between specific operations

Thanks in advance,

**Comment by marcosinigaglia** [comment]
Hi, some device need some delay after an operation so you have to test if you need this. The ble stack is awful in ios and android.
