### ISSUE TITLE
I can find only MacBook

### ISSUE THREAD

**Issue by vladinko0** [innoveit/react-native-ble-manager#287]
### Version

- react-native-ble-manager v 6.2.6
- react-native v 0.53
- Android v. 7.0

### Expected behaviour

I would like to find by scanning all available devices: iPhone, Desktop, other Android, Medical device, MacBook.

### Actual behaviour

I can find only MacBook.

### Steps to reproduce

1. Using Example from react-native-ble-manager/example/App.js
2. Turning On Bluetooth on all devices.
3. Tapping 'Scan Bluetooth' button in application.

**Comment by marcosinigaglia** [comment]
You see only the visible bluetooth LE devices.

**Comment by vladinko0** [comment]
Is it a big problem to implement classic bluetooth devices?

**Comment by marcosinigaglia** [comment]
It's a different thing, search for others libraries.
