### ISSUE TITLE
Broken Offset when writing more then 20 bytes

### ISSUE THREAD

**Issue by lukabers** [innoveit/react-native-ble-manager#29]
Hello,
while writing more then 20 bytes the plugin splits data correctly but it doesn't send the correct offset to the reader.
Any solution?

Thanks

**Comment by marcosinigaglia** [comment]
Hi, can you explain better your problem?

**Comment by lukabers** [comment]
Hi,
We are sending a message of 200 bytes to the reader. This last one, a bleno server, receives always offset:0  during the write request.

Thanks

**Comment by marcosinigaglia** [comment]
Hi, I'm not an expert on BLE but from what I read you have to handle manually the queue in the server to join the splitted message, there isn't the "stream" concept.

**Comment by lukabers** [comment]
Thanks! we managed this manually with the server!
