### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException: bridge is not set. This is probably because you've explicitly synthesized the bridge in BleManager, even though it's inherited from RCTEventEmitter.

### ISSUE THREAD

**Issue by etayluz** [innoveit/react-native-ble-manager#294]
### Version

Tell us which versions you are using:

- react-native-ble-manager: 6.2.6
- react-native v?.? 0.51.0
- iOS/Android v.? iOS

### Expected behaviour

App should NOT crash when pressing Scan Bluetooth

### Actual behaviour

Once in a while (NOT deterministic) the app crashes

### Steps to reproduce

Not easily reproducible

### Stack trace and console log

Fatal Exception: NSInternalInconsistencyExceptionbridge is not set. This is probably because you've explicitly synthesized the bridge in BleManager, even though it's inherited from RCTEventEmitter. Raw Text
--
0 | CoreFoundation | (Missing)
3 | Foundation | (Missing)
4 | project | RCTEventEmitter.m line 40-[RCTEventEmitter sendEventWithName:body:]
5 | project | BleManager.m line 317-[BleManager stopScanTimer:]
6 | Foundation | (Missing)
13 | UIKit | (Missing)
14 | project | main.m line 16main
15 | libdyld.dylib | (Missing)
16 | (Missing) | (Missing)

<img width="921" alt="trace" src="https://user-images.githubusercontent.com/1825834/36756718-d7bde8d0-1bdd-11e8-8f39-3ad125b64f02.png">

**Comment by marcosinigaglia** [comment]
Hi, try te latest release.
