### ISSUE TITLE
How to send hex code

### ISSUE THREAD

**Issue by ilyakar** [innoveit/react-native-ble-manager#299]
How do I send the following hex code "0x14" to the device?
Is using stringToBytes("0x14") the right way of converting the hex to binary so that I can then send it?

**Comment by marcosinigaglia** [comment]
Hi, send [0x14] .

**Comment by ilyakar** [comment]
So to clarify, this would work?
```
BleManager.writeWithoutResponse(x, y, z, [0x14])
```

**Comment by marcosinigaglia** [comment]
Yep.

**Comment by ilyakar** [comment]
It worked! Thanks a lot.

Kind regards,
Ilya
