### ISSUE TITLE
write

### ISSUE THREAD

**Issue by yedeba** [innoveit/react-native-ble-manager#3]
Hello, I need to write a byte 01 in characteristic, but can not,
You could put me an example.
Thank you!!

**Comment by marcosinigaglia** [comment]
You need a base64 converter like **base64-js** to convert your bytes:
```
var base64 = require('base64-js');
var data = base64.fromByteArray([1]);
BleManager.write(peripheralId, serviceUUID, characteristicUUID, data);
```

**Comment by yedeba** [comment]
Thanks, work perfect!!
