### ISSUE TITLE
Checking connection state?

### ISSUE THREAD

**Issue by joshreeves** [innoveit/react-native-ble-manager#30]
Love this library, but is there no way to check the connection status of a peripheral? Without that capability it is difficult to manage the connection state between the app and the pairing of devices in iOS system settings. Thanks in advance.

**Comment by marcosinigaglia** [comment]
I thins this pull https://github.com/innoveit/react-native-ble-manager/pull/33 solve your problem.

**Comment by joshreeves** [comment]
Awesome!
