### ISSUE TITLE
Some mobiles wont find the Ble device

### ISSUE THREAD

**Issue by gkothe** [innoveit/react-native-ble-manager#300]
- react-native-ble-manager v6.2.8
- react-native v0.54.0
- iOS/Android v.7.1.1

I made a blank app with the latest versions of everything , it opens a blank screen and start scanning, when it finds, its prints on console.
So, there are two mobiles that I tested that did not find the expected device. But did find other(s) device
The mobiles are: lg-v500 ,  Moto G5S plus
![pic2](https://user-images.githubusercontent.com/11322245/37228599-f59360e4-23bf-11e8-8077-4d758d362b57.png)

I also downloaded the "ble scanner" from google play to see if it was a hardware problem, but its not.
That app found the device in question (kafer)

![screenshot_20180309-173401](https://user-images.githubusercontent.com/11322245/37228736-5cbb99e4-23c0-11e8-9bea-af7fbaf853a9.png)

Is that peripheral mode relevant to something? 

In others mobiles it worked well (tested around 5 different android cellphones ).

Any Ideias?

Thanks.

**Comment by gkothe** [comment]
Update: If i have both apps running at the same time, The device is found. (ble scanner and my app)

**Comment by marcosinigaglia** [comment]
Hi, do you use the forceLegacy flag?

**Comment by gkothe** [comment]
Not using (false), since I was not sure what was that about. Going to try with "true".

**Comment by nomoreboredom** [comment]
I was having the same issue as @gkothe, and using forceLegacy flag solved the discovery for me.
