### ISSUE TITLE
Not found android device.

### ISSUE THREAD

**Issue by engelsizmuzik** [innoveit/react-native-ble-manager#310]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.9
- react-native v0.55.1
- Android SM-J106H - 6.0.1' real device

-----------------------------------
Not found android device.
How to scan android phone and connect device?

**Comment by engelsizmuzik** [comment]
Not found  phone devices  but   I can contact the device id. 
I can not read some values ​​after linking  these values ​​are serviceUUID and characteristicuuıd

**Comment by marcosinigaglia** [comment]
Hi, you can connnect only to ble devices.
