### ISSUE TITLE
not found  android phone Characteristic

### ISSUE THREAD

**Issue by engelsizmuzik** [innoveit/react-native-ble-manager#312]
StartNotificationClick

```
 BleManager.startNotification(deviceid, '2a05', '1801')
        .then(() => {
            // Success code
            console.log('Notification started');
        })
        .catch((error) => {
            // Failure code
            console.log(error);
        });
        BleManager.stopNotification(deviceid, '2a05', '1801')
        .then(() => {
            // Success code
            console.log('Notification started');
        })
        .catch((error) => {
            // Failure code
            console.log(error);
        });
```

>  "dependencies": {
>     "react": "16.3.1",
>     "react-native": "0.55.1",
>     "react-native-ble-manager": "^6.2.9",
>     
>   },

> peripheralInfo button click
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS: { characteristics:
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:    [ { properties: { Indicate: 'Indicate' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        characteristic: '2a05',
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        service: '1801' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:      { properties: { Read: 'Read' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        characteristic: '2a00',
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        service: '1800' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:      { properties: { Read: 'Read' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        characteristic: '2a01',
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        service: '1800' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:      { properties: { Read: 'Read' },
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        characteristic: '2aa6',
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:        service: '1800' } ],
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:   services: [ { uuid: '1801' }, { uuid: '1800' } ],
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:   id: 'F8:8C:9D:3D:8D:47',
> 04-12 11:13:13.084 13886 16352 I ReactNativeJS:   name: 'General' }
> 04-12 11:13:16.267 13886 16352 I ReactNativeJS: startNotification button click
> 04-12 11:13:16.277 13886 16352 I ReactNativeJS: Characteristic 00001801-0000-1000-8000-00805f9b34fb not found
> 04-12 11:13:16.287 13886 16352 I ReactNativeJS: Characteristic 00001801-0000-1000-8000-00805f9b34fb not found

**Comment by marcosinigaglia** [comment]
Hi @engelsizmuzik , I don't get your question.
