### ISSUE TITLE
Support for Bluetooth 5.0

### ISSUE THREAD

**Issue by darshanrn** [innoveit/react-native-ble-manager#314]
- react-native-ble-manager v6.2.9
- iOS v.10

Expected behaviour: react-native-ble-manager should support Bluetooth 5.0 on iPhone

Actual behaviour: My question is does react-native-ble-manager actually support Bluetooth 5.0?

If my peripheral still runs Bluetooth 4.2 and the device to connect runs 5.0, does react-native-ble-manager still work?

**Comment by whitedogg13** [comment]
Hi, BLE 5.0 is **backward compatible** with previous bluetooth versions, including 4.2. So in your case, it will still work and result in running BLE at version 4.2.

Thanks!
