### ISSUE TITLE
Issue running with react-native-navigation

### ISSUE THREAD

**Issue by snowdall** [innoveit/react-native-ble-manager#317]
- react-native-ble-manager v6.2.9
- react-native 0.54.4
- Android 8.0.0

I am somewhat new to react-native so be kind.

I was able to get the react-native-ble-manager example working on my local hardware with relatively few issues.  From there I wanted to integrate this into my current app; I of course used the example application as a template to accomplish this.

What I noticed is that on Android the BleManager.start({showAlert: false}); would result in:

`TypeError: Cannot read property 'start' of undefined`

Even though it was specifically imported at the top of the view.  I also noticed that when I would console log NativeModules, BleManager was not one of the modules that was included in the list.  Note these issues do not occur when running iOS (in emulation granted).

When exploring a bit deeper the main difference between the example app and my app is I'm using react-native-navigation by Wix (https://wix.github.io/react-native-navigation/#/).  I'm using this so I can have a login screen that then navigates to a tabbed application.

This requires MainApplication to extend a different class:

`package com.macaw;

import android.app.Application;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.reactnativenavigation.NavigationApplication;
import it.innove.BleManagerPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new BleManagerPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

  @Override
  public boolean isDebug(){
    return BuildConfig.DEBUG;
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages(){
    return null;
  }
}
`

I'm wondering if this could perhaps be causing the issue when running on Android.  Are these two npm mutually exclusive?  Is there a way to get them to play nicely together?  Thoughts?

Thanks,
Clark

**Comment by marcosinigaglia** [comment]
Hi, I think you only miss something in the installation, try again.
