### ISSUE TITLE
startNotification does not called

### ISSUE THREAD

**Issue by mikeex5** [innoveit/react-native-ble-manager#325]
- react-native-ble-manager v6.2.9
- react-native v0.55.2
- iOS/Android v4.4

I have problem with older Android devices. On Android 7.1 everything works fine, but on devices under version 6 startNotification() method is not called.

` BleManager.connect(peripheral.id).then(() => {`
  `  console.log('Connected');`
     ` BleManager.retrieveServices(peripheral.id).then((device) => {`
      ` console.log(device);`
       ` BleManager.startNotification(device.id, device.characteristics[5].service,`   `device.characteristics[5].characteristic).then((res) => { `
`// Success code`
   ` console.log('Notification started');`       
  ` })`
    `.catch((error) => {`
    `// Failure code`
    `console.log(error);`
  `})`
  ` .catch((e) => console.log(e));`
`})`
`.catch((e) => console.log(e));`

 In console log I don't see either the successful or the failed log. But it successful connect and retrieve services.

**Comment by alexbidiuk** [comment]
Subscribe

**Comment by marcosinigaglia** [comment]
Hi, I saw that in some devices you don't have the feedback from the notification so the startNotification promise doesn't work but the BleManagerDidUpdateValueForCharacteristic event works.

**Comment by gregogalante** [comment]
Get same problems.

**Comment by kgaspar** [comment]
Hi did you guys managed to find a solution for this?
Got the same problem on android 5.1.1.

startNotification starts, but you don't get feedback about it every time, but the "BleManagerDidUpdateValueForCharacteristic" gets triggered. 

I observed the logcat on android and  the "setNotifyComplete()" logs get called, but the callback just doesn't fire up.

Tried on a 6.0 android and works fine. For some reason the callback doesn't fire.

**Comment by gregogalante** [comment]
@kgaspar Yes, i don't know why but with an update of the minSdkVersion the application stops to request the  ACCESS_COARSE_LOCATION permission to the user.

I have forced it on application startup

```javascript
if (Platform.OS === 'android') {
      PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION).then((result) => {
        if (!result) {
          PermissionsAndroid.requestPermission(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION).then((result) => {
            if (!result) {
              alert("The application can not work property without the requested permissions.")
            }
          })
        }
      })
    }
```

**Comment by kgaspar** [comment]
@gregogalante 

Yeah they introduced that in Android 6.0. to protect the users privacy. As stated in [Android Developer](https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-hardware-id)

To scan the user needs to allow coarse location services.

But I think startNotification is not related to this. Since this is an 5.0 Android issue, and is related to not getting a notification started callback.
