### ISSUE TITLE
Is it possible to modify the showAlert toast?

### ISSUE THREAD

**Issue by zhan4139** [innoveit/react-native-ble-manager#329]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.3.0
- react-native v0.53
- iOS v11.3?

### Expected behaviour

Is it possible to change the showAlert "OK" button to be "Cancel" because in iOS toast, I thought click ok just turn on the bluetooth but actually not. It will make more sense if it is a "cancel".

### Actual behaviour

Current there are two buttons in the alert, one is "settings" which redirects to the iOS setting menu.
The other one is "ok"

**Comment by marcosinigaglia** [comment]
Hi, it's a system alert so you can't change the text.
