### ISSUE TITLE
Android 4.4.4 application crashing during connecting

### ISSUE THREAD

**Issue by westcode** [innoveit/react-native-ble-manager#343]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.3.3
- react-native v0.55.3
- iOS/Android v: Android 4.4.4 (Samsung Galaxy Ace 4)

### Expected behaviour

Bluetooth device connection should be setup after calling BleManager.connect

### Actual behaviour

Application crashes because the gatt in the onConnectionStateChange Run method is null the first time.

### Steps to reproduce

1. Connect to a device

### Stack trace and console log

The following stacktrace is available from logcat:

06-21 10:57:51.697 9043-9080/nl.appid D/ReactNative:  Catch to call normal connection
06-21 10:57:51.707 9043-9080/nl.appid D/BluetoothGatt: connect() - device: FE:10:D2:0F:0D:38, auto: false
    registerApp()
06-21 10:57:51.717 9043-9080/nl.appid D/BluetoothGatt: registerApp() - UUID=25835378-f0e5-4804-ad9a-6f16f539f9cf
06-21 10:57:51.717 9043-9080/nl.appid I/BluetoothGatt: Client registered, waiting for callback
06-21 10:57:51.717 9043-9065/nl.appid D/BluetoothGatt: onClientRegistered() - status=0 clientIf=7
06-21 10:57:51.717 9043-9080/nl.appid D/ReactNativeBleManager: onConnectionStateChange to 2 on peripheral: FE:10:D2:0F:0D:38 with status0
06-21 10:57:51.717 9043-9043/nl.appid D/AndroidRuntime: Shutting down VM
06-21 10:57:51.717 9043-9043/nl.appid W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x416f6d58)
06-21 10:57:51.727 9043-9080/nl.appid D/ReactNativeBleManager: Peripheral event (BleManagerConnectPeripheral):FE:10:D2:0F:0D:38
    Connected to: FE:10:D2:0F:0D:38
06-21 10:57:51.857 9043-9043/nl.appid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.appid PID: 9043
    java.lang.NullPointerException
        at it.innove.Peripheral$1.run(Peripheral.java:301)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5426)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
06-21 10:57:51.867 9043-9055/nl.appid D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=7 device=FE:10:D2:0F:0D:38
06-21 10:57:51.867 9043-9055/nl.appid D/ReactNativeBleManager: onConnectionStateChange to 2 on peripheral: FE:10:D2:0F:0D:38 with status0
06-21 10:57:51.877 9043-9055/nl.appid D/ReactNativeBleManager: Peripheral event (BleManagerConnectPeripheral):FE:10:D2:0F:0D:38

Ive fixed this by adding a null check on the gatt (line 301: Peripheral.java) after that everything seems to work fine.

**Comment by marcosinigaglia** [comment]
Hi, can you make a PR? Thanks.
