### ISSUE TITLE
Can't build app on Android after updating RN to 0.56

### ISSUE THREAD

**Issue by anton-loktev** [innoveit/react-native-ble-manager#347]
### Version

- react-native-ble-manager v.6.3.3
- react-native v.0.56.0

After updating React-Native i have error with Android build
"The SDK Build Tools revision (24.0.2) is too low for project ':react-native-ble-manager'. Minimum required is 25.0.0"

Please update the version of SDK Build Tools in build.gradle

**Comment by VitamineC** [comment]
+1

**Comment by marcosinigaglia** [comment]
Try v.6.4.0

**Comment by anton-loktev** [comment]
It works. Thanks a lot!
