### ISSUE TITLE
Is it possible to pair ble device programmatically without the user entering pin??(QUESTION)

### ISSUE THREAD

**Issue by Hyeongwon** [innoveit/react-native-ble-manager#354]
Hi, Guys

my goal is for the app to automatically input the password when pairing with the bluetooth device without asking user to input the PIN.

Thanks!

**Comment by wesdewitte** [comment]
@Hyeongwon Did you fix it? How did you do it then?

**Comment by Hyeongwon** [comment]
> @Hyeongwon Did you fix it? How did you do it then?

no I didn't

**Comment by helloyan** [comment]
any update?

**Comment by erdouzun** [comment]
Hello,

Is there any update for this capability?

**Comment by mazenchami** [comment]
any update on this?

**Comment by marcosinigaglia** [comment]
Is possible but I don't have a device to test, a PR is welcome.

https://stackoverflow.com/questions/35519321/android-bluetooth-pairing-without-user-enter-pin-and-confirmation-using-android

**Comment by siddaiahm** [comment]
Hey, I have made a PR for this changes, I tested and it is working in android

**Comment by maartenvandillen** [comment]
@siddaiahm this used to work perfectly for me, but not anymore. I'm not sure if the update of the firmware is the cause or maybe an update of my phone (Samsung). Is it still working for you?

**Comment by siddaiahm** [comment]
> @siddaiahm this used to work perfectly for me, but not anymore. I'm not sure if the update of the firmware is the cause or maybe an update of my phone (Samsung). Is it still working for you?

Yes still working as expected for me (v7.4.2).  I did not check in the other updated versions.
