### ISSUE TITLE
iOS devices not receiving data / notification not firing

### ISSUE THREAD

**Issue by VanessaI** [innoveit/react-native-ble-manager#355]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.2.9
- react-native v0.55.3
- iOS/Android v.?

### Expected behaviour

1. iOS connects to device
2. Notification starts
3. iOS receives data (characteristics) from device

### Actual behaviour

**iOS** finds device and connects to it but **notification is not sent** and therefore, it **does not receive any data** from my peripheral device.
Please note that it works perfectly on the Android devices, but not on iOS.

**Comment by marcosinigaglia** [comment]
Hi, did you check the xcode log?

**Comment by tal987** [comment]
@VanessaI can you show me the code how do you search and connect to device?
