### ISSUE TITLE
Set notification failed for XXxxX-XXxxX-XXxXX-xXxxx

### ISSUE THREAD

**Issue by xioayaohou** [innoveit/react-native-ble-manager#357]
when you use      BleManager.startNotification(device.id, this.state.service, this.state.readCharacteristic).then(() => {
                  console.warn('Notification readCharacteristic success')
                })
                .catch((error) => {
                  console.warn("Notification readCharacteristic fail", error)
                });
and then the log is    ''Set notification failed for XXxxX-XXxxX-XXxXX-xXxxx'' ,  why?

**Comment by marcosinigaglia** [comment]
Hi, check the error in the platform log.
