### ISSUE TITLE
Use of undeclared identifier 'RCTBridgeWillReloadNotification' in iOS

### ISSUE THREAD

**Issue by Symous** [innoveit/react-native-ble-manager#362]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.4.0
- react-native v0.45.1
- iOS/Android iOS 11.4

### Expected behaviour

running normally

### Actual behaviour

Xcode give me an error that Use of undeclared identifier 'RCTBridgeWillReloadNotification'

### Reason

the RCTBridge of react-native 0.45.1 do not contains the RCTBridgeWillReloadNotification

**Comment by marcosinigaglia** [comment]
Hi @Symous , your RN version is old, can you try to search for the same problem in other project?

**Comment by Symous** [comment]
@marcosinigaglia , yes, I understand. but the readme said that this lib support RN0.40 or higher which may misleading users like me. :)
