### ISSUE TITLE
the BleManager.startNotification   error   in ios

### ISSUE THREAD

**Issue by yydinfo** [innoveit/react-native-ble-manager#364]
when you use 
 BleManager.startNotification(this.state.id, this.state.uuidData.nofityServiceUUID[0], this.state.uuidData.nofityCharacteristicUUID[0])
            .then(() => {
                console.log('Notification started');
                this._write()
            })
            .catch((error) => {
                console.log('Notification error:',error);
            });

and then the log is '''Could not find service with UUID 0000FFE0-0000-1000-8000-00805F9B34FB on peripheral with UUID 1910A25A-94B4-4F9D-A08E-83DD6EDC55C7''' , why?

**Comment by Rana-Muhammad-Amir** [comment]
Facing same error but in error.....
any help please....

 'Notification error', 'Characteristic 13333333-3333-3333-3333-333333330003 not found'

**Comment by eddroid** [comment]
Did you call `retrieveServices` first?

_Before write, read or start notification you need to call retrieveServices method_
https://github.com/innoveit/react-native-ble-manager#note
