### ISSUE TITLE
Write mehtod returns nothing

### ISSUE THREAD

**Issue by szkkeny** [innoveit/react-native-ble-manager#378]
### Version

- react-native-ble-manager v6.5.0
- react-native v0.56.0
- iOS v.11

### Expected behaviour
We can get the value which is sent by peripheral with Write mehtod.

### Actual behaviour
there is no return value.

**Comment by marcosinigaglia** [comment]
Hi, is not an error, the write method doesn't return value.

**Comment by anwarhamr** [comment]
You will have to read the value after writing it if you need confirmation or set notification on (if possible) on the characteristic.

**Comment by harshit275** [comment]
@anwarhamr Can you please elaborate some more on the read, write and set notification of this library as to how to use them. I am trying to fetch the data from a PID of a BLE using write method of this library but I am getting empty promise object. Don't know what I am doing wrong.
