### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by vpfaulkner** [innoveit/react-native-ble-manager#385]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.1
- react-native v0.55.3
- Android v.19

### Expected behaviour

This crash should not occur

### Actual behaviour

I'm seeing this crash

### Steps to reproduce

Unfortunately I am unable to reproduce, sorry. But, I am pasting all that I see in Bugsnag (our error monitoring service). Let me know if anything comes to mind.

### Stack trace and console log

```
java.lang.NullPointerException
    Peripheral.java:324 it.innove.Peripheral.onConnectionStateChange
    Peripheral.java:121 it.innove.Peripheral.connect
    BleManager.java:228 it.innove.BleManager.connect
    Method.java:-2 java.lang.reflect.Method.invokeNative
    Method.java:515 java.lang.reflect.Method.invoke
    JavaMethodWrapper.java:372 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:160 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:733 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:29 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:136 android.os.Looper.loop
    MessageQueueThreadImpl.java:192 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:841 java.lang.Thread.run
```

Some Events that occurred right before the crash:
![image](https://user-images.githubusercontent.com/6223462/46316188-6d5aba80-c59d-11e8-85fb-802e0b6c3ffc.png)

Everything recorded about the Device:
![image](https://user-images.githubusercontent.com/6223462/46316275-bca0eb00-c59d-11e8-9a48-e0e29898160d.png)

**Comment by marcosinigaglia** [comment]
Hi @vpfaulkner , can you try to debug this error? It's strange because there is a check for null value.
