### ISSUE TITLE
android - Multiple connect events and undesirable manual stateChange invocation

### ISSUE THREAD

**Issue by granttj01** [innoveit/react-native-ble-manager#386]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.1
- react-native v0.56?
- Android v.8?

### Expected behaviour

Tell us what should happen:

Connection events are triggered once the connection has actually completed. See the [android Google source](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/bluetooth/BluetoothGatt.java#835) for explanation.

The resolving of the connect promise, see [ReadMe example](https://github.com/innoveit/react-native-ble-manager#connectperipheralid) should not mean that the peripheral is connected but instead that the process has been successfully initiated. Developers using this package should be advised to use event listeners instead. Maybe a process flow guide of what state each promise resolve/event represents would be useful for contributors and developers (I could help here if you agree?)

### Actual behaviour

Tell us what happens instead:

The onConnectionStateChange is incorrectly called manually [here](https://github.com/innoveit/react-native-ble-manager/blob/34742173695a7f4d2c563b999a69f9fc624d9a13/android/src/main/java/it/innove/Peripheral.java#L121). From the Google source code link above, you can clarify that the connection is not necessarily instant but may take some time. The device connect method returning true does not mean that the device has been connected but that the connection process has been initiated. 
```
The connection may not be established right away, but will be completed when the remote device is available. A {@link BluetoothGattCallback#onConnectionStateChange} callback will be invoked when the connection state changes as a result of this function.
``` 

I think the origin of the misunderstanding may be this [pr](https://github.com/innoveit/react-native-ble-manager/pull/338) and may **possibly**  have since resulted in a few of the issues:

[350](https://github.com/innoveit/react-native-ble-manager/issues/350)
[366](https://github.com/innoveit/react-native-ble-manager/issues/366)
[383](https://github.com/innoveit/react-native-ble-manager/issues/383)
[385](https://github.com/innoveit/react-native-ble-manager/issues/385) <- This issue even has a screenshot of the duplicate connect event.

### Steps to reproduce

1. add listeners/handlers for 'BleManagerConnectPeripheral' and 'BleManagerDisconnectPeripheral' to see events emitting
2. You can discover the device, then connect to see it emit twice (same for disconnect - not sure why just yet)
3. If you were to remove the power supply from the peripheral after discovering and then call connect. You would receive a single 'BleManagerConnectPeripheral' when it should not even be possible.

I am not a Java developer (yet) so further clarification and help to refactor the code for this issue would be much appreciated, hope the above is clear but if anything seems incorrect please let me know.

**Comment by rnevius** [comment]
I can confirm this issue. Here's the Android `Log.d` output when I connect to a peripheral:

```shell
21:03:44.007   D/ReactNativeBleManager: BleManager initialized
21:03:46.076   D/ReactNativeBleManager: checkState
21:03:46.077   D/ReactNativeBleManager: state:on
21:03:46.092   D/ReactNativeBleManager: scan
21:03:46.094   D/ReactNativeBleManager: Filter service: 00001XXX-XX8C-4AB9-BF4C-05590CC2A3F3
21:03:46.095   D/BluetoothAdapter: isLeEnabled(): ON
21:03:46.097   D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=7 mScannerId=0
21:03:48.039   I/ReactNativeBleManager: DiscoverPeripheral: Some Name
21:03:48.062   D/ReactNativeBleManager: Connect to: XX:XX:XX:XX:XX:XX
21:03:48.062   D/ReactNativeBleManager:  Is Or Greater than M $mBluetoothDevice
21:03:48.064   D/BluetoothGatt: connect() - device: XX:XX:XX:XX:XX:XX, auto: false
21:03:48.065   D/BluetoothGatt: registerApp()
21:03:48.065   D/BluetoothGatt: registerApp() - UUID=XXXXXXXX-01ed-4043-adf4-698f7eec3563
21:03:48.069   D/BluetoothGatt: onClientRegistered() - status=0 clientIf=8
21:03:48.070   D/ReactNativeBleManager: onConnectionStateChange to 2 on peripheral: XX:XX:XX:XX:XX:XX with status0
21:03:48.073   D/ReactNativeBleManager: Peripheral event (BleManagerConnectPeripheral):XX:XX:XX:XX:XX:XX
21:03:48.073   D/ReactNativeBleManager: Connected to: XX:XX:XX:XX:XX:XX
21:03:48.074   D/BluetoothGatt: discoverServices() - device: XX:XX:XX:XX:XX:XX
21:03:48.101   D/ReactNativeBleManager: Stop scan
21:03:48.103   D/BluetoothAdapter: isLeEnabled(): ON
21:03:48.125   D/ReactNativeBleManager: Retrieve services from: XX:XX:XX:XX:XX:XX
21:03:48.125   D/BluetoothGatt: discoverServices() - device: XX:XX:XX:XX:XX:XX
21:03:48.463   D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=XX:XX:XX:XX:XX:XX
21:03:48.464   D/ReactNativeBleManager: onConnectionStateChange to 2 on peripheral: XX:XX:XX:XX:XX:XX with status0
21:03:48.465   D/BluetoothGatt: discoverServices() - device: XX:XX:XX:XX:XX:XX
21:03:48.466   D/ReactNativeBleManager: Peripheral event (BleManagerConnectPeripheral):XX:XX:XX:XX:XX:XX
21:03:48.494   D/ReactNativeBleManager: Stop scan
21:03:48.496   D/BluetoothAdapter: isLeEnabled(): ON
21:03:48.496   D/BluetoothLeScanner: could not find callback wrapper
```
