### ISSUE TITLE
Not work after turned Bluetooth on -> off -> on.

### ISSUE THREAD

**Issue by nagaokashi** [innoveit/react-native-ble-manager#391]
### Version

Tell us which versions you are using:

react-native-ble-manager v ^6.4.0
react-native v 0.55.4
iOS/Android v 10.3/8.0

### Expected behaviour

App should work normally after turned Bluetooth on -> off -> on.

### Actual behaviour

After turned Bluetooth on -> off -> on, app does not work.
See the picture.
<img width="431" alt="ble_notwork" src="https://user-images.githubusercontent.com/9496518/47026064-94210f80-d19f-11e8-967f-4bc84a6efc14.PNG">

At the second red line, a notification should started same as the first red line. But everything stop without any console log.
What happened ?

```
```

**Comment by chentianci123** [comment]
Hello, what method do you call to turn on Bluetooth?

**Comment by HKSOLDIER** [comment]
for turning on bluetooth.BleManager.enableBluetooth()
  .then(() => {
    // Success code
    console.log("The bluetooth is already enabled or the user confirm");
  })
  .catch((error) => {
    // Failure code
    console.log("The user refuse to enable bluetooth");
  });

**Comment by zeeshan6** [comment]
> for turning on bluetooth.BleManager.enableBluetooth() .then(() => { // Success code console.log("The bluetooth is already enabled or the user confirm"); }) .catch((error) => { // Failure code console.log("The user refuse to enable bluetooth"); });

Not working on Android 12 app gone carsh
