### ISSUE TITLE
StartNotification not working on Release Builds

### ISSUE THREAD

**Issue by nikoWah** [innoveit/react-native-ble-manager#393]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.1
- react-native v0.57.2
- Android v.8

### Expected behaviour
StartNotification should work in both Debug and Release Builds

### Actual behaviour
I have the correct peripheral ID and the log showed that the Connect method is working. Also, I can see on the device that the app is connected.

RetrieveServices seemed to take much longer to return in Release Builds, compared to Debug Builds.

It threw this error at the catch error for StartNotification method. 
{"line":765,"column":331,"sourceURL":"index.android.bundle"}

Or did I miss any settings?

Any help is appreciated. Thanks.

**Comment by marcosinigaglia** [comment]
Hi @nikoWah , I never tested with an Android 8 so I don't know if there is an issue. Try to debug.

**Comment by marcosinigaglia** [comment]
I've never had a problem like this...maybe can be a permission problem.

**Comment by nikoWah** [comment]
@marcosinigaglia I found the problem. 

I used Buffer.from to convert the hex string into bytes array for the write command. It seemed like the Buffer library is either missing or linked improperly in React Native. After using a NPM module, it worked.

Thanks for your time.
