### ISSUE TITLE
stopNotification disconnects peripheral

### ISSUE THREAD

**Issue by SherClockHolmes** [innoveit/react-native-ble-manager#4]
Hey,

I noticed that every time I stop a notification on iOS that my peripheral disconnects. Commenting out this line here seems to solve the issue:

https://github.com/innoveit/react-native-ble-manager/blob/master/ios/BleManager.m#L87

Is this intended behavior?

**Comment by marcosinigaglia** [comment]
Hi, fix in 0.0.12.
Thanks
