### ISSUE TITLE
cannot use refreshCache() method

### ISSUE THREAD

**Issue by yoshimoto8** [innoveit/react-native-ble-manager#401]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.0
- react-native v55.4
- Android v7.0

### Expected behaviour

refresh remaining cache

### Actual behaviour

Although I tried to refreshCache before disconnecting from the peripheral,  "Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference" always error occur.

### Steps to reproduce

call 'refreshCache(PeripheralId)' before disconnect method. Error occur

### related

#368 

my question : is this bug? or This is wrongly way or arguments?

**Comment by nagaokashi** [comment]
Try to use refreshCache  after connected and before retrieveServices.
Note: do not use '.cache'.
```
if (Platform.OS === 'android') {
      	BleManager.refreshCache(peripheral.id)
		  .then((peripheralInfo) => {
		    // Success code
		    console.log('cache refreshed!', peripheralInfo);
		    connectAndPrepare(peripheral, data_wr); 
		  }); 
      }
```

**Comment by marcosinigaglia** [comment]
Hi, I don't use this function in my project, is an internal function to force the refresh of the peripheral.
