### ISSUE TITLE
Hang up at await BleManager.retrieveServices()

### ISSUE THREAD

**Issue by nagaokashi** [innoveit/react-native-ble-manager#402]
### Version

react-native-ble-manager v ^6.4.0
react-native v 0.55.4
iOS/Android v 10.3/8.0

### Actual behaviour

Hang up at ### **await BleManager.retrieveServices()** after connected successful.
```
async function connectAndPrepare(peripheral, data_wr) 
{
  // Before startNotification you need to call retrieveServices
  await BleManager.retrieveServices(peripheral.id).then((peripheralInfo) => {
        console.log("retrieveServices",peripheralInfo);
        }); 
  // To enable BleManagerDidUpdateValueForCharacteristic listener
  await BleManager.startNotification(peripheral.id, service, characteristic).then(() => {
            console.log('Started notification on ' + peripheral.id);
        });    
  await BleManager.write(peripheral.id, service, characteristic, data_wr).then(() => {
                console.log('Write to peripheral');
        });
}
```
Stop without any error log..
Any idea?

**Comment by marcosinigaglia** [comment]
I don't know if you can use 'await' and 'then' in an async function.

**Comment by nagaokashi** [comment]
No problem for 'await' and 'then'. 
It is not always hang up. Just often.

**Comment by nagaokashi** [comment]
@Sean-Brown Yes, I'm sure.
@NN01010101 
I tried minutes but nothing happened. Sometime it works, sometime doesn't. Still no idea.

**Comment by NN01010101** [comment]
@nagaokashi Hi did you found the solution to that problem? I had the same issue, very often happening on iPhone 8 (iOS 12.1), almost never on iPhone 7(iOS 12.1). As a workaround I wait 1 second before startNotification, so far had 100% success.

**Comment by faizaanshah** [comment]
I am also having the issue if I use any timeout function it stucks forever but when I remove that it works fine.
