### ISSUE TITLE
Reading data from ble device after writing 

### ISSUE THREAD

**Issue by KayhanB** [innoveit/react-native-ble-manager#403]
### Version

- react-native-ble-manager v6.5.1
- react-native v0.57.4
- Android

Hi

Our ble device HM10 bluetooth 4.0  runing on a custom electronic card . When i writing data to device, card  returning me data. but i can't read that data .We tested it with BLE Scanner  app it is on the apple store and its working perfectly.  BLE Scanner getting data  what we should to see.
 I've tried to use read() function after write function  but read function returning me something strange.
How can i do this and  what am i doing wrong

**This is my  console after writing and reading.**

```
Peripheral is connected
Writed :  566666
ReadData:  Ô69ØCT
```

### **This is my code**

```
 bleManagerEmitter.addListener(
      'BleManagerConnectPeripheral',
      (device) => {
        BleManager.isPeripheralConnected(device.peripheral, [])
          .then((isConnected) => {
            if (isConnected) {
              console.log('Peripheral is connected')
              BleManager.retrieveServices(device.peripheral)
                .then((peripheralDevice) => {
                  let service = peripheralDevice.characteristics[6].service
                  let characteristic = peripheralDevice.characteristics[6].characteristic
                  this.write(this.state.message, device, service, characteristic)
                })
            } else {
              console.log('Peripheral is NOT connecteddd!');
            }
          })
      })


write(message, device, service, characteristic) {

    let byteMsg = stringToBytes(message);
    BleManager.write(device.peripheral, service, characteristic, byteMsg)
      .then(() => {
        console.log('Writed : ', message)
        BleManager.read(device.peripheral, service, characteristic, byteMsg)
          .then((readData) => {
            this.setState({ connecting: false, connectingId: null, writedId: device.peripheral, writeErrorDeviceId: null }, () => {
              let readedData = bytesToString(readData)
              console.log('ReadData: ', readedData)
              this.disconnect(device.peripheral)
            })
          }).catch((err) => console.log(err))
      }).catch((err) => {
        console.log(err, " Error Write")
        this.setState({ connecting: false, connectingId: null, writedId: null, writeErrorDeviceId: device.peripheral })
        this.disconnect(device.peripheral)

      })

  }

```

**Comment by marcosinigaglia** [comment]
Hi, are you sure that you have to read? Maybe you need to use notification.

**Comment by KayhanB** [comment]
I have read your documentation but i dont understand what is notification for and im sure after read function return 'Ô69ØCT' that string

**Comment by marcosinigaglia** [comment]
What did you expect to read?

**Comment by KayhanB** [comment]
ble device runing on our card. This card listening ble device and  When i send  something to ble device   card return me answer through ble device.  İ want to read that answer. When i trying to read device , result is  "Ô69ØCT" wrong .We changing answer on card but result is same every time. This is the my problem but  no need to read any more we solved this problem with another way .
thank you for taking the time and answering

**Comment by marcosinigaglia** [comment]
Are you sure that is not an encoding problem? What kind of data are you reading?

**Comment by MrDockal** [comment]
Hi @KayhanB in order to get an understanding of the BLE communication, I would recommend you to go through these posts
[Very nice explained here](https://www.silabs.com/community/wireless/bluetooth/knowledge-base.entry.html/2018/05/30/ble_basics_masters-i4n9)
[This medium post is more about programming](https://medium.com/@avigezerit/bluetooth-low-energy-on-android-22bc7310387a)
[Download the starter kit, which contains more theory](https://www.bluetooth.com/develop-with-bluetooth/build/developer-kits/bluetooth-starter-kit)

If you want to check your peripheral profiles, services and characteristics I would recommend you to use (nRF Connect for android)[https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=cs]

Hope it helps you to get the problem solved.

**Comment by KayhanB** [comment]
@MrDockal thank you for your interest

**Comment by malikowaisghafoor** [comment]
Do you have any idea how I can see BLE SCANNER data on run time in any Android device?
