### ISSUE TITLE
More details on device to device BLE communication? Is it even possible.

### ISSUE THREAD

**Issue by Technaur** [innoveit/react-native-ble-manager#404]
Hi all,

I have a question about this library. I am sort of new to react native and even newer to bluetooth on mobile devices. (Never worked with BLE in platform native code either)

Is it possible to set up device to device communication with this library? I just want to send a string across from one device to another. Even better if it can be from an Android device to an iOS device, and visa versa.

I understand the concept of scanning and then connecting, but the idea of actually getting information across to other devices still confuses me.

Also curious to know if you can set up your own service and characteristic with read, write and notify abilities?

Thanks in advance!

PS. If someone had a public repository with an example of this, that would be great. :)

**Comment by marcosinigaglia** [comment]
Hi, with this library you can only connect to a device as a 'client'.
