### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by MrDockal** [innoveit/react-native-ble-manager#406]
### Question

Have you considered to add Typescript support? This package is not even listed in a [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

I am using your project with a custom types that I had created. And so far I am very happy to use this library.
Would you accept PR adding typescript support?

Thanks,
Jan

**Comment by marcosinigaglia** [comment]
I Jan, I never used Typescript, what's will change adding the support?

**Comment by MrDockal** [comment]
Hi, there are two ways of doing so. The first one is to rewrite the BleManager to typescript and let the build process output BleManager.js and BleManager.d.ts. The second way is to add BleManager.d.ts to project files, however, everytime anyone changes the javascript definition, the type definition should reflect that changes.

**Comment by marcosinigaglia** [comment]
Hi, I'm taking a look in this [post](https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c) and it seems easy to add the compiler in the npm build script. So, since the 'BleManager.js' is very simple, we can rewrite in Typescript. Your PR is welcome.

**Comment by rknlhrqy** [comment]
Hi,
I am writing a react native mobile app in Typescript. This app uses react-native-ble-manager. But it does not work. It always complains "Native module cannot be null". See the snapshot of the simulator and the source code of index.ts below
<img width="409" alt="screen shot 2018-11-25 at 9 55 56 am" src="https://user-images.githubusercontent.com/15458277/48980539-71382400-f098-11e8-8f91-d37c4455b8a9.png">
<img width="614" alt="screen shot 2018-11-25 at 9 56 20 am" src="https://user-images.githubusercontent.com/15458277/48980541-76956e80-f098-11e8-9f1c-1735b5b8b787.png">
I did run "react-native link react-native-ble-manager". But it appears to me that Typescript somehow still cannot take in react-native-ble-manager.
I set up my Typescript environment based on the following link: 
![image](https://user-images.githubusercontent.com/15458277/48980576-f6233d80-f098-11e8-97c8-e069148eaae9.png)
Please take a look.
THank you.
--Kening

**Comment by rknlhrqy** [comment]
Hi,
I can get it work by putting the line7-10 codes into a js file. So react-native-ble-manager does not work in Typescript environment. It will be a great advantage that react-native-ble-manager can support Typescript.
Thanks
--Kening

**Comment by MrDockal** [comment]
Hi @rknlhrqy 
I am working on integration. I would like to create PR in next two weeks. You can still use `require` instead of `import..`.
For a now you can add custom typings by yourself, just take a look at my [repo](https://github.com/MrDockal/breathing-friend-app/blob/master/types/react-native-ble-manager/index.d.ts). Keep in mind that interfaces are not perfect yet.

Cheers,
Jan
