### ISSUE TITLE
requestMTU promise does not return on Android API 23

### ISSUE THREAD

**Issue by ssajnani** [innoveit/react-native-ble-manager#411]
### Information

Need to send more than 512 bytes, however, I cannot increase the MTU, the function never returns it's promise. I tried to print out the result of the function and it never prints. How shall I proceed? My other alternative is to process data in chunks on the server side.

**Comment by marcosinigaglia** [comment]
Hi, can you debug what happens?

**Comment by dionator** [comment]
Had the same issue. ended up
