### ISSUE TITLE
When I call writing funtion I get error. Error is writing status 133

### ISSUE THREAD

**Issue by EdisonDevadoss** [innoveit/react-native-ble-manager#419]
Hai friends, last one week I got agony with this problem.

### Version
- react-native-ble-manager ^6.4.0
- react-native 0.55.4

**My writing function:**

    const data = stringToBytes('TT');
    setTimeout(() => {
      BleManager.write(
        this.props.deviceDetails.deviceId,
        serviceId,
        BatteryTypeCharacteristicId,
        data
      )
        .then((success) => {
          alert('success');
          this.props.dispatch(
            readConfigBatterySetting(this.props.deviceDetails.deviceId)
          );
        })
        .catch((error) => {
          alert('error failed');
        });
    }, 500);

Can you tell me what type of mistakse I made in my code.

**Comment by priyanka-Sadh** [comment]
@Marcos-Costa why did you closed this, since there is no answer of anyone, and no message that issue gets fixed ?

**Comment by juliobetta** [comment]
> @Marcos-Costa why did you closed this, since there is no answer of anyone, and no message that issue gets fixed ?

@marcosinigaglia ☝️
