### ISSUE TITLE
How to get battery level of connected device?

### ISSUE THREAD

**Issue by nagaokashi** [innoveit/react-native-ble-manager#422]
### Version

Tell us which versions you are using:

eact-native-ble-manager v ^6.4.0
react-native v 0.55.4
iOS/Android v 10.3/8.0

### So, How to get battery level of connected device?

**Comment by marcosinigaglia** [comment]
https://stackoverflow.com/questions/19539535/how-to-get-the-battery-level-after-connect-to-the-ble-device

**Comment by RRMoelker** [comment]
For future reference, the iOS version requires using the short UUID codes.

So
* Battery service: `180F`
* Battery characteristic: `2A19`

**Comment by prasanna-colan** [comment]
in android how to i get battery status
