### ISSUE TITLE
[Android] writeQueue not clear when disconnect

### ISSUE THREAD

**Issue by ducNgbk** [innoveit/react-native-ble-manager#430]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.4
- react-native v0.57.7
- Android 7.0

### Expected behaviour
variable `writeQueue` should call `clear()` when a device disconnected
### Actual behaviour
Such thing won't happen. This will cause error when a disconnection happens when I have a writeQueue to send
I have to modify directly to this lib to avoid this error.
```
@Override
	public void onConnectionStateChange(BluetoothGatt gatta, int status, int newState) {
                         .....
		if (newState == BluetoothGatt.STATE_CONNECTED) {
                         .....
		} else if (newState == BluetoothGatt.STATE_DISCONNECTED) {
                       ......
			writeCallback = null;
			writeQueue.clear();          // Add this line
			readCallback = null;
			retrieveServicesCallback = null;
			readRSSICallback = null;
			registerNotifyCallback = null;
			requestMTUCallback = null;
		}

	}
```

I hope this will be included in next release.
Thank you for your awesome library

**Comment by marcosinigaglia** [comment]
Hi @ducNgbk , thanks, the next time you can also make a PR.
