### ISSUE TITLE
Basic understanding

### ISSUE THREAD

**Issue by assafb81** [innoveit/react-native-ble-manager#432]
### Version
- react-native-ble-manager v6.5.4
- react-native v0.57.8
- iOS v12.1.2

### Questions
first let me say that the package is great.
I am trying to understand the basic of the package.
`BLE Peripheral Simulator` app (from google store) is used as a peripheral device, and the `Heart Rate Monitor` in it is used.

#### 1st question:
- When using `connect()` method - does it means that the devices are `paired` or `bonded`?

#### 2nd question:
- When using `retrieveServices` the response contain 3 characteristics:
1. `characteristicUUID`: `2A37` -> with property "Notify"
2. `characteristicUUID`: `2A38` -> with property "Read"
3. `characteristicUUID`: `2A39` -> with property "Write"

So,
- In order to listen to the notifications, the registration is done to `characteristicUUID - 2A37`?
- In order to write, it is done with `characteristicUUID - 2A39`?

Thanks

**Comment by assafb81** [comment]
Thanks for the quick reply.
I know that `pairing` and `bonding` are different this is why I asked the 1st question.
I will try to clarify my question - as I understand, correct me if I am wrong, `connect` is used to perform `pairing` between 2 devices.
- iOS: the OS is responsible to perform `bond` (according to OS parameters) - and we as developers don't have access to this api (including in SWIFT).
- Android: `bonding` is possible using `createBond`. Can I use `createBond` without `connect` or do I have to use `connect` prior to `createBond`?

**Comment by marcosinigaglia** [comment]
You don't need to pair to a device to connect with ble. In iOS is the OS that manage the pairing and bonding process, in Android I think you can 'force' with `createBond`.

**Comment by assafb81** [comment]
thanks
