### ISSUE TITLE
Security support

### ISSUE THREAD

**Issue by assafb81** [innoveit/react-native-ble-manager#435]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.4
- react-native v0.57.8
- iOS v12.1.2

Does this package support BLE secure connection?
I mean, How is it possible to allow only to "allowed" central devices to connect with peripheral device with some kind of PIN number?

Thanks

**Comment by marcosinigaglia** [comment]
Hi, I never tried but I think that the "secure connection" is transparent for this library.

**Comment by assafb81** [comment]
thanks
