### ISSUE TITLE
bluetooth permission request

### ISSUE THREAD

**Issue by cruizg** [innoveit/react-native-ble-manager#445]
when the bluetooth is off every time I start the application I use: BleManager.enableBluetooth
in componentDidMount asks me to accept permission request for bluethoo, my question is how can I not ask for that request every time I start the application

### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.6
- react-native v0.55.3
- iOS/Android v.7.1

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi @cruizg , do you check the ble state before enable?
