### ISSUE TITLE
Can't read data from TI cc2650stk

### ISSUE THREAD

**Issue by faizaanshah** [innoveit/react-native-ble-manager#447]
### Version

Tell us which versions you are using:

- react-native v. 0.57.8
- iOS/Android v.8.0

### Expected behaviour

Tell us what should happen
read() should return raw data from accelerometer.
### Actual behaviour

Tell us what happens instead
read() is continuously returning 0
### Steps to reproduce

I had been trying to fetch accelerometer data from ti cc2650 sensortags but I am continuously getting 0 data, Attached is the code:

`readServices(device){
    if(device){
      if(device.connected){
        console.log('Previously Connected now disconnected');
        BleManager.disconnect(device.id);
      }else{
        BleManager.connect(device.id).then(()=>{
          let peripherals = this.state.peripherals;
          let p = peripherals.get(device.id);
          if (p) {
            p.connected = true;
            peripherals.set(device.id, p);
            this.setState({peripherals});
            console.log('Connected to ' + device.id);
           // console.log("I am here");
         //  setTimeout(()=>{ //execute after 9ms
              //console.log("Time out Function");
              BleManager.retrieveServices(device.id)
                .then((peripheralInfo) => {
                // Success code
                console.log('Peripheral info:', peripheralInfo);
                  var MOVEMENT_SERVICE = 'f000aa80-0451-4000-b000-000000000000';
                  var MOVEMENT_DATA = 'f000aa81-0451-4000-b000-000000000000';
                  // var MOVEMENT_CONFIG = 'f000aa82-0451-4000-b000-000000000000';
                  // var MOVEMENT_PERIOD = 'f000aa83-0451-4000-b000-000000000000';
                  // var MOVEMENT_NOTIFICATION = '00002902-0000-1000-8000-00805f9b34fb';
            //      setTimeout(()=>{
                    BleManager.startNotification(device.id, MOVEMENT_SERVICE, MOVEMENT_DATA).then(()=>{
                        //adjust Movement notification
                        console.log('Started notification on ' + device.id);
                        BleManager.read(device.id,MOVEMENT_SERVICE,MOVEMENT_DATA).then((data)=>{
                          console.log("Data Retrieved:"+data);
                          const buffer = Buffer.from(data);    //https://github.com/feross/buffer#convert-arraybuffer-to-buffer
                          const sensorData = buffer.readUInt8(1, true);
                          // var sensorData = new Uint8Array(data);
                          console.log(sensorData);
                          var value = this.getAccelerometerValues(sensorData);
                          x = value.x;
                          y = value.y;
                          z = value.z;
                          console.log(x+"::"+y+"::"+z)  ;
                        }).catch((error)=>{
                          console.log("ERRor:"+error);
                        });
                    }).catch((error) => {
                      console.log('Notification error', error);
                    });
          //        },200);
               });
      //     },9);
          }
        }).catch((error) => {
          console.log('Connection error', error); //couldn't connect
        });
      }
    }
  }
  getAccelerometerValues = function (data) {
    var divisors = { x: 16384.0, y: 16384.0, z: 16384.0 };
    // var divisors = { x: -16384.0, y: 16384.0, z: -16384.0 };
    // Calculate accelerometer values.
    var gx = endianness(data, 0) / (65536 / 500);
    var gy = endianness(data, 2) / (65536 / 500);
    var gz = endianness(data, 4) / (65536 / 500);
    var ax = endianness(data, 6) / divisors.x;
    var ay = endianness(data, 8) / divisors.y;
    var az = endianness(data, 10) / divisors.z;

    return { x: ax, y: ay, z: az, a: gx, b: gy, c: gz };
};`

![ssss](https://user-images.githubusercontent.com/22859078/51444733-475c5000-1d1d-11e9-8348-666cc1eb5376.PNG)

**Comment by marcosinigaglia** [comment]
Hi @faizaanshah , if the device use the notification you don't have to call the read method but to handle the notification event (check the documentation).
