### ISSUE TITLE
Java exception in 'NativeModules' java.lang.NoClassDefFoundError: android/bluetooth/le/ScanRecord

### ISSUE THREAD

**Issue by shengliZh** [innoveit/react-native-ble-manager#448]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.6
- react-native v0.56
- iOS/Android Android4.4.2

### Expected behaviour

Open app will crash

### Actual behaviour

Java exception in 'NativeModules' java.lang.NoClassDefFoundError: android/bluetooth/le/ScanRecord

### Steps to reproduce

1.  Open app
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi, check your project api level.

**Comment by shengliZh** [comment]
Hi, @marcosinigaglia 
This is my project api level, my phone OS Version is 4.4.2.
![image](https://user-images.githubusercontent.com/25652977/51507943-3bac7e80-1e2e-11e9-9d44-f86ea59d062f.png)

**Comment by lvlrSajjad** [comment]
Same here, min SDK version is 19

**Comment by yangxy112683** [comment]
same here, min SDK version is 19, RN version is ^0.57.8;

**Comment by owen12ab** [comment]
Same here, min SDK version is 19 and RN version is 0.56.0, my android device os is 4.4.4. Any update on this issue?

**Comment by JackClown** [comment]
Catch the same problem.I find that `android.bluetooth.le.ScanRecord` is added in API level 21.

**Comment by marcosinigaglia** [comment]
Hi @shengliZh , can you try the latest release?
