### ISSUE TITLE
Understanding question

### ISSUE THREAD

**Issue by assafb81** [innoveit/react-native-ble-manager#449]
I am going over the example code and I trying to understand why you need both:
import this here:
```
import BleManager from 'react-native-ble-manager';
```
and later:
```
const BleManagerModule = NativeModules.BleManager;
const bleManagerEmitter = new NativeEventEmitter(BleManagerModule);
```

Why the 1st one is not used for the events as well?

Thanks

**Comment by marcosinigaglia** [comment]
Hi, I think is the same, you can make a PR to clean the example.

**Comment by marcosinigaglia** [comment]
Hi, I tried and is not the same.
