### ISSUE TITLE
The connect success callback is never called if the peripheral has no service

### ISSUE THREAD

**Issue by haibinyu** [innoveit/react-native-ble-manager#45]
I encounter a issue, when my ble device has no service, the connect success callback is never called after I call:

```
BLEManager.connect(peripheralId)
.then(() => {
  // the code here is never called
})
```
After research the code, I find that after connected the peripheral, connect callback is not called, but **discoverServices** method and **discoverCharacteristics:forService:** is called immediately.
I think this is not a best practice and it is better to split  **discoverServices** from **connect**.

**Comment by marcosinigaglia** [comment]
Hi, I thinks there is a reason for call the callback after discoverServices, I'll investigate

**Comment by marcosinigaglia** [comment]
Hi, temporarily you can use BleManagerConnectPeripheral event (https://github.com/innoveit/react-native-ble-manager/commit/e17ce837d51537a6288895f0f381a013421a3050)

**Comment by haibinyu** [comment]
@marcosinigaglia thanks, 🎉
