### ISSUE TITLE
Bluetooth Devices not listing in android

### ISSUE THREAD

**Issue by Sanjeevs1995** [innoveit/react-native-ble-manager#456]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.4
- react-native v0.57.8
- Android v.8.0

### Expected behavior

ESP 32 Bluetooth module should get listed in the application

### Actual behavior

The device does not get listed. 

But it shows in the OS Bluetooth listing UI

The application works fine for all android version<8.

**Comment by marcosinigaglia** [comment]
Hi @Sanjeevs1995 , Android 8 have a lot of issue with the bluetooth, try to google and find a solution, I don't thinks is a library problem but a OS problem.

**Comment by Sanjeevs1995** [comment]
But while using native code the device gets listed

I followed the steps mentioned in android native developer site

https://developer.android.com/guide/topics/connectivity/bluetooth#java

**Comment by marcosinigaglia** [comment]
So figure out the difference.
