### ISSUE TITLE
why do we need to call retrieveServices?

### ISSUE THREAD

**Issue by dmorr041** [innoveit/react-native-ble-manager#459]
This is merely a question... I'm wondering why the documentation states we need to call retrieveServices() before a read, write, or startNotification? What are the implications of not calling it, i.e. what bad things could happen potentially?

I'm trying to minimize the time it takes for a write operation, as the user may be requesting a write at a rate faster than the time it takes for a write to complete in some scenarios. I've noticed a slightly faster time of completion when I only connect() and then write() as opposed to connect(), then retrieveServices(), then write(). I've removed the retrieveServices call and my multi colored light is changing colors and brightness as expected. The code seems to function without it. So what could potentially happen behind the scenes if I don't call it?

**Comment by marcosinigaglia** [comment]
Hi @dmorr041 , in my experience I always had to call retrieveServices before write or read. Maybe with some device is not needed.
