### ISSUE TITLE
Crash on writeWithoutResponse

### ISSUE THREAD

**Issue by mahyali** [innoveit/react-native-ble-manager#460]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.2
- react-native v0.57.8
- Android v28

### Expected behaviour

writeWithoutResponse should send binary data to the ble device

### Actual behaviour

I get a crash (red screen) containing an error saying "Malformed calls from JS: field sizes are different"

### Steps to reproduce
`
        await BleManager.writeWithoutResponse(
                this.state.device.id,
                this.UUID_SERVICE,
                this.UUID_TX,
                binaryMessage)
                .catch(error => alert(error));
`
Calling that function causes the crash. 

### Stack trace and console log
<img width="839" alt="screen shot 2019-01-31 at 5 12 13 pm" src="https://user-images.githubusercontent.com/10799786/52096406-90ad6a80-257b-11e9-9962-15ddab25ec73.png">

```
```

**Comment by marcosinigaglia** [comment]
Hi, do you have the same error using `write`?

**Comment by mahyali** [comment]
I think I figured it out. Using a plain array works but not a typed Array like Uint8Array for some reason.
