### ISSUE TITLE
Help me make the example work in android and iOS

### ISSUE THREAD

**Issue by omatrot** [innoveit/react-native-ble-manager#462]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.0
- react-native v0.57.8
- iOS 12.1.3 / Android 7.1.1

### Expected behaviour

The example should compile and run without issue

### Actual behaviour

On iOS, the app starts then failed with the red screen:
**Native Module cannot be null**.

I can't compile the example on Android:

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-ble-manager.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-ble-manager.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-ble-manager.
Show Details
Affected Modules: app

### Steps to reproduce

1. Download or clone the repository
2. Open the project in XCode / Android Studio
3. Compile and run

**Comment by marcosinigaglia** [comment]
Hi @omatrot , try with a new empty project and then use the code in the example.
