### ISSUE TITLE
Manufacturer Data - Help

### ISSUE THREAD

**Issue by crobinson42** [innoveit/react-native-ble-manager#464]
Hello - I'm new to Bluetooth and struggling to understand how I can get the names of devices that are discovered nearby.

I've tried decoding the `manufacturerData.bytes` as well as the base64 data and get some very odd character output - nothing legible or descriptive as to what device it is for.

Any help or light shed on this would be greatly appreciated! Or, pointing to resources where one can learn more.

**Comment by marcosinigaglia** [comment]
Hi, in the BleManagerDiscoverPeripheral event you already have the device name.

**Comment by crobinson42** [comment]
@marcosinigaglia thx - what I'm saying is that the field is `null` ie: `peripheral.name === null` for all devices discovered. Is that normal?

**Comment by marcosinigaglia** [comment]
Yes, can be.
