### ISSUE TITLE
Write without call startNotification before

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#467]
Just a question of beginner:

Do I have to call startNotification function before I use the function Write?
I know I have to call retrieveServices function before Write but what about startNotification...

Thanks in advance

**Comment by marcosinigaglia** [comment]
Hi @tal987 , `startNotification` is to read data from the device so depends, probably is not necessary.

**Comment by tal987** [comment]
@marcosingaglia so if startnotification read the data from the device so why do we mend the read function? What is the difference between the read function and the startnotification function?

**Comment by marcosinigaglia** [comment]
Using `startNotification` you start to read the data that the device send to you depends on its specification. Using `read` you ask a value.

**Comment by tal987** [comment]
@marcosinigaglia when I use the read fucnction, from the readMe file I understand it return promise but the data inside the promise is in type String or Byte array?

**Comment by marcosinigaglia** [comment]
Is an array, check the example in the readme.
