### ISSUE TITLE
Characteristic not found

### ISSUE THREAD

**Issue by amjalca** [innoveit/react-native-ble-manager#473]
### Version

Tell us which versions you are using:

- react-native-ble-manager v.6.6.2
- react-native v.0.57.8
- iOS/Android v.6.0.1

### Expected behaviour

Get temperature and humidity
```
BleManager.read((peripheral.id).toString(), '0000ffe1-0000-1000-8000-00805f9b34fb', '7f280002-8204-f393-e0a9-e50e24dcca9e')
                    .then((readData) => {
                      // Success code
                      console.log('Read: ' + readData);

                      const buffer = Buffer.Buffer.from(readData);    //https://github.com/feross/buffer#convert-arraybuffer-to-buffer
                      const sensorData = buffer.readUInt8(1, true);
                    })
                    .catch((error) => {
                      // Failure code
                      console.log('No Read -> ', error);
                    });
```

### Actual behaviour

I send uuid of service and characteristic in Promise, but in error console get not found

### Steps to reproduce

1. Scan peripherals
2. Connect with S1 Minew (Success)
3. Waiting for read data

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: Errore su caratteristica 7f280002-8204-f393-e0a9-e50e24dcca9e
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics()' on a null object reference
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at it.innove.Peripheral.findNotifyCharacteristic(Peripheral.java:552)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at it.innove.Peripheral.setNotify(Peripheral.java:490)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at it.innove.Peripheral.registerNotify(Peripheral.java:537)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at it.innove.BleManager.startNotification(BleManager.java:265)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at android.os.Handler.handleCallback(Handler.java:739)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at android.os.Looper.loop(Looper.java:148)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
02-19 17:11:09.165 24037 24154 E ReactNativeBleManager: 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by marcosinigaglia** [comment]
Did you call `retrieveServices` before? Is the characteristic in the return data?

**Comment by amjalca** [comment]
Yes, I call retrieveServices. I have several characteristic for read info of beacon
```
'Characteristics ---> ', { characteristics: 
02-20 14:11:04.550 31853 31894 I ReactNativeJS:    [ { properties: { Write: 'Write', Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a00',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a01',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a04',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a29',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a24',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a25',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a27',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a26',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a28',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: 
02-20 14:11:04.550 31853 31894 I ReactNativeJS:         { Notify: 'Notify',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:           Write: 'Write',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:           WriteWithoutResponse: 'WriteWithoutResponse' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '7f280002-8204-f393-e0a9-e50e24dcca9e',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: { Notify: 'Notify', Write: 'Write' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a08',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: 
02-20 14:11:04.550 31853 31894 I ReactNativeJS:         { Notify: 'Notify',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:           Write: 'Write',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:           WriteWithoutResponse: 'WriteWithoutResponse' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '7f280005-8204-f393-e0a9-e50e24dcca9e',
02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280004-8204-f393-e0a9-e50e24dcca9e' } ],
02-20 14:11:04.550 31853 31894 I ReactNativeJS:   services: 
02-20 14:11:04.550 31853 31894 I ReactNativeJS:    [ { uuid: '1800' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '1801' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '180a' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '7f280004-8204-f393-e0a9-e50e24dcca9e' } ]
```
In the console, i can see

```
02-20 14:04:27.320 31853 31894 I ReactNativeJS: 'Started notification on AC:23:3F:A0:04:93'
02-20 14:04:27.850 31853 31894 I ReactNativeJS: 'In Read -> ', 'Characteristic 7f280002-8204-f393-e0a9-e50e24dcca9e not found.'
02-20 14:04:27.980 31853 31894 I ReactNativeJS: 'Write: ', [ [Getter/Setter],
02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter],
02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter],
02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter] ]
02-20 14:04:27.980 31853 31894 I ReactNativeJS: 'Received data from AC:23:3F:A0:04:93 characteristic 7f280002-8204-f393-e0a9-e50e24dcca9e', [ 69, 82, 82, 32, 67, 77, 68 ]
```

**Comment by marcosinigaglia** [comment]
Hi, the characteristic is not readable.

**Comment by samsun009** [comment]
> Yes, I call retrieveServices. I have several characteristic for read info of beacon
> 
> ```
> 'Characteristics ---> ', { characteristics: 
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:    [ { properties: { Write: 'Write', Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a00',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a01',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a04',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '1800' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a29',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a24',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a25',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a27',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a26',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { properties: { Read: 'Read' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a28',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: 
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:         { Notify: 'Notify',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:           Write: 'Write',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:           WriteWithoutResponse: 'WriteWithoutResponse' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '7f280002-8204-f393-e0a9-e50e24dcca9e',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: { Notify: 'Notify', Write: 'Write' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '2a08',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { descriptors: [ { value: null, uuid: '2902' } ],
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        properties: 
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:         { Notify: 'Notify',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:           Write: 'Write',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:           WriteWithoutResponse: 'WriteWithoutResponse' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        characteristic: '7f280005-8204-f393-e0a9-e50e24dcca9e',
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:        service: '7f280004-8204-f393-e0a9-e50e24dcca9e' } ],
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:   services: 
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:    [ { uuid: '1800' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '1801' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '180a' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '7f280001-8204-f393-e0a9-e50e24dcca9e' },
> 02-20 14:11:04.550 31853 31894 I ReactNativeJS:      { uuid: '7f280004-8204-f393-e0a9-e50e24dcca9e' } ]
> ```
> 
> In the console, i can see
> 
> ```
> 02-20 14:04:27.320 31853 31894 I ReactNativeJS: 'Started notification on AC:23:3F:A0:04:93'
> 02-20 14:04:27.850 31853 31894 I ReactNativeJS: 'In Read -> ', 'Characteristic 7f280002-8204-f393-e0a9-e50e24dcca9e not found.'
> 02-20 14:04:27.980 31853 31894 I ReactNativeJS: 'Write: ', [ [Getter/Setter],
> 02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter],
> 02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter],
> 02-20 14:04:27.980 31853 31894 I ReactNativeJS:   [Getter/Setter] ]
> 02-20 14:04:27.980 31853 31894 I ReactNativeJS: 'Received data from AC:23:3F:A0:04:93 characteristic 7f280002-8204-f393-e0a9-e50e24dcca9e', [ 69, 82, 82, 32, 67, 77, 68 ]
> ```

can you share your code used for write? because I have error while write characterstic not found.
