### ISSUE TITLE
Read Failed for glucose measurement on android

### ISSUE THREAD

**Issue by dharmeshapex** [innoveit/react-native-ble-manager#483]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.2
- react-native v0.55.4
- Android v8.1.0

### Expected behaviour

I am using Contour plus one bluetooth device for glucose measurement with my react native application. There are currently 3 measurement data in that device which i should be able to fetch from my react native application with this plugin.

### Actual behaviour

When i use below code to read data with serviceUUID and characteristiUUID, It gives error that **read failed.**
             
```
BleManager.read(peripheral.id, '1808', '2a18')
              .then((readData) => {
                // Success code
                console.log('Read: ------------->>>>>>>>>>>2a34' + readData);

                const buffer = Buffer.from(readData);  
                const sensorData = buffer.readUInt8(1, true);

                console.log("buffer => ",buffer);
                console.log("sensor Data => ",sensorData);

              })
              .catch((error) => {
                // Failure code
                console.log('error 2a34', error); //this is always printed with 'Read failed'
              });
```

However there is strange behaviour which is when i comment that code and use different way to read data which is first start notification on that same serviceUUID and characteristiUUID and then setting ```BleManagerDidUpdateValueForCharacteristic``` event listener, then it gives me output but i don't know how to proceed it.

```
  BleManager.startNotification(peripheral.id, '1808', '2a18').then((noti)=>{
                console.log("Notification started => ",noti);
                // Add event listener
                bleManagerEmitter.addListener(
                  'BleManagerDidUpdateValueForCharacteristic',
                  ({ value, peripheral, characteristic, service }) => {
                      // Convert bytes array to string
                      console.log("all arguments => ",...arguments);
                      const data = bytesToString(value);
                      console.log(`Recieved ${data} for characteristic ${characteristic}`);
                  }
                );

              }).catch((errNoti)=>{
                console.error("error while noti => ",errNoti)
              })
```

All I want to know is how to read old data stored in device without setting eventEmitter, because eventEmitter will only give us new record for one time.

### Stack trace and console log
[Checkout Peripheral info stored at jsoneditoronline](https://jsoneditoronline.org/?id=38dc9c8a70954868a9539bf24150cbec)

**Comment by marcosinigaglia** [comment]
Hi, try to use the 128bit version of the UUIDs (https://www.novelbits.io/uuid-for-custom-services-and-characteristics/)
