### ISSUE TITLE
Writing Uint8 number to device

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#484]
Hey, 
I want to write a uint8 number using the Write function, I know the function getting byteArray but I need to write the number 10(=0A) how can I do that? just simply send 10?

**Comment by marcosinigaglia** [comment]
Hi,
`BleManager.write('XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', [10])`
