### ISSUE TITLE
First write isn't working

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#485]
I'm trying to write into my device, when I'm using different app like NRFconnect its working with no problem, but here only 'Write3' and 'Write4' is working,  'Write1' and 'Write2' not working(I can't even see the console.log) and I still see the previous write. im not getting any error what should be the problem:

      BleManager.retrieveServices(peripheralId).then((peripheralData) => {
    //change name
    BleManager.write(peripheralId, '0000af40-62bd-468a-9b17-3918fdafb86d', '0000af41-62bd-468a-9b17-3918fdafb86d', [10]).then(() => {
      console.log('Writed1');

      BleManager.write(peripheralId, '0000af40-62bd-468a-9b17-3918fdafb86d', '0000af42-62bd-468a-9b17-3918fdafb86d',[53]).then(() => {
        console.log('Writed2');
      }) .catch((error) => {
        // Failure code
        console.log(error);
      });

    }) .catch((error) => {
      // Failure code
      console.log(error);
    });
     })
     BleManager.retrieveServices(peripheralId).then((peripheralData) => {

       // change length
        BleManager.write(peripheralId, '0000af40-62bd-468a-9b17-3918fdafb86d', '0000af41-62bd-468a-9b17-3918fdafb86d', [11]).then(() => {
          console.log('Writed3');
    
          BleManager.write(peripheralId, '0000af40-62bd-468a-9b17-3918fdafb86d', '0000af42-62bd-468a-9b17-3918fdafb86d',[1] ).then(() => {
            console.log('Writed4');
          })
    
        })
      })

*Put attention that im trying to write to same service and the same char but different param... 
When I remove 'Write3','Write4' I can see 'Write1','Write2' but when all the writes together Im getting the problem above

**Comment by marcosinigaglia** [comment]
Hi, you have to queue the writes, you can't write simultaneously

**Comment by tal987** [comment]
@marcoinigaglia what do you mean queue?
I can’t do write inside the then of the first write? Should I separate the write to 4 functions?

**Comment by marcosinigaglia** [comment]
You have to move the write 3 and 4 inside the write 2 then.
