### ISSUE TITLE
Android phone Name is null

### ISSUE THREAD

**Issue by tianweicc** [innoveit/react-native-ble-manager#487]
### Version

Tell us which versions you are using:

- react-native-ble-manager v new
- react-native v0.54
- iOS/Android v.android

phone Name is null
```

**Comment by marcosinigaglia** [comment]
Hi, the device name can be null.

**Comment by Lloyd1229** [comment]
> Hi, the device name can be null.

Have you solved it? I had the same problem

**Comment by Robiullah2244** [comment]
Same issue
