### ISSUE TITLE
Android connect error

### ISSUE THREAD

**Issue by tianweicc** [innoveit/react-native-ble-manager#488]
### Version

Tell us which versions you are using:

- react-native-ble-manager v  new
- react-native v0.54
- iOS/Android v.android

![1](https://user-images.githubusercontent.com/17263719/54266133-c2214900-45b1-11e9-8ea8-f7540fb763e1.jpg)
connect error

**Comment by marcosinigaglia** [comment]
Hi, I can't help, can be anything.
