### ISSUE TITLE
Byte array for sending data

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#489]
Hey,
I have a question about the Write function and the data that I should pass.
For instance if I want to send the word 'hello'. I should send this array:
[68,65,6c,6c,6f] I mean the hex convert of the string or it may be this array:
[104,101,108,108,111] = the decimal convert of the string "hello"?

Thank you for the answer

**Comment by wangrenhai** [comment]
Thank you for your reminding, thanks to your plug-in, or my bluetooth printer function simply can not do out. You are selfless devotees, you are the best.




------------------ 原始邮件 ------------------
发件人: "tal987"<notifications@github.com>;
发送时间: 2019年3月14日(星期四) 凌晨0:24
收件人: "innoveit/react-native-ble-manager"<react-native-ble-manager@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [innoveit/react-native-ble-manager] Byte array for sending data(#489)




Hey,
 I have a question about the Write function and the data that I should pass.
 For instance if I want to send the word 'hello'. I should send this array:
 [68,65,6c,6c,6f] I mean the hex convert of the string or it may be this array:
 [104,101,108,108,111] = the decimal convert of the string "hello"?
 
Thank you for the answer

**Comment by tal987** [comment]
@marcosinigaglia Do you have any idea?

**Comment by Kevin-zyk** [comment]
I sent an array like [122] in the write method, but the format was not correct

**Comment by tal987** [comment]
@kevin-zyk hows your answer related to my question?

**Comment by marcosinigaglia** [comment]
Hi @tal987 , depends on you device protocol. 
( You can also write in hex directly [0x68,0x65,0x6c,0x6c,0x6f] )
