### ISSUE TITLE
Is there anyway to make this work on Background even after the app is killed?

### ISSUE THREAD

**Issue by sudharsan1988** [innoveit/react-native-ble-manager#49]
Hi, I am wondering is there anyway to make this library scans ble data on the Background even after the app is killed. I can see, it works only on the foreground for now. Thanks in advance!

**Comment by marcosinigaglia** [comment]
Hi, you need specific native code to handle the ble in background so is not possible to have a generic library.

**Comment by anton-aleksandrov** [comment]
@marcosinigaglia do you have an example? I understand, generally, how to implement this with `NativeModules` but there are quite a few details i need to discover yet.

**Comment by hidayatNgganteng** [comment]
You must add **UIBackgroundModes key** in info.plist and the value is array containing string _bluetooth-central_ and _bluetooth-peripheral_

allowing bluetooth behavior even in the background
