### ISSUE TITLE
The BOND_BONDED state event callback is not called?

### ISSUE THREAD

**Issue by fkhosrow** [innoveit/react-native-ble-manager#493]
### Version

Tell us which versions you are using:
- iOS/Android v.? Android
- react-native-ble-manager v.? latest
- re act-native v.? 0.55.4
 
### Steps to reproduce
1. Run an Android app.
2. Turn off a paired device.
3. Turn this device back on.
4. The App connects to this paired device by calling createBond() followed by connect(). 
5. The App at this point registers and listens to a NOTIFY characteristics on the paired device. **The paired device fails to start the read.** 

6. Restart the app but leave the paired device turned on.
7. The App connects to this paired device by calling createBond() followed by connect().
8. The App at this point registers and listens to a NOTIFY characteristics on the paired device. **The paired device is able to start the read and the notify callback is called. Success.**

I believe the reason the start read fails is that a BOND_BONDED event is sent after setNotify is complete. This messes the Bluetooth stack. 

### Expected Behavior
The callback that was set in createBond() would be called such that the App can listen to this event and resets the stack. 

### Actual behaviour
The callback that was set in createBond() in BleManager.java is not called for some reason?!! The App needs to listen to this event and restart read after actual bonding is successful.

See BleManager.java createBond and BroadcastReceiver calls

### Stack trace and console log
![logcat](https://user-images.githubusercontent.com/2480836/55285402-59bbc100-5340-11e9-84ca-09e2c700784b.png)

### Suggestion
Perhaps createBond can be renamed to requestBond?

### Suggested Fix
Call sendEvent in BroadcastReceiver to broadcast a successful bond in case createBond is never called and some other bluetooth functionality calls it. I was able to fix this here: d9c2e0b7d4b980b6acec4645ea13898921cfdcf7

**Comment by marcosinigaglia** [comment]
Hi, @fkhosrow  I don't have a device to test, if you think your commit is ok make a PR.

**Comment by fkhosrow** [comment]
Hi @marcosinigaglia no problem. I will test it some more on couple of phones and submit a PR this week.

**Comment by fkhosrow** [comment]
@marcosinigaglia I created a PR for this purpose. Thanks.
