### ISSUE TITLE
Unable to connect | Android v5

### ISSUE THREAD

**Issue by harshit275** [innoveit/react-native-ble-manager#499]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.1
- react-native v0.59.6
- Android v.5.0

### Expected behaviour

Device should connect with my BLE adapter and Android version 5.0 isn't a problem.
My code works perfectly fine with the Android version 6.0 and above. It is giving problem specifically with the version 5.

### Actual behaviour

Every time the connect function gets called it gives an unusual error "Unable to connect"
### Steps to reproduce

1. Firstly, I called the `BLEManager.start()` function
2. Then I ask for the paired peripherals using function `getBondedPeripherals()` on my Android 5 device and get a particular peripheral id from the paired devices.
3. Then I call the function `connect()` and pass the peripheral id to it but to my surprise it didn't connect and gave me this error "Unable to connect" every time.

In your git document its written specifically that your library will support Android v.19+ APIs but strangely Android 5 (20+ API) didn't give me the desired results, it unable to connect to the peripherals.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi, you have to debug on you phone.
