### ISSUE TITLE
react native v0.25.1

### ISSUE THREAD

**Issue by vlade2008** [innoveit/react-native-ble-manager#5]
![13407457_10204788343667662_504621125_n](https://cloud.githubusercontent.com/assets/13525454/15997300/f3f32b42-3164-11e6-972f-e472e2c06cb0.png)

**Comment by marcosinigaglia** [comment]
Hi, I think you miss the second parameter in scan method.

**Comment by vlade2008** [comment]
oh yeah! thank you so much .
 please update the example, thanks :D
