### ISSUE TITLE
didDiscoverCharacteristicsForService: Attempted to dereference null pointer

### ISSUE THREAD

**Issue by elliottkember** [innoveit/react-native-ble-manager#500]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.1
- react-native v0.57.1
- iOS/Android v12

### Expected behaviour

The application should not crash when a device is disconnected

### Actual behaviour

It seems to be that if I'm retrieving a characteristic for the connected BLE device, but the device is disconnected at the same time, it crashes with the above error.

Unfortunately it's very hard to reproduce this error - it usually happens after leaving the application open for an hour or two, but sometimes it can happen during normal usage.

### Steps to reproduce

1. Have device connected
2. Simultaneously power off the device while retrieving a characteristic
3. App (sometimes) crashes

### Stack trace and console log

Happens at BLEManager.m line 593 in `retrieveServices:(NSString *)deviceUUID services:(NSArray<NSString *> *)services callback:(nonnull RCTResponseSenderBlock)callback`:

`[retrieveServicesCallbacks setObject:callback forKey:[peripheral uuidAsString]];`

```2019-04-23 20:45:13.768647-0700 Soulmate 🐛[1158:761779] Service 4FAFC201-1FB5-459E-8FCC-C5C9C331914B <CBService: 0x281223cc0, isPrimary = YES, UUID = 4FAFC201-1FB5-459E-8FCC-C5C9C331914B>
2019-04-23 20:45:13.769748-0700 Soulmate 🐛[1158:761779] Characteristics For Service Discover
2019-04-23 20:45:13.771732-0700 Soulmate 🐛[1158:770057] retrieveServices (null)
2019-04-23 20:57:29.454065-0700 Soulmate 🐛[1158:771242] XPC connection interrupted
```

`Thread 550: EXC_BAD_ACCESS (code=1, address=0x3332363133354424)`

Also - *thank you* for this library! It's working great for us apart from this occasional crash. There's a chance I'm doing something wrong in my React Native code, but the full application crash is unexpected, so I suspect there's something happening under the hood that I can help diagnose and help work around.

**Comment by marcosinigaglia** [comment]
Hi @elliottkember , do you have the crash only on iOS?

**Comment by elliottkember** [comment]
@marcosinigaglia Hi! Yes I'm only building for iOS with this app.

**Comment by iradkot** [comment]
Hey, why was this close?
