### ISSUE TITLE
[Android only]  Lost connect promise resolve\reject after reboot phone

### ISSUE THREAD

**Issue by VitamineC** [innoveit/react-native-ble-manager#501]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.5.2
- react-native v0.55.4
- Android v.6, 7.1, 8.1

I try connect to device without scan, saving uuid in my asyncStorage. Everything work great. However after reboot my mobile phone, something went wrong. 
I don't get any connect promise resolve\reject. And I can connect to device only after starting scan process. 
I get this problem only on android, on ios all works great.

**Comment by marcosinigaglia** [comment]
Is not supported, you can try (https://stackoverflow.com/questions/25478827/how-to-connect-ble-device-without-scanning-android-4-3?rq=1) and make a PR.
