### ISSUE TITLE
sending long data in ios

### ISSUE THREAD

**Issue by amirhosein5858** [innoveit/react-native-ble-manager#509]
- react-native-ble-manager v6.6.4
- react-native v0.59.5
- iOS 11

can not send a 255 byte string data in ios without Response
i set max byte size to 255 but only 182 byte sent successfully,how i can send large  data...?

**Comment by marcosinigaglia** [comment]
Hi, it's a protocol limitation, split the data in smaller packet.

**Comment by amirhosein5858** [comment]
thank,i can you tell an example please? i cant find it any where...

**Comment by marcosinigaglia** [comment]
You have only to split the byte's string, is the receiver that have to handle the splitted data.
