### ISSUE TITLE
Scan Option

### ISSUE THREAD

**Issue by keyz23** [innoveit/react-native-ble-manager#510]
I guys i'm using this library for my Android Application.
I have a question. 
I need to connect to a particular device (actually two with a very similar name, one right and one left).
I would like to know if there is a way to connect directly to a device without considering all the others.
I saw that in the function:
```
BleManager.scan ([], 5, true)
             .then (results => {
```

the results variable returns all the devices, how do I get back only what interests me?
Thanks a lot.

**Comment by marcosinigaglia** [comment]
You can filter only by the service UUID, or you can connect directly to the peripheral id if you already saved it.

**Comment by keyz23** [comment]
So can I connect automatically only if I had connected to this device once before?

**Comment by marcosinigaglia** [comment]
Yes, to have the peripheral id you need to scan it one time.

**Comment by keyz23** [comment]
To be sure that I understand what you're telling me, if I know the name of the device, can't I make a connection automatically if I haven't made a manual connection before? (To be clear if first I don't physically click on the Connect button)

**Comment by marcosinigaglia** [comment]
To be precise: to connect you need the peripheral id, to have the peripheral id you need to scan the device at least one time.
