### ISSUE TITLE
write vs writeWithoutResponse

### ISSUE THREAD

**Issue by harshit275** [innoveit/react-native-ble-manager#511]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.1
- react-native v0.59.3
- Android v28.0.2

### Question

I really like to know that how methods `write()` and `writeWithoutResponse()` works. And how are they different from each other functionality wise. I mean in your module doc you did not mention it very clearly what different features these 2 provide.
As both the methods return Promise object in return then what is the other response that `write()` gives us that `writeWithoutResponse()` not.
I mean it would very nice if you give me some examples as to how and when use these methods.

**Comment by marcosinigaglia** [comment]
It's a protocol difference, `writeWithoutResponse` is faster because the peripheral that write doesn't wait the write confirmation from the other peripheral.
