### ISSUE TITLE
Fetching Accelerometer data from cc2650STK

### ISSUE THREAD

**Issue by faizaanshah** [innoveit/react-native-ble-manager#512]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.6.4
- react-native v0.59.8
- Android v.8.0

### Expected behaviour

Fetching accelerometer and gyroscope data continuously... 
I need to fetch accelerometer and gyroscope data continuously in my react native application from TI-Sensortag. I have these serives and characteristics::
             `var MoveMentServiceUUID = "f000aa80-0451-4000-b000-000000000000"`
              `var MoveMentCharUUID = "f000aa81-0451-4000-b000-000000000000";`
              `var MoveMentConfigUUID = "f000aa82-0451-4000-b000-000000000000";`
              `var MovMentPeriodUUID = "f000aa83-0451-4000-b000-000000000000";`
              `var MovMentNotifUUID ="00002902-0000-1000-8000-00805f9b34fb";`

Things work pretty fine for other services and characteristics, e.g. for Battery Status I have just a serviceUUID and a charUUID.
`var batteryServiceUUID = "180f";`
              `var batteryCharUUID = "2a19";`
              `setTimeout(()=>{`
                `BleManager.startNotification(peripheral.id, batteryServiceUUID,batteryCharUUID).then(()=>{`
                  `console.log("Battery Notification Started>>>>> on "+ peripheral.id);`
                  `setTimeout(()=>{`
                    `BleManager.read(peripheral.id,batteryServiceUUID,batteryCharUUID).then((batterySt)=>{`
                     ` console.log("Battery:"+batterySt);`
                    `});`
                  `},200);`
               ` })`
              `},200);`

### Actual behaviour

But for accelerometer I am pretty confuse, since there are 4 UUIDs and I don't want to get the data once but to fetch it continuously on sensors wakeup.
I am currently doing this:
`setTimeout(()=>{`
                `BleManager.startNotification(peripheral.id,MoveMentServiceUUID,MoveMentCharUUID).then(()=>{`
                  `console.log("Movement Notification started>>>> on "+ peripheral.id);`
                 `setTimeout(()=>{`
                    `BleManager.read(peripheral.id,MoveMentServiceUUID,MoveMentCharUUID).then((movData)=>{`
                    `console.log("Movement: "+movData);`
                 ` });`
                ` },200);`
               ` });`
             ` },300);`
### Steps to reproduce

1. Accelerometer data  only z_axis
2. Gyro data , all the axis

### Stack trace and console log

![image](https://user-images.githubusercontent.com/22859078/57839634-83418680-77e0-11e9-81a4-edf372f278ca.png)

```
```

**Comment by marcosinigaglia** [comment]
Hi, if you use notification you don't have to read the values but handle the BleManagerDidUpdateValueForCharacteristic event that fire every time the value change.
