### ISSUE TITLE
getConnectedPeripherals returning empty array

### ISSUE THREAD

**Issue by Mattimus333** [innoveit/react-native-ble-manager#514]
### Version
- react-native-ble-manager v6.6.4
- react-native v.56
- iOS/Android Android Version 9

### Expected behaviour

I'm expecting to see the connected peripheral being returned.  I connected a pair of airpods to the android device and when running the app expected getConnectedPeripherals to return the connected airpod.  

### Actual behaviour
Instead I am getting an empty array.  If I change the function to getBondedPeripherals I can see the airpods listed in that response.  Any idea what is going on?  Do I have to connect to the airpods via this package to see it in the response?    

```
```
Edit:  Doing some research and it seems like on Android you can't query for currently connected devices?  Can only do it by noting when devices are connected/disconnected?  Going to assume this is the reason, feel free to close this issue if I'm correct!

**Comment by marcosinigaglia** [comment]
Connected and bonded are different status, so I think is correct.
