### ISSUE TITLE
Connection and getConnected functions error

### ISSUE THREAD

**Issue by OzgunAkkoyun** [innoveit/react-native-ble-manager#521]
### Version

Tell us which versions you are using:

- react-native-ble-manager: "^6.6.6"
- react-native : "0.59.9"

### Expected behaviour

I trying to only specific device which is bluetooth headphone,but i cant get any connected device or connect this device 

### Actual behaviour

its giving me error when i get connected devices "No connected peripherals" or connect function with mac adress. Other bounded functions all work fine.

**Comment by marcosinigaglia** [comment]
Hi, I don't think you can get the connection of a bounded device on iOS, on Android use that functions..

**Comment by OzgunAkkoyun** [comment]
Im using in android but i cant get any response in this functions.

**Comment by rakshitbharat** [comment]
global.isBLEManagerInitialized = false;
if (!global.isBLEManagerInitialized) {
  BleManager.start({showAlert: false}).then(() => {
    console.error('Module initialized');
    global.isBLEManagerInitialized = true;
  });
}

add this in index.js and make sure BleManager.start will never be called again anywhere in app
