### ISSUE TITLE
peripheral json returns with advertising: {serviceUUIDs: Array(0), txPowerLevel: -2147483648, isConnectable: true, manufacturerData: {…}} id: "71:3D:C6:14:D9:D6" name: null rssi: -86  always name is null. may I know why ?

### ISSUE THREAD

**Issue by mkhan90** [innoveit/react-native-ble-manager#524]
### Version

Tell us which versions you are using:

- react-native-ble-manager v?.?.?
- react-native v?.?
- iOS/Android v.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by Robiullah2244** [comment]
Same issue
