### ISSUE TITLE
Ios ask to turn on bluetooth on app startup

### ISSUE THREAD

**Issue by lukabers** [innoveit/react-native-ble-manager#53]
Hello,
Everytime the app is started it asks to turn on bluetooth is there a way to disable this or to ask only when the component mount?

Thanks

**Comment by marcosinigaglia** [comment]
Hi, you can can try to move the CBCentralManager init in a specific method and test if there are problems in the module, I thinks it's a dangerous change.

**Comment by marcosinigaglia** [comment]
Solved with start method on [v2.0.0](https://github.com/innoveit/react-native-ble-manager/releases/tag/v2.0.0)
