### ISSUE TITLE
Continuous write failure?

### ISSUE THREAD

**Issue by 1442916418** [innoveit/react-native-ble-manager#531]
Why Write Failure?

```
   write(data, index = 0) {
        data = stringToBytes(data);

        return new Promise((resolve, reject) => {
            BleManager.write(this.peripheralId, this.nofityServiceUUID[index], this.nofityCharacteristicUUID[index], data)
                .then((result) => {
                    console.log('success: ', result);
                    resolve();
                })
                .catch((error) => {
                    console.log('fail: ', error);
                    reject(error);
                });
        });
    
```

Console Printing:
Write failed

What's wrong? Please answer, thank you!

**Comment by BaloMueller** [comment]
Please use the template to submit issues. What Version are you using? iOS or Android? 

Shouldn't the "Console Printing" be: "fail: Write failed"? Or is it just "Write failed"?

Have you executed retrieveServices() before for this peripheral? https://github.com/innoveit/react-native-ble-manager#retrieveservicesperipheralid-serviceuuids

**Comment by 1442916418** [comment]
Android,retrieveServices() executed.

Now there are new problems.

How to distinguish whether the currently connected Bluetooth UUID is readable or writable? Do you have any documents to refer to?
