### ISSUE TITLE
getConnectedPeripherals return empty array if the serviceUUIDs params is []

### ISSUE THREAD

**Issue by haibinyu** [innoveit/react-native-ble-manager#54]
when  I call getConnectedPeripherals with serviceUUIDs = [], the result is empty, but if I call it with serviceUUIDs = ['one service uuid in connected peripherals], the result is right.
is the serviceUUIDs required to getConnectedPeripherals?

**Comment by marcosinigaglia** [comment]
Hi, in Android or iOS?

**Comment by haibinyu** [comment]
@marcosinigaglia iOS

**Comment by marcosinigaglia** [comment]
Try version 1.4.2

**Comment by kevyu** [comment]
@thanks, I will try tommrow.

**Comment by Abhinandan-Kushwaha** [comment]
Still facing the same issue

**Comment by longnguyenITG** [comment]
i have same issue, but use getBondedPeripherals get success list connected peripherls but have'nt uuids, what different between getBondedPeripherals and getConnectedPeripherals?

**Comment by SuhitAgarwal** [comment]
This still seems to be an issue @marcosinigaglia. It was working fine until a few days ago. I can't seem to find issues anywhere else in my code. i'm just not getting any peripherals when I run the `BleManager.getConnectedPeripherals([])`. 

Here's my console.log from running that: `{"_h": 0, "_i": 0, "_j": null, "_k": null}`
