### ISSUE TITLE
iOS scanning not working..

### ISSUE THREAD

**Issue by shilpa108** [innoveit/react-native-ble-manager#540]
### Version

Tell us which versions you are using:

- react-native-ble-manager v?.?.?
- react-native v?.?
- iOS/Android v.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by shilpa108** [comment]
I am able to Start Ble manger , start and stop scanning. but it is not giving any scanning result in iOS. On android it is working fine.Please help

**Comment by marcosinigaglia** [comment]
Check the installation and the app permission.
