### ISSUE TITLE
Unable to get response after write please help

### ISSUE THREAD

**Issue by sundeep5165293** [innoveit/react-native-ble-manager#541]
I am able to make the connection to BLE and able to write after notification is active but still getting no response, please suggest how to receive response from BLE once the write is done.

**Comment by sundeep5165293** [comment]
please provide some examples

**Comment by sundeep5165293** [comment]
I have resolved this issue because I was not using \r\n at the end of UART command.

**Comment by yoonachen** [comment]
Is there any code snippest? Thanks!
