### ISSUE TITLE
Cannot make my AppRegistry point to example component

### ISSUE THREAD

**Issue by zdeluna** [innoveit/react-native-ble-manager#543]
### Version

Tell us which versions you are using:

- react-native-ble-manager 6.6.6
- react-native 0.60.5
- iOS/Android iOS - iPhone X 12.4

### Expected behaviour

I was expecting the example project to work on a newly created app

### Actual behaviour
I am getting an error on the simulator that says "Native module cannot be null"

### Steps to reproduce

1) I created a project using react-native init and then ran
```
npm i --save react-native-ble-manager
react-native link react-native-ble-manager
```

2) Then I changed the App.js file to 

```
// in your index.ios.js or index.android.js
import React, { Component } from 'react';
import {
  AppRegistry,
} from 'react-native';
import App from 'react-native-ble-manager/example/App' //<-- simply point to the example js!

AppRegistry.registerComponent('MyAwesomeApp', () => App);
```

3) Then ran ```react-native run-ios```

### Stack trace and console log
![Screen Shot 2019-08-22 at 4 28 39 PM](https://user-images.githubusercontent.com/1248972/63551158-fb16ff80-c4f9-11e9-82e7-4ae7f08571d8.png)

**Comment by marcosinigaglia** [comment]
The module is not working on the Simulator, you need to install the module in the xcode project, follow the installation.
