### ISSUE TITLE
[REQUEST FEATURE] Could please release a version for androidx ？

### ISSUE THREAD

**Issue by dubiao** [innoveit/react-native-ble-manager#545]
### Version 6.6.8

Could please release a version for androidx ？
When my project enabled androidx and jetpack, build thorws an error. I should modify the file who use support package to androidx.support . But it's not good for CI/DI for build project automatically.

Thank you.

**Comment by stockrel** [comment]
+1

**Comment by marcosinigaglia** [comment]
Related to https://github.com/innoveit/react-native-ble-manager/issues/548
