### ISSUE TITLE
problem in introduction

### ISSUE THREAD

**Issue by ysjiang4869** [innoveit/react-native-ble-manager#56]
use as follow when use in android
protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
                new BleManagerPackage(this)
        );
    }

**Comment by marcosinigaglia** [comment]
Hi, witch version of RN do you use?

**Comment by ysjiang4869** [comment]
0.28.0， but in your  BleManagerPackage class the constructor need params Activity activityContext

**Comment by marcosinigaglia** [comment]
Sorry but the library dosn't support RN 0.28

**Comment by ysjiang4869** [comment]
which version is supported? i use 0.27 before and it can work well

**Comment by marcosinigaglia** [comment]
You can use [v.0.0.14](https://github.com/innoveit/react-native-ble-manager/releases/tag/v0.0.14), after this version i think works only with RN 0.29+

**Comment by ysjiang4869** [comment]
ok,thanks, i still use v0.0.14 so there is no wrong
