### ISSUE TITLE
Get services and characteristic IDs

### ISSUE THREAD

**Issue by bwaiter-official** [innoveit/react-native-ble-manager#566]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.7.0
- react-native v0.61
- iOS/Android v.8.1.0

### Expected behaviour

Actually, my post is not about a bug but a question.

How do I know what service and characteristic to use with my printer? I logged the properties of my printer and found one service and characteristic that seemed to work (printed the logs on console but didn't print anything in the printer). Is there a more straight forward way to do it?

In the end, it didn't print on the printer, but it printed the logs in my console. Is the test supposed to communicate with the printer and actually print, or is it only to log?

Thanks.

```
```

**Comment by marcosinigaglia** [comment]
Hi, you need to find the printer documentation.
