### ISSUE TITLE
Example lacking instructions

### ISSUE THREAD

**Issue by Cacowned** [innoveit/react-native-ble-manager#57]
Hi,

The example in the readme doesn't show how to import/require the ble-manager.

I tried

`var BleManager = require('react-native-ble-manager');`

and

`import { BleManager } from 'react-native-ble-manager';`

but both result in an undefined BleManager.

**Comment by marcosinigaglia** [comment]
Hi, there is the **Install** section in [README](https://github.com/innoveit/react-native-ble-manager/blob/master/README.md)

**Comment by Cacowned** [comment]
@marcosinigaglia Yes, there is. But it only tells me how include it to compile with the android or iOS native stuff, but not how to use it on the react-native side, the javascript part.

**Comment by marcosinigaglia** [comment]
Try
`import BleManager from 'react-native-ble-manager';`

**Comment by Cacowned** [comment]
@marcosinigaglia Ok, that works, thanks!
