### ISSUE TITLE
Make isConnectable working for API 26 and up

### ISSUE THREAD

**Issue by juliansteenbakker** [innoveit/react-native-ble-manager#585]
Right now the isConnectable flag is set to true for any device found in Android.
`advertising.putBoolean("isConnectable", true);`

[However, since API 26 (Android 8) it is possible to call isConnectable on the scanresult, which returns a boolean](https://developer.android.com/reference/android/bluetooth/le/ScanResult.html#isConnectable())

Is it possible to check if API version is 26 or up, and pass the value from the scanrecord?

**Comment by marcosinigaglia** [comment]
Hi @juliansteenbakker , yes a PR is welcome

**Comment by juliansteenbakker** [comment]
Hello @marcosinigaglia , See https://github.com/innoveit/react-native-ble-manager/pull/589

**Comment by marcosinigaglia** [comment]
Hi @juliansteenbakker , the new release have the PR
