### ISSUE TITLE
There is no characteristic data after connecting a BLE device

### ISSUE THREAD

**Issue by ttdat89** [innoveit/react-native-ble-manager#59]
After discovering/connecting a peripheral, there is no characteristic in returned object.

**Comment by marcosinigaglia** [comment]
Hi, can you give more information?

**Comment by ttdat89** [comment]
Hi, actually i want to ask how to get characteristic UUID.
I saw that you have connectCallbacks that return characteristic, but i cannot get returned data somehow

**Comment by marcosinigaglia** [comment]
I thinks the device has no services, the connect callback is called after the services discovery. You have to use BleManagerConnectPeripheral event.

**Comment by BigPun86** [comment]
+1 No idea where to obtain the characteristicUUID

**Comment by marcosinigaglia** [comment]
Hi, in release 2.2.0 you have the peripherals services and characteristics in connect callback. I will change the docs soon.

**Comment by BigPun86** [comment]
Tried it, but unfortunately it doesn´t work .... Tried on real device of course :P

![screen shot 2016-10-13 at 14 24 58](https://cloud.githubusercontent.com/assets/7880624/19348982/fcc78d8e-9150-11e6-9e7d-207207ce3583.png)

**Comment by marcosinigaglia** [comment]
Try 2.2.1

**Comment by BigPun86** [comment]
Almost :P This is my crash report ...

<img width="652" alt="screen shot 2016-10-14 at 10 19 37" src="https://cloud.githubusercontent.com/assets/7880624/19381544/6106091e-91fc-11e6-98a5-fafb5d456c16.png">
<img width="762" alt="screen shot 2016-10-14 at 10 34 22" src="https://cloud.githubusercontent.com/assets/7880624/19381543/60fe6f56-91fc-11e6-96f6-af597e19f475.png">
<img width="875" alt="screen shot 2016-10-14 at 10 34 47" src="https://cloud.githubusercontent.com/assets/7880624/19381542/60f8ecf2-91fc-11e6-9e0b-c7755d4d8031.png">

**Comment by marcosinigaglia** [comment]
Fix in 2.2.3, sorry.

**Comment by BigPun86** [comment]
Nice. It is getting better :D But i get now the error: Invalid UUID: 1800. I think the native java part can´t handle this kind of string?!

**Comment by marcosinigaglia** [comment]
The services is a UUID, i never tried this format, do you have the same problem in ios?

**Comment by BigPun86** [comment]
Well i have an other UUID which is "180A" as a service. But this works on iOS. On Android it crashes when i use this kind of UUID -> "1800"... How does your "common" UUID looks like?

**Comment by marcosinigaglia** [comment]
Can you try this change in android?
```java
@ReactMethod
	public void read(String deviceUUID, String serviceUUID, String characteristicUUID, Callback callback) {
		Log.d(LOG_TAG, "Read from: " + deviceUUID);
		Peripheral peripheral = peripherals.get(deviceUUID);
		if (peripheral != null){
			peripheral.read(ParcelUuid.fromString(serviceUUID).getUuid(), UUID.fromString(characteristicUUID), callback);
		} else
			callback.invoke("Peripheral not found", null);
	}
```

**Comment by joshuar500** [comment]
@marcosinigaglia @BigPun86 I'm having the same issue. On iOS it works fine. On Android, it says 'Invalid UUID: ED00'. Using the most recent version of ble-manager with the same code posted above.

**Comment by johneo** [comment]
I am having a similar issue with version 2.4.3. I get back device ID in this format `20:91:48:2A:69:20` rather than the usual UUID format with the dashes, which iOS code gets back when discovering the devices. Has anyone else run into this issue?

**Comment by ibenben** [comment]
I'm having the same issue.
version:` "react-native-ble-manager": "^4.0.0",`
My code:
` //A peripheral was connected.
	    this.BleManagerConnectPeripheralListener = NativeAppEventEmitter.addListener('BleManagerConnectPeripheral', (args) => {
		    console.log('BleManagerConnectPeripheral:', args);
	    });`

` connect(id) {
        return new Promise( (resolve, reject) =>{
            BleManager.connect(id)
                .then((peripheralInfo) => {
                    console.log('Connected peripheralInfo: ', peripheralInfo);
                    resolve(peripheralInfo);
                })
                .catch((error) => {
                    console.log('Connected error:',error);
                    reject(error);
                });
        });
    }
`
log:
`I/ReactNativeJS( 7024): 'BleManagerDiscoverPeripheral:', { rssi: -47,
I/ReactNativeJS( 7024):   name: 'Qianshan01',
I/ReactNativeJS( 7024):   id: '05:04:03:02:01:00',
I/ReactNativeJS( 7024):   advertising:
I/ReactNativeJS( 7024):    { CDVType: 'ArrayBuffer',
I/ReactNativeJS( 7024):      data: 'AgEFAwMSGAsJUWlhbnNoYW4wMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=' } }
I/ReactNativeJS( 7024): Scan stopped
I/ReactNativeJS( 7024): 'Connected peripheralInfo: ', { characteristics: [],
I/ReactNativeJS( 7024):   services: [],
I/ReactNativeJS( 7024):   rssi: -47,
I/ReactNativeJS( 7024):   advertising:
I/ReactNativeJS( 7024):    { data: 'AgEFAwMSGAsJUWlhbnNoYW4wMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
I/ReactNativeJS( 7024):      CDVType: 'ArrayBuffer' },
I/ReactNativeJS( 7024):   id: '05:04:03:02:01:00',
I/ReactNativeJS( 7024):   name: 'Qianshan01' }
I/ReactNativeJS( 7024): Notification error
I/ReactNativeJS( 7024): 'BleManagerConnectPeripheral:', { peripheral: '05:04:03:02:01:00' }
`
![image](https://cloud.githubusercontent.com/assets/13758704/26432865/6b8af540-4131-11e7-9e82-23ac4a187872.png)

**Comment by marcosinigaglia** [comment]
Hi @ibenben , you need to call retrieveServices method after the connection.

**Comment by ibenben** [comment]
@marcosinigaglia Thanks

**Comment by ibenben** [comment]
Hi @marcosinigaglia ,the app run pefect on android 5.0 but the other android version is the same issue like 6.0.1 when call retrieveServices method after the connection.

**Comment by marcosinigaglia** [comment]
Try to use the `forceLegacy` flag.

**Comment by batkhai290499** [comment]
same issue @@. i using version 4.0.0 . i can not het servicesID and characteristicsID. please help. i was use retrieveServices, forceLagacy. nothing change
