### ISSUE TITLE
format manufactured data

### ISSUE THREAD

**Issue by Gueoff** [innoveit/react-native-ble-manager#592]
Hello!

Scan function return different informations for manufacturerData field.
In ios we have directly the company id instead of android where we need to search through the manufacturerData array to get it. Is an implementation of the getManufacturerSpecificData function (android only) ? 

https://developer.android.com/reference/android/bluetooth/le/ScanRecord.html#getManufacturerSpecificData()

We can also do it in JS by searching for informations :
https://www.silabs.com/community/wireless/bluetooth/knowledge-base.entry.html/2017/11/14/bluetooth_advertisin-zCHh

**Comment by marcosinigaglia** [comment]
Hi @Gueoff , you can make a PR with the specific method for Android.
