### ISSUE TITLE
My device can be discovered too?

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#599]
hey I just wondering if its possible that while im scanning my device can be discovered by other scanner?
I mean other device can see my device around (android and iPhone)

Thank you

**Comment by marcosinigaglia** [comment]
The short answer is no https://github.com/innoveit/react-native-ble-manager/issues/578

**Comment by tal987** [comment]
@marcosinigaglia  do you know if there's any library on react native who support it?
every library which saying only for Bluetooth LE devices will not work?
