### ISSUE TITLE
get  Could not find peripheral XXXX error when disconnect a peripheral

### ISSUE THREAD

**Issue by haibinyu** [innoveit/react-native-ble-manager#60]
when I disconnect a peripheral by id which is from getConnectedPeripherals, I got error: 
```
Could not find peripheral XXXX
```

**Comment by marcosinigaglia** [comment]
Are you sure the id match? Do you connect directly to the peripheral or after a scan?

**Comment by haibinyu** [comment]
yes， the id is match, maybe I misunderstand the ble connection, in my scenario, the ble is connected by other app, and I want to disconnect it in my app.

**Comment by marcosinigaglia** [comment]
You can't disconnect another app connection.

**Comment by haibinyu** [comment]
@marcosinigaglia got it, thanks.
