### ISSUE TITLE
How to advertise?

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#600]
Hi, is that possible to advertise? (that other device can discover my device)
if not can you please explain me why? do you think there are other libraries which able to do that or we can't do it right now with react native?

Thank you

**Comment by marcosinigaglia** [comment]
Hi @ tal987, the Bluetooth Low Energy protocol is a subset of Bluetooth, you cannot do the same things, there is a lot of information please look for them.

**Comment by tal987** [comment]
@marcosinigaglia  I understand but is that possible at all to do that in react native?
