### ISSUE TITLE
what kind of devices can be discovered?

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#601]
hey I was wondering what kind of devices can be discovered on scanning?

Can iPhone and android mobile device can be discovered? I couldn't find iPhones and android mobile devices while I scanned. I could only find sensor, computers, headphones...

Can you explain me why?

**Comment by marcosinigaglia** [comment]
You can discover all BLE devices, smartphone aren't BLE device.
https://www.novelbits.io/basics-bluetooth-low-energy/
