### ISSUE TITLE
Discovery doesn't work between different OS [ANDROID<->IOS]

### ISSUE THREAD

**Issue by simonstyleur** [innoveit/react-native-ble-manager#607]
### Version

Tell us which versions you are using:

- react-native-ble-manager 7.2.0
- react-native 0.62.0
- iOS/Android [IOS 13] [ANDROID V9] 

### Expected behaviour
Find Android Devices when i start scanning from IOS device (and vice versa)

### Actual behaviour

Nothing happend

### Steps to reproduce

i tried with the Example available on this repo

**Comment by marcosinigaglia** [comment]
https://github.com/innoveit/react-native-ble-manager/issues/601
