### ISSUE TITLE
Wrong hexadecimal Data Read 

### ISSUE THREAD

**Issue by khaditafzka** [innoveit/react-native-ble-manager#608]
hello! Sorry for the mistakes i am not English-speaker.
i'm trying to read some data from a box installed on a vehicle and i notice that i don't have good hexadecimal value before converting.
Can Someone help me?
here is my function:

    async getDataFromBox(peripheral){
   
    try{
    let peripherals = this.state.peripherals;
    let p = peripherals.get(peripheral.id);
    const peripheralInfo = await BleManager.retrieveServices(peripheral.id);
    console.log("retrieveServices", peripheralInfo);
   
    while(p.connected = true) {

      await BleManager.read(peripheral.id, service, engineSpeed).then(
        (engineS) => {
          
          
          // Success code
          
          console.log('engineSpeed: '+ engineS)

          this.setState({engineSpeedData : parseInt(engineS, 16)});
        }
        )

      await BleManager.read(peripheral.id, service, brake).then(
        (bra) => {
          // Success code
          console.log('brake: '+ bra )
          this.setState({brakeData : parseInt(bra, 16)});
        }
        )

        
      if (p.connected = false){
        break
        
      }
    }
    console.log("finished");
   
     }catch(error){
       console.log(error)
     }
     }

**Comment by fukemy** [comment]
hi, how did u converted data to int?
