### ISSUE TITLE
get Could not find peripheral XXXX error when connect a peripheral

### ISSUE THREAD

**Issue by haibinyu** [innoveit/react-native-ble-manager#61]
react-native-ble-manager version: 2.0.0, same in 1.4.0

like #60 , when I connect a peripheral by id that getting from getConnectedPeripherals, I got error 

```
Could not find peripheral XXXX
```

I check the code and find that it checks if the id is in the discovered peripherals before connecting to it, but in my scenario, the scan operation is skipped if I find the peripheral in the connected peripherals.

As apple recommend at https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW9

when reconnecting a peripheral, it is better to get connected peripherals to check if the peripheral is connected before scan.

**Comment by phoenecke** [comment]
I also ran into this.  `getConnectedPeripherals' needs to do `[peripherals addObject:peripheral];` or something.

**Comment by marcosinigaglia** [comment]
Fixed in 2.3.0
