### ISSUE TITLE
#Questions:  Communication between phones

### ISSUE THREAD

**Issue by BlackCod3** [innoveit/react-native-ble-manager#610]
Hi, 
First of all, thanks for this great lib and clear doc.

I'm very new to BLE APIs and capabilities. I want to achieve a "simple" thing. Let's say I'm developing the APP-X. I want to be able to scan other phone around me, with APP-X installed (exactly like this app here https://www.tracetogether.gov.sg/ ) . So I don't want to establish a connection. I just want to scan and filter the wanted devices via a "simple" metadata (advertising data ? specific for my app) within the signal emitted by the concerned phones. I'm stuck because Idk how to "emit" that custom signal... 

Can you please help me to find a way to do this in RN ?

Many thanks 🙏

**Comment by marcosinigaglia** [comment]
Is not possible.
https://github.com/innoveit/react-native-ble-manager/issues/607
