### ISSUE TITLE
searching only one device 

### ISSUE THREAD

**Issue by syedjawadhashmi** [innoveit/react-native-ble-manager#618]
Hi, 
I have integrated  this libraray successfully and done all its configuration but its searching only one device and its not connecting at all , please let me know the issues i am facing

**Comment by nahidmbstu** [comment]
same here

**Comment by marcosinigaglia** [comment]
How many device are in the BLE range? Do you have an error during the connection, what is the device are you trying to connect?

**Comment by syedjawadhashmi** [comment]
only 1 device is scan which is my pc bluetooth other bluetooth devices are not scan in the app but in mobile bluetooth setting showing all the devices and connect successful but in the app using this module bluetooth scanning and connection is not working

**Comment by viratbhatt** [comment]
For me it shows bunch of random Bluetooth devices but my Other devices are not visible in the scan

**Comment by kkureli** [comment]
> For me it shows bunch of random Bluetooth devices but my Other devices are not visible in the scan
same
