### ISSUE TITLE
Can i list the peripherals and get the and then get data from a device?

### ISSUE THREAD

**Issue by gvaldatti** [innoveit/react-native-ble-manager#623]
I'm developing an application to communicate with mi band's, but I can't connect using the UUID (only by MAC address) I would like to list the devices so I can get the MAC address and use it to connect.

**Comment by marcosinigaglia** [comment]
Hi, you can't use directly the MAC address to connect to a device.

**Comment by isThereAnyF-ingNameAvailable** [comment]
what are you talking about?
handleDiscoverPeripheral(peripheral){
  BleManager.connect(peripheral.id)
}
works just fine. peripheral.id is MAC address.
