### ISSUE TITLE
Android 10 Bluetooth cannot be searched ?

### ISSUE THREAD

**Issue by Lizhooh** [innoveit/react-native-ble-manager#625]
### Version

Tell us which versions you are using:

- react-native-ble-manager latest
- react-native v0.60.2
- iOS/Android v10

**Comment by marcosinigaglia** [comment]
Hi, you have to debug in your device.

**Comment by qsayeed** [comment]
For Android 10, you need to give both permission  **ACCESS_FINE_LOCATION** and **ACCESS_COARSE_LOCATION**.

**Comment by sasurau4** [comment]
FIY: This link is helpful for users met this issue.
https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions

**Comment by anwarhamr** [comment]
Possible related https://github.com/innoveit/react-native-ble-manager/issues/647 I have made the recommended change listed here but didn't help me.

**Comment by Theofilos-Chamalis** [comment]
I had the same issue and adding `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` in the AndroidManifest.xml file as @qsayeed mentioned has solved the issue for me.

**Comment by anwarhamr** [comment]
> I had the same issue and adding `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` in the AndroidManifest.xml file as @qsayeed mentioned has solved the issue for me.

That change did not work for me.  Still not getting scan results.

**Comment by kapernikxd** [comment]
i have  this code in AndroidManifest.xml 
'
	<uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
'

But it still doesn't work in Android 10 qp1a.

**Comment by kapernikxd** [comment]
it will be solution for me https://github.com/Polidea/react-native-ble-plx/issues/730

**Comment by WookieFPV** [comment]
you have to request the permission "android.permission.ACCESS_FINE_LOCATION" and have it in the AndroidManifest.xml file.
This fixed the issue for me

**Comment by WookieFPV** [comment]
@kapernikxd do you check and request the ACCESS_FINE_LOCATION permission at runtime?
You need this for Android 10.
(You don't have to request ACCESS_COARSE_LOCATION if you have ACCESS_FINE_LOCATION)
