### ISSUE TITLE
handle discovered connection in two different ways

### ISSUE THREAD

**Issue by tal987** [innoveit/react-native-ble-manager#627]
hey, I have one component to handle ble, I would like to use the handler that handle with discovered devices in two different ways depends who called the handler.

ill try to explain by example:

   `class gatewayBLE {
    constructor() {
        bleManagerEmitter.addListener('BleManagerDiscoverPeripheral', this.handleDiscoverPeripheral1);
        bleManagerEmitter.addListener('BleManagerDiscoverPeripheral', this.handleDiscoverPeripheral2);
        bleManagerEmitter.addListener('BleManagerStopScan', this.handleStopScan);
        bleManagerEmitter.addListener('BleManagerDisconnectPeripheral', this.handleDisconnectedPeripheral);
        bleManagerEmitter.addListener('BleManagerDidUpdateValueForCharacteristic', this.handleUpdateValueForCharacteristic);
    }
}
`

I would like that class A will use this.handleDiscoverPeripheral1 and class B will use this.handleDiscoverPeripheral2.
is there any option to do that?
Thank you

**Comment by marcosinigaglia** [comment]
Hi, this is not a library issue.
