### ISSUE TITLE
No way to increase write() max byte size? (trying to implement OTA Update for device)

### ISSUE THREAD

**Issue by NeilMcGuiness** [innoveit/react-native-ble-manager#629]
### Version

Tell us which versions you are using:

- react-native-ble-manager v6.7.0
- react-native v61.4
EDIT: Android only (larger byte sizes work on iOS)

### Problem

I suppose this is a feature request of a kind, but max write size of 20 seems very small doesn't it?

I am trying to develop Over The Air update functionality for my app whereby i can stream a hex file (~ 700 kb) to my device in order to update the firmware, however this will take a long time being limited to 20 bytes at a time.

Is there no way to increase this 20 byte limit? I'm fairly sure the cypress app (compatible with the Peripheral device we're using) sends larger chunks of data much quicker to do OTA updating.

If it's possible to adjust this in the source code, just a point in the right direction would be very much appreciated.

Thanks in advanced.

**Comment by marcosinigaglia** [comment]
Hi, use [requestMTU](https://github.com/innoveit/react-native-ble-manager#requestmtuperipheralid-mtu-android-only-api-21)

**Comment by NeilMcGuiness** [comment]
Yes I found this today, my mistake, apologies! I'll close this now.
