### ISSUE TITLE
reportDelay isNull

### ISSUE THREAD

**Issue by MK3690** [innoveit/react-native-ble-manager#634]
### Version

- react-native-ble-manager 7.2.0
- react-native 0.62.2

![Screenshot_20200604-204734](https://user-images.githubusercontent.com/31363109/83775599-c3ea9700-a6a4-11ea-806b-c9580bf0c1f4.png)

**Comment by marcosinigaglia** [comment]
Are you sure that you have the last version? https://github.com/innoveit/react-native-ble-manager/commit/ee815ff11c066bbb45bb8e676bbeeee5fef13999

**Comment by MK3690** [comment]
Thank You @marcosinigaglia.

This solve my issue :- 

 if (scanningOptions.reportDelay == null) {
        scanningOptions.reportDelay = 0;
      }
