### ISSUE TITLE
BleManager.enableBluetooth() crashes on Android

### ISSUE THREAD

**Issue by BigPun86** [innoveit/react-native-ble-manager#64]
Hey there, i am trying to use enableBluetooth() on Android on a real device and it always crashes. 

My stacktrace: 

![screen shot 2016-10-06 at 16 51 15](https://cloud.githubusercontent.com/assets/7880624/19157290/21f28d82-8be5-11e6-929b-78021c579195.png)

Any hints on this how to fix it?

**Comment by marcosinigaglia** [comment]
Hi, I can't test on real device now, try replace the enable method with:
```java
	@ReactMethod
	public void enableBluetooth(Callback callback) {
		if (getBluetoothAdapter() == null) {
			Log.d(LOG_TAG, "No bluetooth support");
			callback.invoke("No bluetooth support");
			return;
		}
		if (!getBluetoothAdapter().isEnabled()) {
			enableBluetoothCallback = callback;
			Intent intentEnable = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
			getCurrentActivity().startActivityForResult(intentEnable, ENABLE_REQUEST);
			callback.invoke();
		} else
			callback.invoke();
	}
```

**Comment by BigPun86** [comment]
Nice! Works better now. Atleast it doesn´t crash as soon as i call the function but unfortunately it crashes as soon as i abort the dialog, i deny the dialog or after i have connected to bluetooth.

**"The callback enableBluetooth() exists in module BleManager, but only one callback may be registered to a function in a native module."**

**Comment by marcosinigaglia** [comment]
Hi, version [2.1.3](https://github.com/innoveit/react-native-ble-manager/releases/tag/v2.1.3) fix the error.

**Comment by ankushShetty1993** [comment]
App still crashes on Android when clicked on deny or enable(verison- 7.4.1)
