### ISSUE TITLE
Can't get a notification after recording data

### ISSUE THREAD

**Issue by nmikhaylovskiy** [innoveit/react-native-ble-manager#642]
### Version

Tell us which versions you are using:

react-native-ble-manager v7.2.0
react-native v0.62.2
Android v9

### Expected behaviour

I hope to get a response on the record

### Actual behaviour

I don't get an answer

### Steps to reproduce

1. connect
2. retrieveServices
3. startNotification
4. NativeAppEventEmitter.addListener('BleManagerDidUpdateValueForCharacteristic')
5. write

Output after retrieveServices is:

> [{"characteristic": "2a00", "properties": {"Read": "Read"}, "service": "1800"}, 
> {"characteristic": "2a01", "properties": {"Read": "Read"}, "service": "1800"}, 
> {"characteristic": "2a02", "properties": {"Read": "Read"}, "service": "1800"}, 
> {"characteristic": "2a04", "properties": {"Read": "Read"}, "service": "1800"}, 
> {"characteristic": "2a05", "descriptors": [[Object]], "properties": {"Indicate": "Indicate"}, "service": "1801"}, 
> {"characteristic": "ffe1", "descriptors": [[Object]], "properties": {"Notify": "Notify", "Write": "Write", "WriteWithoutResponse": "WriteWithoutResponse"}, "service": "ffe0"}, 
> {"characteristic": "ffe2", "properties": {"Write": "Write", "WriteWithoutResponse": "WriteWithoutResponse"}, "service": "ffe0"}]

I send a command to ffe0 ffe1 and hope to get a response, but it doesn't come.

I use the following code

```
await BleManager.connect(peripheral)
    .then(() => {
        console.log('Connect done');
    })
    .catch((error) => {
        console.log("Connected error", error);
    });
await BleManager.retrieveServices(peripheral)
    .then((peripheral) => {
        console.log("get retrieveServices");
    })
    .catch((error) => {
        console.log("retrieveServices error", error);
    });
setTimeout(function() {
    BleManager.startNotification(peripheral, service, characteristic).then(() => {
        console.log('SUBSCRIBING')
        NativeAppEventEmitter.addListener('BleManagerDidUpdateValueForCharacteristic', function(data) {
            console.log('RESULT FROM NOTIFICATION')
            console.log(data)
        });
        setTimeout(function() {
            console.log("write")
            BleManager.write(peripheral, service, characteristic, data)
                .then(() => {
                    console.log('Write: ' + data);
                })
                .catch((error) => {
                    console.log("error", error);
                });
        }, 3000);
    }).catch((error) => {
        console.log(error)
    });
}, 3000);
```

I call the function like this:
```
const data = stringToBytes(":010600000000F9\r\n");
this.connectAndPrepareRead("19:11:07:09:21:0D", "ffe0", "ffe1", data)
```

The command is successfully written on the device, I can see it by changing the device, but I can't get a response. 

Changing characteristics I can't read because my characteristic has the Notify property but doesn't have the Read property.

How i can get answer?

P.s  The output looks like this, but I never get the console.log('RESULT FROM NOTIFICATION') line

[Tue Jun 23 2020 16:20:35.710]  LOG      Connect done
[Tue Jun 23 2020 16:20:35.730]  LOG      get retrieveServices
[Tue Jun 23 2020 16:20:38.832]  LOG      SUBSCRIBING
[Tue Jun 23 2020 16:20:41.837]  LOG      write
[Tue Jun 23 2020 16:20:41.899]  LOG      Write: 58,48,49,48,54,48,48,48,48,48,48,48,49,70,56,13,10

**Comment by anwarhamr** [comment]
Do you know for sure that the value of the characteristic has been changed?  To test this connect, read the char you are going to change then read it again after you successfully write.  See if the values are what you think.  If the value does not change you will not get a notification; like if the value when you connect is 50 and your write 50 you will not get notified.
