### ISSUE TITLE
NativeModules.BleManager returns null

### ISSUE THREAD

**Issue by kayaen** [innoveit/react-native-ble-manager#643]
Hello, 

I just download and import react-native-ble-manager as in example but I get the error "Invariant Violation: Native module cannot be null." Then investigated that it is caused from NativeEventEmitter which means NativeModules.BleManager returns null.
I think it is a simple error but couldn't find the answer anywhere. 
Thanks in advance.

**Comment by marcosinigaglia** [comment]
Try to install correctly.

**Comment by Space-Around** [comment]
@marcosinigaglia, what does it mean?

> Try to install correctly.

What exactly is wrong with the installation?

**Comment by Space-Around** [comment]
#703
