### ISSUE TITLE
Android devices are not detecting in iOS

### ISSUE THREAD

**Issue by Pranay2019** [innoveit/react-native-ble-manager#651]
Hi,

I am able to scan iOS devices from the Android phone, but from iOS I'm not able to detect any android devices. Do we need to do anything while scanning from iOS Device?

**Comment by amor87** [comment]
@Pranay2019  please check -> https://github.com/innoveit/react-native-ble-manager/issues/650 I had the same issue and still have but there's nothing much we can do about it as you can see in my post

**Comment by marcosinigaglia** [comment]
Hi, is not an issue, is a OS limitation.
