### ISSUE TITLE
Type System - PeripheralInfo Object Data Type is empty

### ISSUE THREAD

**Issue by amor87** [innoveit/react-native-ble-manager#656]
### Version

Current Version

### Expected behaviour

The type declaration for PeripheralInfo is well defined or at least decent enough to include the basic data type for that object

### Actual behaviour

It has no definition
https://github.com/innoveit/react-native-ble-manager/blob/master/index.d.ts#L123

**Comment by Marvedog** [comment]
@marcosinigaglia Do I understand it correctly that it is just an `Array<string>` containing services? I extrapolate from the `retrieveServices` function and the code below.

https://github.com/innoveit/react-native-ble-manager/blob/master/android/src/main/java/it/innove/BleManager.java#L383

**Comment by marcosinigaglia** [comment]
@Marvedog yes, is correct.

**Comment by Marvedog** [comment]
@marcosinigaglia #747  ?
