### ISSUE TITLE
What will happen to "an queued message?"

### ISSUE THREAD

**Issue by WhaSukGO** [innoveit/react-native-ble-manager#667]
So, my application `write()` a message to my BLE device constantly, and I check the response value via `startNotification().`

Following each successful write, it throws an error, `You have already an queued message` about 20 times.

What will happen to all the queued message? Are they sent to the device sequentially or erased?

Thank you.

**Comment by marcosinigaglia** [comment]
Hi, check the Android code, if you write a something bigger than 20 bytes the library split the message and create a queue. You can do it in your js code to handle it better.
