### ISSUE TITLE
[All Platform] retrieveServices API return un-unified data structure between IOS and Android

### ISSUE THREAD

**Issue by wathui99** [innoveit/react-native-ble-manager#668]
### Version
 * Library version: 7.3.1

### Actual behaviour

When i call retrieveServices:
* IOS: return object contains services:[UUIDstring]
* Android: return object contains services:[{uuid: UUIDstring}]

I hope in next release this will be unified

**Comment by ferkawi** [comment]
Waiting for the same...I wanted to open a Pull Request but I saw @anees17861 (thx) already solve this bug in https://github.com/innoveit/react-native-ble-manager/pull/984 isn't it?
