### ISSUE TITLE
Where can i obtain the characteristicUUID?

### ISSUE THREAD

**Issue by BigPun86** [innoveit/react-native-ble-manager#67]
Hey there. I am tryinig to read and write to a bluetooth module. I have problems to understand how this works obviously, but maybe someone could help me with this... Discovering and connecting to the Bluetooth MOdule works great and wasn´t that hard, but now i would like to read data from the module. Where do i find the characteristicUUID which is needed to read from module?

This is what i receive from the module out of discovery:

![screen shot 2016-10-10 at 15 11 06](https://cloud.githubusercontent.com/assets/7880624/19237232/277c01d8-8efc-11e6-93ec-37868b138221.png)

**Comment by marcosinigaglia** [comment]
Hi, in release 2.2.0 you have the peripherals services and characteristics in connect callback. I will change the docs soon.
