### ISSUE TITLE
readRSSI on Android 7 does nothing

### ISSUE THREAD

**Issue by Gueoff** [innoveit/react-native-ble-manager#670]
### Version

Tell us which versions you are using:

- react-native-ble-manager v7.3.1
- react-native v0.61.4
- Android v.7.0

### Expected behaviour

The method reads the peripheral RSSI and returns value between -1 & -80

### Actual behaviour

The method does nothing and never stops

### Steps to reproduce

1. Launch connect function.
2. Launch readRSSI function

### Stack trace and console log

Call in my app:
```
console.log('before');
await BleManager.connect(identifier);
console.log('between');
await BleManager.readRSSI(identifier);
console.log('after');
```

Method called in the module:
```
readRSSI(peripheralId) {
    console.log('readRSSI module method');
    return new Promise((fulfill, reject) => {
      bleManager.readRSSI(peripheralId, (error, rssi) => {
        console.log('result', error, rssi);
        if (error) {
          reject(error);
        } else {
          fulfill(rssi);
        }
      });
    });
  }
```

I have tested the code bellow on few devices, on my Android 7.0, stack traces are :
```
before
between
readRSSI module method
```

on other devices:
```
before
between
readRSSI module method
result null -54
after
```

**Comment by marcosinigaglia** [comment]
Check the phone permission.
