### ISSUE TITLE
Why is BleManager imported twice in the example? (Line 18 & Line 22)

### ISSUE THREAD

**Issue by amanuelz91** [innoveit/react-native-ble-manager#683]
I'm looking at the example application (Example/App.js) and can't reason why BleManager is imported from the NPM package (line 18) and then explicitly from NativeModules (line 22). 

They seem to be the same modules with the same functionality.

**Comment by marcosinigaglia** [comment]
Hi @amanuelz91 , the first import is a js helper to use the module, the second is to real native module to bind in that case the events.
