### ISSUE TITLE
Cant listen to bluetooth changes via 'BleManagerDidUpdateState' listener

### ISSUE THREAD

**Issue by iradkot** [innoveit/react-native-ble-manager#685]
### Version 

Tell us which versions you are using:

- react-native-ble-manager v7.4.1
- react-native v0.63.3
- iOS/Android v.12

### Expected behaviour

Tell us what should happen
On ios - Once we listen to 'BleManagerDidUpdateState' we should be be updated on bluetooth connection changes
### Actual behaviour
This event doesn't get fired at all

Tell us what happens instead
nothing

### Steps to reproduce

1. Use library in ios
2. add:
`const BleManagerModule = NativeModules.BleManager;
export const bleManagerEmitter = new NativeEventEmitter(BleManagerModule);`
3. try listening to bluetoothe connection changes:
`bleManagerEmitter.addListener(
      'BleManagerDidUpdateState',
      this.handleBluetoothConnection,
    );`
on android it works fine

**Comment by marcosinigaglia** [comment]
Hi, is an import problem, check the ios project.
