### ISSUE TITLE
Is there anyway to make this work on Background in Android even after the app is killed? Nov 2020

### ISSUE THREAD

**Issue by danielbenedykt** [innoveit/react-native-ble-manager#688]
Is there anyway to make this work on Background in Android even after the app is killed?

As soon as I kill the app,  the device disconnects,  and of course the listeners are gone.

Platform: Android

if not,  I need to code a native BLE service/library myself to handle this?

**Comment by marcosinigaglia** [comment]
Hi, I think you need a custom module to handle something in background.

**Comment by siddaiahm** [comment]
try using react-native-background-fetch for  running app in background.
