### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication) on iOS devices

### ISSUE THREAD

**Issue by Girum** [innoveit/react-native-ble-manager#690]
Hi.

I used the example and modified it. But, when I tried to run on iOS device, it says:

```
  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Nov 27 2020 08:54:22.670]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

I realized that the NativeModules and NativeEventEmitter was the problem. I removed them and it starts to work... but nothing happens. I saw a solution on the web tu uso NativeAppEventEmitter, but it dont work too. This post: [https://eysermans.com/post/scanning-for-bluetooth-devices-with-react-native](url)

How cal I solve this?

Note: in Android it works fine

**Comment by Girum** [comment]
I verified and use the NativeAppEventEmmiter. The android continous goes Ok. The iOS receive the devices, but only in the Xcode terminal

**Comment by marcosinigaglia** [comment]
I think is some installation issue.

**Comment by voulgarakis** [comment]
cd ios
pod install
cd ..
react-native run-ios

that fixed the issue for me. 

@marcosinigaglia please update the documentation for iOS
