### ISSUE TITLE
Android 10 - startNotification gives error "Error writing descriptor stats=133"

### ISSUE THREAD

**Issue by viktorbk** [innoveit/react-native-ble-manager#694]
### Version
- react-native-ble-manager v7.4.1
- react-native v0.63.4
- iOS/Android v.10 kernel 4.19.95

### Expected behaviour
startNotification should start notification on characteristic

### Actual behaviour
Gives error: Error writing descriptor stats=133

### Code to reproduce
AndroidManifest.xml
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```
App.js
```
  const connect = async device => {
    await BleManager.connect(device.id)
    console.log('Connected......')
    const info = await BleManager.retrieveServices(device.id)
    console.log('Got service...', info)
    const characteristic = info.characteristics[3]
    const service = characteristic.service
    const charect = characteristic.characteristic
    console.log(service, charect)
    setTimeout(async () => {
      await BleManager.startNotification(device.id, service, charect)
      debugger
      await BleManager.disconnect(device.id)
      console.log('Disonnected......')
    }, 500)
  }
```

### Stack trace and console log
```
{advertising: {…}, rssi: -56, id: "04:91:62:93:03:59", name: "MyDevice"}
App.js:65 Connected......
App.js:67 Got service... {characteristics: Array(4), services: Array(3), advertising: {…}, name: "MyDevice", rssi: -56, …}
App.js:71 11020304-0506-0708-0900-0a0b0c0d0e0f 11223344-5566-7788-9900-aabbccddeeff
backend.js:32 Possible Unhandled Promise Rejection (id: 0):
"Error writing descriptor stats=133"
...

```

Could it be the new UBSan (Bounds Sanitizer) in Android 10?
https://source.android.com/devices/tech/debug/bounds-sanitizer

```
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'ubsan: out-of-bounds'
```

It here in Peripheral.java where it fails: (line 501)
```
if (gatt.writeDescriptor(descriptor)) {
    Log.d(BleManager.LOG_TAG, "setNotify complete");
} else {
    registerNotifyCallback = null;
    callback.invoke(
        "Failed to set client characteristic notification for " + characteristicUUID);
}
```

**Comment by marcosinigaglia** [comment]
Hi, I don't have an android 10 phone so i can't  reproduce your issue.

**Comment by viktorbk** [comment]
Hi, if you buy Nokia 5.3 with Android 10 as I did i will pay for the phone. There are already customers complaining since our app is in Google Play store and important functionality for our company.

**Comment by SCasarotto** [comment]
I can confirm as I just ran identical code on android 10 and 11 and everything worked correctly on Android 11 but not android 10. My error was `Error writing descriptor stats=1`. @viktorbk did you ever find a solution to this?

**Comment by zorba0517** [comment]
i got same issue

**Comment by marcosinigaglia** [comment]
It's a OS/Hardware bug.

**Comment by atornatore** [comment]
Did anybody find a workaround for this?

**Comment by jimhuf** [comment]
I have this same problem, on a Samsung note 10
Android 11 (Kernel 4.14)
But works fine on Android 11 (Kernel 4.9) Galaxy Tab S5e

Any update on this issue?

**Comment by DomLeMarin** [comment]
I had the same issue with the phone OPPO A53 (ColorOS 7.2 based on Android 10). After struggling on it for several days,
I found out that I need to **create a bond first** and then it works (I never had to do that with any other Android phones). 

After catching the error stats=133, the following seems to work:
1) Wait until the device is truly disconnected (about 10 sec),
2) Call the function _BleManager.createBond(peripheral.id)_,
3) Accept the pairing pop-up that shows up on the screen,
4) Wait until the device is truly disconnected (about 25 sec),
5) Start again with _BleManager.connect_, _BleManager.retrieveServices_, _BleManager.startNotification_

This needs to be done only once. The next connections are working as usual, since the two devices are bonded.

I hope it helps someone...

**Comment by 2sem** [comment]
the error rarely occured.
I saw it once.
