### ISSUE TITLE
Is it possible to bring both the id and the mac address at the same time on both android and ios?

### ISSUE THREAD

**Issue by Heltonphg** [innoveit/react-native-ble-manager#700]
Tell us which versions you are using:

react-native-ble-manager v7.4.1
react-native v0.63.4
Android version 10

I need the peripheral to bring both the id and the mac address in the same object, it's possible?

` bleManagerEmitter.addListener(
      'BleManagerDiscoverPeripheral',
      (peripheral) => {
        console.log(peripheral)
      },
    );
`

**Comment by marcosinigaglia** [comment]
The id on Android is the mac address, in iOS is an internal id.

**Comment by Heltonphg** [comment]
What is the difference between mac address to internal id?

**Comment by marcosinigaglia** [comment]
iOS decide to hide the mac address so they show you a generated id.

**Comment by turkogluc** [comment]
Is there a way to retrieve mac address from the discovered peripheral?
