### ISSUE TITLE
'writeWithoutResponse' request do not work on release android APK.

### ISSUE THREAD

**Issue by alexp193** [innoveit/react-native-ble-manager#702]
hey,
for some reason, 'writeWithoutResponse' doesn't work for android devices that not debug the app from use before. 

that's works just after installing the app from debugging mode.

thanks

**Comment by Xenofono** [comment]
Is your writeWithoutResponse call wrapped in a function with useCallback or useMemo? I had this problem until I adjusted the dependencies of the useCallback so it refreshed properly, after that it worked in the release build.
