### ISSUE TITLE
Failed to start notification

### ISSUE THREAD

**Issue by nolife08021** [innoveit/react-native-ble-manager#706]
"Set notification failed for 000036f6-0000-1000-8000-00805f9b34fb".I did add the time out between retrieveServices and startNotification but set notification failed too. Any solution to solve it?

retrieve result
[{"characteristic": "36f5", "properties": {"Write": "Write"}, "service": "fee7"}, {"characteristic": "36f6", "properties": {"Notify": "Notify", "Read": "Read"}, "service": "fee7"}, {"characteristic": "fec7", "properties": {"Write": "Write"}, "service": "fee7"}, {"characteristic": "fec8", "properties": {"Indicate": "Indicate", "Read": "Read"}, "service": "fee7"}, {"characteristic": "fec9", "properties": {"Read": "Read"}, "service": "fee7"}]

logcat
2021-01-15 15:09:09.673 23627-23864/com.lock2020 D/ReactNativeBleManager: startNotification 2021-01-15 15:09:09.674 23627-23864/com.lock2020 D/ReactNativeBleManager: registerNotify 2021-01-15 15:09:09.674 23627-23864/com.lock2020 D/ReactNativeBleManager: setNotify 2021-01-15 15:09:09.674 23627-23864/com.lock2020 D/BluetoothGatt: setCharacteristicNotification() - uuid: 000036f6-0000-1000-8000-00805f9b34fb enable: true 2021-01-15 15:09:09.679 23627-23863/com.lock2020 I/ReactNativeJS: Set notification failed for 000036f6-0000-1000-8000-00805f9b34fb

**Comment by nolife08021** [comment]
BleManager.start({showAlert: false})
          .then(() => {
              console.log('Module initialized');
              let id = 'FA:97:B4:F4:26:65';
              BleManager.connect(id)
                  .then(() => {
                      console.log('Connected');
                      BleManager.retrieveServices(id)
                          .then((peripheralInfo) => {
                              console.log('Peripheral info:', peripheralInfo);
                              setTimeout(function () {
                                  console.log('in timeout');
                                  BleManager.startNotification(id, 'fee7', '36f6')
                                      .then(() => {
                                          console.log('Notification success');
                                      })
                                      .catch((error) => {
                                          console.log(error);
                                      });
                              }, 3000);
                          })
                          .catch((error) => {
                              console.log(error);
                          });
                  })
                  .catch((error) => {
                      console.log(error);
                  });
          })
          .catch((error) => {
              console.log(error);
          });

**Comment by heusgenda** [comment]
BleManager.startNotification(id, 'fee7', '36f6') in this method you need to swap fee7 with 36f6 (1. MAC, 2. serviceUUID, 3. characteristic)

**Comment by nolife08021** [comment]
> BleManager.startNotification(id, 'fee7', '36f6') in this method you need to swap fee7 with 36f6 (1. MAC, 2. serviceUUID, 3. characteristic)

sorry, i dont understand. fee7 is the serviceUUID and 36f6 is the notify characteristic.
