### ISSUE TITLE
Not able to read the data from thermometer

### ISSUE THREAD

**Issue by TNSelvan** [innoveit/react-native-ble-manager#707]
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v?.?.? 7.4.1
- react-native v?.? 0.63.4
- iOS/Android v.? 

### Expected behaviour

I am not able to read the values from my thermometer model no TE-91, I have tried all the UUIDs returned by the system, For some UUIds i am getting the constant value only.

BleManager.read(peripheral.id, '180F', '2a00').then((readData) => {
                console.log('Data is : ' + readData);
              }).catch((error) => {
                console.log('read error' + error);
              });

I am getting the result as "Data is : 0"

Please help me to get the exact result value.

### Actual behaviour

We need the exact value captured on the system like 96.8 F

### Steps to reproduce

1.  
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
This is not an issue, check the device documentation.
