### ISSUE TITLE
Example App.js Problems with testPeripheral()

### ISSUE THREAD

**Issue by heusgenda** [innoveit/react-native-ble-manager#709]
I am new to this library and bluetooth.
The Example is for simple testing excellent. 
When you want to outsource a  function which should set a light (LED) on and off by sending a JSON String one runs into big trouble, because of  the nested promise, setTimeout() , .then() asynchronous function testPeripheral().  You can only implement code in a required place in the innermost setTimeout() function.

const testPeripheral = (peripheral) => {
    if (peripheral){
      if (peripheral.connected){
        BleManager.disconnect(peripheral.id);
      }else{
        BleManager.connect(peripheral.id).then(() => {
          let p = peripherals.get(peripheral.id);
          if (p) {
            p.connected = true;
            peripherals.set(peripheral.id, p);
            setList(Array.from(peripherals.values()));
          }
          console.log('Connected to ' + peripheral.id);

          setTimeout(() => {

            /* Test read current RSSI value */
            BleManager.retrieveServices(peripheral.id).then((peripheralData) => {
              console.log('Retrieved peripheral services', peripheralData);

              BleManager.readRSSI(peripheral.id).then((rssi) => {
                console.log('Retrieved actual RSSI value', rssi);
                let p = peripherals.get(peripheral.id);
                if (p) {
                  p.rssi = rssi;
                  peripherals.set(peripheral.id, p);
                  setList(Array.from(peripherals.values()));
                }
              });
            });

            // Test using bleno's pizza example
            // https://github.com/sandeepmistry/bleno/tree/master/examples/pizza

            BleManager.retrieveServices(peripheral.id).then((peripheralInfo) => {
              console.log(peripheralInfo);
              var service = '13333333-3333-3333-3333-333333333337';
              var bakeCharacteristic = '13333333-3333-3333-3333-333333330003';
              var crustCharacteristic = '13333333-3333-3333-3333-333333330001';

              setTimeout(() => {
                BleManager.startNotification(peripheral.id, service, bakeCharacteristic).then(() => {
                  console.log('Started notification on ' + peripheral.id);
                  setTimeout(() => {

                   **HERE I CAN READ AND WRITE BUT I HAVE NO ACCESS TO IT, IT IS SCOPED. I WANT TO IMPLEMENT A FUNCTION WHICH IS CALLED IN THE VIEW BY A BUTTON. IF I SET FUNCTION GLOBAL OUTSIDE IT IS NOT ATTACHED TO THE "testPeripheral() quasi Object". IT DELIVERS A FAILURE, BECAUSE "peripheral.id" IS NOT RECEIVED AND SET. I CAN'T SET THE peripheral.id AS A CONST GLOBALLY, THIS IS NO OPTION, BECAUSE I HAVE TOO MANY PERIPHERALS LATER. THE SOURCE WOULD GET TOO LONG.  **

                    /*BleManager.write(peripheral.id, service, crustCharacteristic, [0]).then(() => {
                      console.log('Writed NORMAL crust');
                      BleManager.write(peripheral.id, service, bakeCharacteristic, [1,95]).then(() => {
                        console.log('Writed 351 temperature, the pizza should be BAKED'); */

                        //var PizzaBakeResult = {
                        //  HALF_BAKED: 0,
                        //  BAKED:      1,
                        //  CRISPY:     2,
                        //  BURNT:      3,
                        //  ON_FIRE:    4
                        //};
                      });
                    });

                  }, 500);
                }).catch((error) => {
                  console.log('Notification error', error);
                });
              }, 200);
            });

          }, 900);
        }).catch((error) => {
          console.log('Connection error', error);
        });
      }
    }

  }  
 HOW CAN I CHANGE THE CALLBACK NESTED FUNCTION PROBLEM INTO ASYNC AWAIT FUNCTIONS AND HOW CAN I SOLVE THE SCOPING PROBLEM?

**Comment by marcosinigaglia** [comment]
Hi, sorry but this is not an issue, is not the right place to ask this questions.
