### ISSUE TITLE
bleManagerEmitter.removeEventListener is not a function

### ISSUE THREAD

**Issue by headkaze** [innoveit/react-native-ble-manager#710]
I get this error running the example:
`TypeError: bleManagerEmitter.removeEventListener is not a function. (In 'bleManagerEmitter.removeEventListener('BleManagerDiscoverPeripheral', handleDiscoverPeripheral)', 'bleManagerEmitter.removeEventListener' is undefined)`

Changing 'removeEventListener' to 'removeListener' resolves the issue.

**Comment by marcosinigaglia** [comment]
Hi, can you make a PR?
