### ISSUE TITLE
Cant find any bluetooth device if already enabled Bluetooth on Android Samsungs

### ISSUE THREAD

**Issue by iHunterX** [innoveit/react-native-ble-manager#717]
### Version

Tell us which versions you are using:

- react-native-ble-manager v7.4.2
- react-native v0.63.3
- Android  X

### Expected behaviour
if the bluetooth already initialized it will able to scan for devices
### Actual behaviour

If already turned on bluetooth Samsung device (eg. A20, S20) it will not able to find any devices.
I already turn on and enabled with 

`await BleLib.start({ showAlert: false });`
and
`await BleLib.enableBluetooth();`

I need to turn off bluetooth in settings then using our application to run `await BleLib.enableBluetooth();` for it to able to scan devices

### Steps to reproduce

1. using Samsung A20
2. turn on Bluetooth in settings
3. scan devices

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi, check the app permission.
