### ISSUE TITLE
Get data from write property 

### ISSUE THREAD

**Issue by VoVaBro** [innoveit/react-native-ble-manager#718]
- react-native-ble-manager v7.4.2
- react-native v0.63.4
- iOS/Android v.14/X

I run the module according to the documentation, everything works correctly.

But when I using the **write** method, I need to get data from response as in the **read** method.
I tried to call write after startNotification - unsuccessfully...
How to implement this behavior?

**Comment by marcosinigaglia** [comment]
Hi, this is not an issue, check the device documentation.
