### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'bleManager.start')]

### ISSUE THREAD

**Issue by viren-vii** [innoveit/react-native-ble-manager#725]
I saw the same issue but didn't get the solution.
You said expo doesn't support external native libraries. Then what else can I do for building applications using this library?

![ss](https://user-images.githubusercontent.com/56278281/114388324-2a87ed80-9bb1-11eb-80e9-7276aca3b79a.png)

**Comment by marcosinigaglia** [comment]
No, doesn't support external native libraries.
