### ISSUE TITLE
Problem in running the example provided.

### ISSUE THREAD

**Issue by viren-vii** [innoveit/react-native-ble-manager#727]
The example does not work!!! I used the same example without changing a single thing.
After scanning when I hit the retrieve connected peripherals button it shows only device with name `advertising` in the list. Which is not even in the bluetooth list when i scan for bluetooth devices from phone's UI.
Should the example work without  any extra coding? Or do we have to code something by ourselves?
Am I doint anything wrong here?
When tried from another device it shows no peripheral devices even if i can see several numbers of devices when i scan from settings! 
If yes, please guide me how should I handle things.
Scanning works but other functions are not triggerred automatically since I checked logging. Please help :)
![issue](https://user-images.githubusercontent.com/56278281/115144923-ceb7db80-a06c-11eb-8e4d-221f3afd5c5c.png)

**Comment by marcosinigaglia** [comment]
Hi, please read the BLE protocol specification.
