### ISSUE TITLE
How should I write a RGB value to a device?

### ISSUE THREAD

**Issue by Jeith** [innoveit/react-native-ble-manager#739]
### Version
- react-native-ble-manager: ^7.4.2
- react-native: ^0.64.0
- iOS/Android: 11

### Expected behaviour
LED Light Strip that's connected to the device should change colors on WriteWithoutResponse call.

### Actual behaviour
WriteWithoutResponse passes successfully but device shows no change in color.

### Steps to reproduce
1. Successful connection to LED Light Strip
2. Send WriteWithoutResponse Call

### Stack trace and console log
No error message but here's the code:

```
       BleManager.connect(peripheral.id)
        .then(() => {
            console.log("Connected");

            BleManager.writeWithoutResponse(peripheral.id, "0000ffe0-0000-1000-8000-00805f9b34fb", "0000ffe1-0000-1000-8000-00805f9b34fb", [0, 255, 0])
            .then(() => {
                console.log("Success");
            })
            .catch((error) => {
                console.log(error);
            });
        })
        .catch((error) => {
            console.log(error);
        });
```
 
We have this same functionality in Kotlin working as it should when we pass this as the byte array: 
```val payload = byteArrayOf(0xff.toByte(), 0x00, 0x00)```
but we have been haven't been able to get it working in React Native. 

Do you have any tips on how to debug  writeWithoutResponse or suggestions to make to my current code? Thanks!

**Comment by marcosinigaglia** [comment]
Try:
`BleManager.writeWithoutResponse(peripheral.id, "0000ffe0-0000-1000-8000-00805f9b34fb", "0000ffe1-0000-1000-8000-00805f9b34fb", [0xFF, 0, 0])`
