### ISSUE TITLE
write's  serviceUUID can be acquired from?

### ISSUE THREAD

**Issue by JianFengH** [innoveit/react-native-ble-manager#74]
write(peripheralId, serviceUUID, characteristicUUID, data, maxByteSize)

when call method:
`
BleManager.connect(data.id)
                .then((peripheralInfo) => {
                    console.log('connected');
                    console.log('peripheralInfo:', peripheralInfo);
                })
`
result peripheralInfo like: 
`
{
"services": [{"uuid": "1800"}],
"characteristics": [{"service": "1800", "characteristic": "2a00", "properties": {"Read": "Read"}}]
}
`
what's the meaning of the result peripheralInfo?
how to use it?
hope to have some examples with more detail.

**Comment by marcosinigaglia** [comment]
Hi, you have the generic service 1800 and a readable characteristic, you have to read the device documentation to know what you read and how interpret the data.
