### ISSUE TITLE
the connection get lost once i killed the app <IOS>

### ISSUE THREAD

**Issue by AmirDoreh** [innoveit/react-native-ble-manager#740]
## Version

Tell us which versions you are using:

- react-native-ble-manager v 7.4.2
- react-native v 0.64.0
- iOS/Android

### Expected behaviour

The Device will be connected even if i killed the app within 15 mins

### Actual behaviour

the connection get lost once i killed the app

**Comment by marcosinigaglia** [comment]
Hi, it's the correct behaviour.
