### ISSUE TITLE
How to write back to back values to the same characteristic?

### ISSUE THREAD

**Issue by sale7268** [innoveit/react-native-ble-manager#745]
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v7.5.0
- react-native v0.60
- iOS/Android v.14

### Expected behaviour

I'm trying to write two values without response like this:

`BleManager.writeWithoutResponse(Peripheral.id, 'FFE0', 'FFE1', 'DM?').then(() => {});`
`BleManager.writeWithoutResponse(Peripheral.id, 'FFE0', 'FFE1', 'BL?').then(() => {});`

and expecting it to give me value like DM(3) and BL(3) in handleUpdateValueForCharacteristic = (data) =>{} function.

### Actual behaviour

For some reason it is only writing the first value and gives back DM value. if i swap values it still only reads the first value. Both of my write functions are next to eachOther and before them i'm calling startNotification and Retrieveservices.

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Put a delay between the two writes.
