### ISSUE TITLE
Physical Bluetooth connection is not terminating on iOS 14.6

### ISSUE THREAD

**Issue by zhifeng-heng** [innoveit/react-native-ble-manager#746]
### Background

This issue happens frequently on iPhone 7 (14.6) when the app is install via TestFlight. If the app is loaded from xcode itself, the disconnect method works most of the time. 

Any help / advice would be greatly appreciated.

### Version

Tell us which versions you are using:

- react-native-ble-manager v7.5.0
- react-native v0.60.6
- iOS v14.6

### Expected behaviour

Upon calling the .disconnect() method, the physical bluetooth link between the BLE peripheral and mobile phone should be terminated.

### Actual behaviour

The .disconnect() method promise returned a success but the physical bluetooth connection between the 2 devices are not terminated, hence causing an issue when mobile is trying to reconnect to the same BLE device again (the BLE device is in connected state and not advertising).

Currently, when this happens, the physical Bluetooth connection will terminate when the App is killed or the BLE device is shutdown or restarted.

**Comment by marcosinigaglia** [comment]
Hi, probably is a device bug.
