### ISSUE TITLE
Not able to find characteristic uuid

### ISSUE THREAD

**Issue by viren-vii** [innoveit/react-native-ble-manager#749]
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v7.5.0
- react-native v5.0.1
- iOS/Android Nougat

### Expected behaviour

Tell us what should happen

`retireveServices` should show full characteristic and service uuid.

### Actual behaviour

Tell us what happens instead

when I tried logging the `peripheralData.characteristics` I am getting
``
 [{"characteristic": "2a05", "properties": {"Indicate": "Indicate"}, "service": "1801"}, {"characteristic": "2a00", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2a01", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2aa6", "properties": {"Read": "Read"}, "service": "1800"}]
``

Unlike others, I am not getting characteristic uuid  I read in existing and closed issues. 
Here's my full response of `retrieveServices`

``
  {"advertising": {"isConnectable": true, "manufacturerData": {"CDVType": "ArrayBuffer",  "bytes": [Array], "data": ""}}, "characteristics": [{"characteristic": "2a05", "properties": [Object], "service": "1801"}, {"characteristic": "2a00", "properties": [Object], "service": "1800"}, {"characteristic": "2a01", "properties": [Object], "service": "1800"}, {"characteristic": "2aa6", "properties": [Object], "service": "1800"}], "id": "68:C4:4D:16:74:EE", "name": "SLAAUMDTO1U/Q1Y3JvtTOe5Z6qEukAsQ", "rssi": 0, "services": [{"uuid": "1801"}, {"uuid": "1800"}]}
``

**Comment by leoguanco** [comment]
Hello @viren-vii, I had the same problem and I solved it as follows:

- I updated the bluez firmware from v5.43 to v5.50 by following this tutorial [https://www.argenox.com/library/bluetooth-low-energy/using-raspberry-pi-ble/](url) , just the **Installing BlueZ Bluetooth Stack on the Raspberry Pi** part.
- Then I followed this tutorial [https://scribles.net/creating-ble-gatt-server-uart-service-on-raspberry-pi/](url) and it worked!
- To test it I used [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=es_AR&gl=US) and then I used the library [example](https://github.com/innoveit/react-native-ble-manager/tree/master/example) 

I hope this helps you :)
