### ISSUE TITLE
Scan returns 0 results even with the sample

### ISSUE THREAD

**Issue by sssembler** [innoveit/react-native-ble-manager#750]
Samsung S21 Ultra, trying the sample app as is. nothing.  the other well know lib does return results.  So any ideas? its not permissions or anything and like I say I just use the sample app.

**Comment by viren-vii** [comment]
for me, scan returns results as undefined! How are you getting even 0?

**Comment by Anggasayogo** [comment]
yes i ran into this after using the sample

**Comment by marcosinigaglia** [comment]
Hi, if is not working it's a installation/device/hw problem.

**Comment by sssembler** [comment]
not really a valid response, it happens with your default test sample with multiple users

**Comment by marcosinigaglia** [comment]
@sssembler the library use the OS api so if you don't have result:

- the app don't have the right permissions
- there is an issue in the phone
- there is an issue in OS
- there is an issue on the BLE device

There is no way that anyone can reproduce your problem without the combination of phone/os/ble device.

**Comment by sssembler** [comment]
ble plx worked first time so what can I say.

**Comment by marcosinigaglia** [comment]
@sssembler i'm happy the plx library is working and I can't debug your device and reproduce your problem.
