### ISSUE TITLE
Change timeout of BleManagerDisconnectPeripheral

### ISSUE THREAD

**Issue by Heltonphg** [innoveit/react-native-ble-manager#751]
Version
Tell us which versions you are using:

react-native-ble-manager  v7.4.1
react-native v0.63.4
Android 10

Expected behaviour
BleManagerDisconnectPeripheral is fired after a timeout during which a connection attempt is made.

Question: Can I change some way or timeout of triggering BleManagerDisconnectPeripheral? I wanted it to always fire within 10s - 15s.

Any help will be greatly appreciated.

**Comment by vish188** [comment]
U can use a react-native library called Headless JS, which will help to run the android application background or foreground.But it works only for Android.
