### ISSUE TITLE
send command via bluetooth 

### ISSUE THREAD

**Issue by danalmeidadev** [innoveit/react-native-ble-manager#752]
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v 7.5.0
- react-native 0.63.4
- iOS/Android v.?

### Expected behaviour
send command via bluetooth 

Tell us what should happen

### Actual behaviour

Tell us what happens instead

I would like to know how to send the command to my board via bluetooth, do you have an example? 

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Hi, sorry but this is not an issue.
