### ISSUE TITLE
error in writing the write method is giving an error as shown in the photo 

### ISSUE THREAD

**Issue by danalmeidadev** [innoveit/react-native-ble-manager#753]
![Screenshot_20210627-204603_arno](https://user-images.githubusercontent.com/47141407/123564071-4e110c00-d78e-11eb-802b-a128e93a14e4.jpg)
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v7.5.0
- react-native v0.63.4
- iOS/Android v.?

### Expected behaviour
call the method and send the parameters 

Tell us what should happen

### Actual behaviour

Tell us what happens instead
error in writing the write method is giving an error as shown in the photo 

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by marcosinigaglia** [comment]
Check the installation docs.
