### ISSUE TITLE
Connecting issue 

### ISSUE THREAD

**Issue by Shirsendu-Sarkar** [innoveit/react-native-ble-manager#758]
### Version

Tell us which versions you are using:

- react-native-ble-manager v-7.5.0
- react-native v-0.64.1
  testing on android api > 23

### Expected behaviour

on connect, it should connect quickly, using BleManager.connect(id) where id is peripheral id 

### Actual behaviour

sometimes its getting connected quickly, sometimes its taking too time to connect, not seeing any error callback or success callback while connecting

### Steps to reproduce

1.scaninfg nearby peripheral devices
2.getting peripheral id from scanned devices
3.passing id to connect method to connect to peripheral

### Stack trace and console log

Not getting exceptions while connecting but taking time to connect

**Comment by marcosinigaglia** [comment]
Hi, is not a library issue.
