### ISSUE TITLE
iOS scan not working in 2.x version

### ISSUE THREAD

**Issue by vinayr** [innoveit/react-native-ble-manager#76]
RN 0.37
iOS 10.1.1
XCode 8.1

scan is failing to discover peripheral on iOS for all 2.x releases. It works fine on 1.4.0.
Did anything change related to linking the project? I have `BleManager.xcodeproj` in Libraries and linked `libBleManager.a`, `CoreBluetooth.framework` in Build Phases.

**Comment by kevyu** [comment]
Did you call BleManager.start() before scan?

**Comment by vinayr** [comment]
I didn't know `start` was added. Thanks @kevyu. It works now.
