### ISSUE TITLE
Android autoConnect(peripheral) exists? 

### ISSUE THREAD

**Issue by OferWormser** [innoveit/react-native-ble-manager#760]
- react-native-ble-manager v7.4.2
- react-native v0.64.1
-Android 11

### Expected behaviour
Disconnect from peripheral device and then auto connect to the device when it's in range again

### Actual behaviour
Not reconnecting automatically

### Steps to reproduce
1.Disconnect from peripheral
2.Turn on peripheral device id

**Comment by OferWormser** [comment]
I found how to do it - I went to Peripheral.java class and changed in connectGatt function the autoConnect parameter to true.
Maybe you should add it in your api.

**Comment by marcosinigaglia** [comment]
Hi @Marvedog , you can make a PR with the autoConnect parameter 👍
