### ISSUE TITLE
cross platform connection

### ISSUE THREAD

**Issue by Goldtek** [innoveit/react-native-ble-manager#763]
Please how can i use the mac address i got in android though saved to my account and use it to scan and get the uuid for ios to use and connect on ios. @mkrawiec @christophercotton @seigel @typester

**Comment by marcosinigaglia** [comment]
You can't.

**Comment by Goldtek** [comment]
so how can handle cross-platform connectivity especially if I'm saving the
details of the device to the database?

**Comment by marcosinigaglia** [comment]
You can't via BLE.

**Comment by Goldtek** [comment]
Please can you explain
