### ISSUE TITLE
Listen to only one notification after a write

### ISSUE THREAD

**Issue by kabiskac** [innoveit/react-native-ble-manager#767]
In my use case I would like to always only listen to the next notification right after a write instead of getting all of them in a general callback.

The [NordicSemiconductor Android BLE Library](https://github.com/NordicSemiconductor/Android-BLE-Library) has this feature, called waitForNotification which is triggered by a writeCharacteristic call and it has a callback argument.

Can you please provide me tips on how to achieve this?

**Comment by marcosinigaglia** [comment]
- startNotification
- write
- stopNotification after BleManagerDidUpdateValueForCharacteristic event
