### ISSUE TITLE
Why do we need npx react-native link ?

### ISSUE THREAD

**Issue by ksetrin** [innoveit/react-native-ble-manager#781]
not an issue just a question

```shell
npm i --save react-native-ble-manager
npx react-native link
```

I installed react-native-ble-manager and executed `react-native link` and what I have:
1. Changed Info.plist with 
```
	<array>
		<string>urlscheme</string>
		<string>urlscheme2</string>
		<string>urlscheme3</string>
		<string>urlscheme4</string>
	</array>
```

what kind of schemes are these? 
Do we need `npx react-native link` ?

**Comment by marcosinigaglia** [comment]
Hi, you don't need react-native link using cocoapods.
