### ISSUE TITLE
Need new npm release for updated Typescript defs

### ISSUE THREAD

**Issue by mutablestudio** [innoveit/react-native-ble-manager#789]
Latest npm version does not have updated `index.d.ts` so Peripheral and PeripheralInfo do not have characteristics, services etc. available. TIA!

**Comment by marcosinigaglia** [comment]
Hi, sorry but I'm not using Typescript, any PR is welcome.

**Comment by mutablestudio** [comment]
hi @marcosinigaglia no PR required. the code is already in the `master` branch, but doing a yarn install (for example) installs version `^7.6.1` which is not up to date with master. so I assume a new npm publish frm master would resolve that.

**Comment by marcosinigaglia** [comment]
The latest version is 7.6.3 and is updated.

**Comment by mutablestudio** [comment]
@marcosinigaglia sorry! my bad...
