### ISSUE TITLE
Need use createBond without pop up pairing OS

### ISSUE THREAD

**Issue by BondPiyapan** [innoveit/react-native-ble-manager#790]
I want to use createBond without pairing pop up with OS

My code.

BleManager.createBond(selectDevice.id, '123456')
    .then(() => { 
      BleManager.connect(selectDevice.id)
    .then(() => {//todo})
}

Thank you.

**Comment by marcosinigaglia** [comment]
Did you check the OS documentation? Is possibile?

**Comment by KPS250** [comment]
I am using createBond for pairing with pin without user intervention but the pairing pop up is visible for few seconds and disappears automatically on successful pairing with createBond. Is there a way to disable pop up?
