### ISSUE TITLE
Error could not find service UUID on peripheral, but retrieveServices there are service in that

### ISSUE THREAD

**Issue by canh-eoh** [innoveit/react-native-ble-manager#793]
**Describe the bug**
I start notification error "Could not find service with UUID 00001809-0000-1000-8000-00805f9b34fb on peripheral with UUID 9DEF697C-6739-4C59-2313-5476F9E14264", but I check Peripheral info in retrieveServices there are service 1809 in that.
**To Reproduce**
1. I  build the app on iPhone 7+
2. I scan and connect device BleManager.connect success
3. I BleManager.retrieveServices success
<img width="1439" alt="Screen Shot 2021-11-13 at 23 51 31" src="https://user-images.githubusercontent.com/91376835/141652077-b8f53476-3d11-49f8-a4f6-62e25bf94733.png">

4. I BleManager.startNotification error
Could not find service with UUID 00001809-0000-1000-8000-00805f9b34fb on peripheral with UUID 9DEF697C-6739-4C59-2313-5476F9E14264"

**Screenshots**
<img width="1437" alt="Screen Shot 2021-11-13 at 23 52 24" src="https://user-images.githubusercontent.com/91376835/141652106-3ef55e2d-8677-4dba-bc76-9cf10eeb0126.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone7+]
 - OS: [iOS15]
 - react-native-ble-manager version:  "^7.6.3"
 - react-native version: "0.66.1"

**Comment by joaovitorqueiroz** [comment]
Hi @canh-eoh I had this same problem, apparently the IOS does not use the full UUID as on android, try to search for the service only with the value "1809".

You can create a constant is to use the Platform to toggle between IOS and Android values.

`const SERVICE =  Platform.OS === 'android' ? '00001809-0000-1000-8000-00805f9b34fb' : '1809';`

**Comment by canh-eoh** [comment]
@joaovitorqueiroz thanks it works
