### ISSUE TITLE
Propagating iOS NSError code in BleManagerDisconnectPeripheral event

### ISSUE THREAD

**Issue by Marvedog** [innoveit/react-native-ble-manager#798]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**
I am trying to implement some defensive error handling when my iOS devices disconnect from peripherals during use. The problem is that since `BleManagerDisconnectPeriphal` event does not return a status code, it is hard to do something sensible with the event.

My questions is, can we extend the current API and return error codes for iOS for this event since `didDisconnectPeripheral` is already receiving an `NSError` object, see [here](https://github.com/innoveit/react-native-ble-manager/blob/0b3db6e9b49b166266fd62bfdc06aaa2bfcf909a/ios/BleManager.m#L789)? Or are there particular reasons for only including the Android error codes in this API until now?

**To Reproduce**
N/a

**Expected behavior**
N/a

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: All
 - react-native-ble-manager version: 8.0.0
 - react-native version: N/A

**Additional context**

**Comment by marcosinigaglia** [comment]
Hi  @Marvedog , there is no problem adding details to the error so go ahead.
