### ISSUE TITLE
Device data is being split into multiple strings.

### ISSUE THREAD

**Issue by victorkvarghese** [innoveit/react-native-ble-manager#802]
Hi,

Can some one help please

Eg: ["17 SWIRL 50BBL STAINLESS"] in ios while in android ["17 SWIRL 50BBL STAIN","LESS "]

When issue this library, in iOS i'm able to see data from device. But in android, the same data is split into different strings.
<img width="1023" alt="size" src="https://user-images.githubusercontent.com/15869386/145553433-777a7f8d-7b97-4d10-b2ee-99588ec3143f.png">

**Comment by victorkvarghese** [comment]
@marcosinigaglia can you please take a look?

**Comment by marcosinigaglia** [comment]
Hi @victorkvarghese , I don't understand your problem, are you reading from a characteristic? The MTU in Android is different.

**Comment by victorkvarghese** [comment]
@marcosinigaglia I was able to fix it at-last  by setting MTU for android. 
Thanks for the reply and this awesome library :)
