### ISSUE TITLE
Can I use the react-native-manager to receive heart rate data broadcasted by a Garmin Fenix 6 watch?

### ISSUE THREAD

**Issue by dimitris4** [innoveit/react-native-ble-manager#803]
I would like to receive real time heart rate data from a Garmin wearable watch and show the data in the app.

**Comment by szopenkrk** [comment]
@dimitris4 Hi man I have the same issue or milestone to create. I found flow for that but usually to connect Garmin You need to call Garmin API. You need to check what connection to Garmin returns and after that try to consume some data from there. FOr sure it will request the device code to pare.

**Comment by szopenkrk** [comment]
Topic to close
