### ISSUE TITLE
What does it mean about `Connection error` ?

### ISSUE THREAD

**Issue by eastpiger** [innoveit/react-native-ble-manager#830]
I just upgrade ble-manager to the newest version. After upgrading, I find connect() may throw `Connection error` sometimes, and every thing goes well after retry connecting. 

This error is meaningless and What does it mean?

**Comment by madfauzi** [comment]
same issue.

**Comment by marcosinigaglia** [comment]
@eastpiger check the device log.

**Comment by pankajdreamsoft** [comment]
Same issue.

**Comment by lucasahlgren** [comment]
@pankajdreamsoft Did you find a solution? I am facing the same problem on Android.

**Comment by pgpankajgoyal** [comment]
@lucasahlgren : Yes, I did change my native code to get proper response. Which type of device you are trying to connect ?

**Comment by lucasahlgren** [comment]
I managed to sort it out with another package. Thank you anyways :)

**Comment by lucasahlgren** [comment]
@pgpankajgoyal I managed to sort it out with another package. Thank you anyways :)

**Comment by LazloN5** [comment]
@lucasahlgren what was the package you used?
