### ISSUE TITLE
how does the concept behind scan and writing/reading devices work?

### ISSUE THREAD

**Issue by luanfv** [innoveit/react-native-ble-manager#836]
hello, I have some questions regarding listing/connecting and writing/reading devices.

1. I noticed that not all devices around me are listed, things like notebook and some cell phones don't appear, but speakers, tv and smartwatch yes, could you explain why? does it have something to do with your bluetooth protocol?

2. Previously I developed with bluetooth classic and in it I could write/read items only with the device id, through BLE I realized that I need the serviceUUID and characteristicUUID. Are these things gateways? Does the person who developed the bluetooth part of the device I'm going to connect need to create these ports?

Thank you for your attention, maybe they are silly questions, but I'm new to this world of bluetooth connection and I was really confused by these details.

**Comment by boggsey** [comment]
This article from Adafruit might help explain some of your questions about BLE and GATT. https://learn.adafruit.com/introduction-to-bluetooth-low-energy/gatt

> The most important thing to keep in mind with GATT and connections is that connections are exclusive. What is meant by that is that a BLE peripheral can only be connected to one central device (a mobile phone, etc.) at a time! As soon as a peripheral connects to a central device, it will stop advertising itself and other devices will no longer be able to see it or connect to it until the existing connection is broken.

> Services are used to break data up into logical entities, and contain specific chunks of data called characteristics. A service can have one or more characteristics, and each service distinguishes itself from other services by means of a unique numeric ID called a UUID, which can be either 16-bit (for officially adopted BLE Services) or 128-bit (for custom services).

> The lowest level concept in GATT transactions is the Characteristic, which encapsulates a single data point (though it may contain an array of related data, such as X/Y/Z values from a 3-axis accelerometer, etc.).
