### ISSUE TITLE
Bluetooth Peripheral Stuck in "Connecting" State On iOS

### ISSUE THREAD

**Issue by pgpankajgoyal** [innoveit/react-native-ble-manager#838]
**Describe the bug**
I am trying to connect ble A&D device but stuck on "Connecting to peripheral with UUID : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".

It works with my NONIN (Oximeter) but fail when trying to connect with A&D (weight and BP) machine on iOS device.

It's perfect working for android devices.

**To Reproduce**
1. Run this sample application and enable bluetooth on iOS device.
2. Take weight on A&D device but fail to connect.

**Expected behavior**
Want to connect A&D machine (Weight and BP) with iPhone.

**Screenshots**
![Screenshot 2022-03-02 at 4 09 44 PM](https://user-images.githubusercontent.com/20697269/156346092-d8ae8279-6a96-4ca7-bbf9-5fd19cc5fcb1.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 14.8.1]
 - react-native-ble-manager version: 8.0.1
 - react-native version: 0.63.4

**Comment by marcosinigaglia** [comment]
Hi, this is not a issue, is how it works in iOS.

**Comment by priyasamyal** [comment]
Hi @pgpankajgoyal  Any update on this. I am also facing the same issue for A&D BP device in iOS
