### ISSUE TITLE
react-native-web

### ISSUE THREAD

**Issue by taj567** [innoveit/react-native-ble-manager#840]
Guys,with linking in react-native-web am able to see the paths and working fine if i reloads the page also in my local.
after it is deployed(in apache tomcat) also working fine when i reloads the page getting 404.
![Screenshot 2022-03-08 153213](https://user-images.githubusercontent.com/74459204/157372770-2e4a3a8a-a4d4-4e41-930b-3c5044035b20.png)

**Comment by marcosinigaglia** [comment]
This is another project.
