### ISSUE TITLE
array storage

### ISSUE THREAD

**Issue by Poojamok** [innoveit/react-native-ble-manager#841]
i want ot send acc and gyro data which is store in 6 index but i have got only 5. is it any thing define in package to store only 5 array index or ble manager library only accept 5 array index.

Output:
Data: 57,46,56,120,56,46,57,120,50,49,46,54,120,51,46,56,120,52,46,57
 LOG  sensor data [9.8, 8.9, 21.6, 3.8, 4.9]

Input:
 [9.8, 8.9, 21.6, 3.8, 4.9,9.1]

**Comment by marcosinigaglia** [comment]
I don't understand, probably is something wrong in your code.
