### ISSUE TITLE
[IOS]Unable to work.BleManagerModule is null

### ISSUE THREAD

**Issue by sunnleung** [innoveit/react-native-ble-manager#842]
**Describe the bug**
```
import BleManager from 'react-native-ble-manager'
...
BleManager.start({showAlert: false}).then(() => {
  console.log('init successful')
}).catch(error => {
  console.error(error)
})
```

The Log in Command show the ERROR message: [TypeError: null is not an object (evaluating 'bleManager.start')].
No matter what the device is mobile(iphone12promax ios15.4) or emulator.

```
import BleManager from 'react-native-ble-manager'
import {NativeModules, NativeEventEmitter} from 'react-native'
...
const BleManagerModule = NativeModules.BleManager
console.log(BleManagerModule)
const BleManagerEmitter = new NativeEventEmitter(BleManagerModule)
```

The Command show the "BleManagerModule" is "null". And the ERROR: Invariant Violation: 'new NativeEventEmitter()' require a non-null argument.

**Comment by marcosinigaglia** [comment]
The module is not installed correctly.

**Comment by rithvik-doshi** [comment]
I'm facing the exact same issue, and I've tried a pod install with no result. Has anyone dealt with this before?
