### ISSUE TITLE
null is not an object (evaluating 'bleManager.start')

### ISSUE THREAD

**Issue by JamesOwen7** [innoveit/react-native-ble-manager#851]
I'm new to RN and using BLE packages. I'm having trouble running the example as a lone project with the above error. Any help is appreciated.

**Comment by briandilley** [comment]
I have the same issue on android.

**Comment by marcosinigaglia** [comment]
If 'bleManager' is null the library is not installed correctly.

**Comment by ShongSu** [comment]
I have the same issue. when log BleManager I can get `{ isPeripheralConnected: [Function: bound isPeripheralConnected] }`, but the bleManager.start returns `[TypeError: null is not an object (evaluating 'bleManager.start')]`
Could you please indicate why the library is not installed correctly and how to install it in the right way? Thanks.
