### ISSUE TITLE
Not listening to notification on ios

### ISSUE THREAD

**Issue by Onibenjo** [innoveit/react-native-ble-manager#863]
On Android 11 and below, I am able to connect and get data from the device using the startNotification function.
But on iOS, it connects but the listener doesn't emit any value for the characteristic.

And on Android 12, it doesn't even connect.

**Comment by Jack-QMY** [comment]
I have the same problem, have you solved it？

**Comment by Onibenjo** [comment]
I believe I did. The task was moved to someone where I worked.
