### ISSUE TITLE
lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by quangcanh2975** [innoveit/react-native-ble-manager#865]
Hi. 
When running app using command: `npx react-native run-android` or building with Android Studio, it always returns this error:
node_modules/react-native-ble-manager/android/src/main/java/it/innove/BleManager.java:747: 
error: lambda expressions are not supported in -source 7
`            scanManager.stopScan(args -> {});`
                                      ^
  (use -source 8 or higher to enable lambda expressions)
**To Reproduce**
1. After install all packages
2. Start app by command: `npx react-native run-android `
3. See error

**Expected behavior**
It must build the app successfully.

**Screenshots**
Having the same error when building by Android Studio:
<img width="495" alt="Screen Shot 2022-06-10 at 17 00 25" src="https://user-images.githubusercontent.com/26849248/173042841-b3724a82-96d5-4912-adfa-c1e7ae0e7011.png">

**Smartphone (please complete the following information):**
 - Device: Samsung A52s 5G
 - OS: Android 12
 - react-native-ble-manager version: 8.3.0
 - react-native version: 0.66.0

**android/build.gradle:**
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.6.0')
    }
}
```

**Full error log**
```
> Task :react-native-ble-manager:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-ble-manager:compileDebugRenderscript NO-SOURCE
> Task :react-native-ble-manager:generateDebugResValues UP-TO-DATE
> Task :react-native-ble-manager:generateDebugResources UP-TO-DATE
> Task :react-native-ble-manager:packageDebugResources UP-TO-DATE
> Task :react-native-ble-manager:parseDebugLocalResources UP-TO-DATE
> Task :react-native-ble-manager:processDebugManifest UP-TO-DATE
> Task :react-native-ble-manager:generateDebugRFile UP-TO-DATE
> Task :react-native-ble-manager:javaPreCompileDebug UP-TO-DATE

> Task :react-native-ble-manager:compileDebugJavaWithJavac FAILED
10 actionable tasks: 2 executed, 8 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Users/canhqn/Documents/cartek/node_modules/react-native-ble-manager/android/src/main/java/it/innove/BleManager.java:747: error: lambda expressions are not supported in -source 7
            scanManager.stopScan(args -> {});
                                      ^
  (use -source 8 or higher to enable lambda expressions)
1 error

FAILURE: Build failed with an exception.
```

**Comment by SohaibKtb** [comment]
+1

**Comment by FroxCode** [comment]
I am getting the same error using with this library. 

It worked up until recently, I am not sure what changed.

**Comment by marcosinigaglia** [comment]
Hi, you are using and old java version to compile.

**Comment by dmingjuan** [comment]
+1. 
This problem does not exist in version 7.6，but exists in version 8.4.
I have configured :
android {
    .....
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by dmingjuan** [comment]
> 



> you are using and old java version to compile.

I have used the java8 version, but this problem still occurs

**Comment by jtovarto** [comment]
> compileOptions
Hi, where did you configured this options?

**Comment by jtovarto** [comment]
> Hi, you are using and old java version to compile.

I have the same problem, I see that you are referring to an old version of java, but in my case, I made sure to have version 11 and 17 installed in my environment, however the problem persists.
Any recommendations on what to check?.

**Comment by phamhien2102** [comment]
I also faced this issue (release 8.4.0). My solution:
Firstly, add lines into **node_modules/react-native-ble-manager/android/build.gradle** : 
```compileSdkVersion safeExtGet("compileSdkVersion", 30)
        // Add these lines
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

	defaultConfig {
		minSdkVersion safeExtGet("minSdkVersion", 21)
	}
```



Finally, I used [patch-package](https://www.npmjs.com/package/patch-package) to patch this library, please run this command in terminal:

`yarn patch-package react-native-ble-manager`

So, hope this help everybody

**Comment by MuriloBarranco** [comment]
+1
