### ISSUE TITLE
App crash on android 12

### ISSUE THREAD

**Issue by DavidNguyenvp** [innoveit/react-native-ble-manager#872]
I'm trying to build an android app it's working on android 11 but keep crash on android 12

  <uses-permission android:name="android.permission.INTERNET" />

        <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28"/>
    <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION" tools:targetApi="Q"/>

    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" 
                     android:usesPermissionFlags="neverForLocation"
                     tools:targetApi="s" />
    
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN"
        android:maxSdkVersion="30"
        />
    
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"
        android:maxSdkVersion="30"
        />

**Comment by ndebartha** [comment]
You need to explicitly ask the user to grant runtime permissions: BLUETOOTH_SCAN, BLUETOOTH_CONNECT in case of android 12.

**Comment by adriangiulianotucci** [comment]
I cant request the permission. When I log `PermissionsAndroid.PERMISSIONS` there is no BLUETOOTH_SCAN, or BLUETOOTH_CONNECT so it crashes when i ask for `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN)`. I declared the permissions the same as @DavidNguyenvp, do you think it's related to my `AndroidManifest`?

**Comment by DavidNguyenvp** [comment]
I resolved my issue by asking for runtime permission. 
 await requestMultiple([
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
          PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
        ]);

**Comment by DavidNguyenvp** [comment]
> I cant request the permission. When I log `PermissionsAndroid.PERMISSIONS` there is no BLUETOOTH_SCAN, or BLUETOOTH_CONNECT so it crashes when i ask for `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN)`. I declared the permissions the same as @DavidNguyenvp, do you think it's related to my `AndroidManifest`?

<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="32"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="32"/>
    <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION" tools:targetApi="s"/>

    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" 
                     android:usesPermissionFlags="neverForLocation"
                     tools:targetApi="s" />
    
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN"

        />
    
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"

        />
Hope it can help you

**Comment by phanthelam** [comment]
@DavidNguyenvp  Hi, where you put runtime permission ?
