### ISSUE TITLE
"Command queue busy" writeWithoutResponse/write is not working properly

### ISSUE THREAD

**Issue by lijutsang** [innoveit/react-native-ble-manager#876]
Hi,
I upgraded the Bluetooth library version from v7.5.0 to v8.4.0

writeWithoutResponse/write is not working properly, but there are no promotion errors

Seen from android studio logcat ,  hint "Command queue busy"
as follows
2022-07-06 16:09:53.164 23538-23861/com.labplus D/ReactNativeBleManager: Write without response to: D2:BB:24:EF:53:56
2022-07-06 16:09:53.164 23538-23861/com.labplus D/ReactNativeBleManager: Message(8): 0201016402013232
2022-07-06 16:09:53.165 23538-23861/com.labplus D/ReactNativeBleManager: Command queue busy

It seems to happen like this
[Peripheral.java](https://github.com/innoveit/react-native-ble-manager/blob/master/android/src/main/java/it/innove/Peripheral.java)/# 698line

`private void nextCommand() {
		synchronized (this) {
			if (commandQueueBusy) {
				Log.d(BleManager.LOG_TAG, "Command queue busy");
				return;
			}`

Has anyone had this problem?

 - react-native-ble-manager version:  v8.4.0
 - react-native version:  v0.62.3

 - test device 
 Huawei android 6.0.1 
 MI8  android 10

**Comment by wouterhund** [comment]
In my case this was triggered by calling readRSSI, which eventually leads to `onReadRemoteRssi` being called which does *not* call `completedCommand` leading to the `commandQueueBusy` to stick to true, blocking any further commands (such as writing)
