### ISSUE TITLE
All the BleManager methods has the only  success callback. Can I get the error callback?

### ISSUE THREAD

**Issue by zhanguangao** [innoveit/react-native-ble-manager#88]
`BleManager.scan([], 5, true)
  .then(() => {
    // Success code
    console.log('Scan started');
  })
 .then(() => {
    // Fail code
    console.log('Scan Fail');
  });`
I test this code, but not success.What should I do?

**Comment by marcosinigaglia** [comment]
You have to use `catch` method instead `then`.

**Comment by zhanguangao** [comment]
Using catch method have no effect when I disable the Bluetooth to scan Ble devices.

**Comment by marcosinigaglia** [comment]
You have to use BleManagerDidUpdateState to know the Bluetooth status.

**Comment by zhanguangao** [comment]
Using BleManagerDidUpdateState and Using checkState method I can know the currently Bluetooth status.Thank you!
