### ISSUE TITLE
Active Scan Support

### ISSUE THREAD

**Issue by AmitNeuhaus** [innoveit/react-native-ble-manager#881]
Hey,
I know that currently there are ble devices that are supporting "Active Scanning", where the scanner can send a scan request to the ble devices after receiving it's advertisements in order to get additional information from the ble device (if the ble device itself support it).

From what ive seen this package only supports passive scanning where we can only passively get advertisements when scanning.
Am i missing anything, is active scanning will be supported soon? 

Thank you,
Amit.

**Comment by marcosinigaglia** [comment]
Hi @AmitNeuhaus , can you point me the part in the Android/iOS's documentations that refer to the active scanning?
