### ISSUE TITLE
100ms delay between packages

### ISSUE THREAD

**Issue by ApostolosMavroukakis** [innoveit/react-native-ble-manager#886]
Im communicating with a bluetooth device, and im having trouble optimizing performance.
Even though the mtu is about 247 bytes the data is sent in 64bytes, more importantly tho its braking the data to multiple packages that have about 100ms delay between them. For a 300byte json it takes 500ms for the data to reach its destination.

![0-02-05-9e970009dd722d74d11e381cbb628460d2084019a17f4e7bd9b5886682776ed2_28a07dc8f17b8453](https://user-images.githubusercontent.com/9714171/182826862-eb163e28-97d0-405e-8783-2324f283aae5.png)

**Comment by marcosinigaglia** [comment]
Hi, probably is a device problem that cap the MTU to 64. The BLE protocol is not designed to transfer data.

**Comment by ApostolosMavroukakis** [comment]
> 

yes and yes, it was indeed the device that capped at 64. I dont understand the delay though. Its been tested with native code with passable results as well.

**Comment by marcosinigaglia** [comment]
The react native bridge is the bottleneck, are you using writeWithoutResponse or write?

**Comment by ApostolosMavroukakis** [comment]
I'm using write

`  const writeData = (stringToWrite) => {
    if (stringToWrite) {

      console.log("writeData function", stringToWrite)

      const data = stringToBytes(stringToWrite);
      BleManager.write(
        peripheralId,
        service,
        characteristicRX,
        data,
        247
      )
        .then(() => {
          console.log("Write: " + stringToWrite);
        })
        .catch((error) => {
          console.log(error);
        });

    }
  }`

**Comment by ApostolosMavroukakis** [comment]
Will try and come back to you, thanks a ton
