### ISSUE TITLE
Need android.permission.BLUETOOTH_SCAN permission for AttributionSource  {uid =11495} attributionTag = null, token = android.os.BlinderPorxy@21305d0

### ISSUE THREAD

**Issue by homerotorrijos** [innoveit/react-native-ble-manager#892]
`Hi,` @innoveit

I have tested your project, on Android 11,10, 7. It's working great, but in the recent permissions in Android 12 and de SDK changes  (31), I can't scan devices with Bluetooth 5.0.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/55118367/184385693-5ab5bbc8-541d-4cd4-98a1-b401d9261b4a.jpeg)

My AndroidManifest.xml

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28"/>
<uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION" tools:targetApi="Q"/>


<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"  />
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT"
                android:usesPermissionFlags="neverForLocation"
                tools:targetApi="s" 
/>
```

```
buldscript {
        ext{
              buildToolsVersion = "30.0.0"
              minSdkVersion = 21
              compileSdkVersion = 30 
              targetSdkVersion = 30 
       }
}
```

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions?hl=en-419
https://developer.android.com/google/play/requirements/target-sdk#pre12

**Comment by pradeep11** [comment]
Any update on this? I am facing the same issue

**Comment by Jack-QMY** [comment]
我也面临一样的问题

**Comment by thomasviaud** [comment]
Hello, you also need to ask the BLUETOOTH_SCAN permission at **runtime** for SDK >=31

**Comment by Jack-QMY** [comment]
我已经可以正常运行了，但是我在真机上运行的，跑虚拟机会出现这个问题

**Comment by Jack-QMY** [comment]
I can already run it normally, but running on a real machine, the virtual machine will have such a problem, my sdk version is 31

**Comment by marcosinigaglia** [comment]
You can't use BLE in a virtual machine.
