### ISSUE TITLE
"undefined" to Attempts to connect to a peripheral

### ISSUE THREAD

**Issue by vlade2008** [innoveit/react-native-ble-manager#9]
<img width="1440" alt="screen shot 2016-06-21 at 10 19 29 am" src="https://cloud.githubusercontent.com/assets/13525454/16216000/cdfd0634-3799-11e6-967b-2fca2df17fbb.png">
this is my code, please help me. thanks

**Comment by marcosinigaglia** [comment]
Hi, before connect you have to wait the scan has found the peripheral.
Il giorno mar 21 giu 2016 alle 04:21 Xtian <notifications@github.com> ha
scritto:

**Comment by NabilEL** [comment]
You have to subscribe to the BleManaDiscoverPeripheral event, and inside it you will be able to connect to the device you want (you still have to scan though) : 

Example : 
```
      BleManager.scan([tabletAppServiceUUID],60)
            .then(() => {
                console.log('scan started');
            })
            .catch((error) => {
                console.log("error scan : " + error);
            });
       NativeAppEventEmitter.addListener('BleManagerDiscoverPeripheral', (args) => {
           // Connect to your device here
       }
```

**Comment by tarang9211** [comment]
I tried the above code, and I still cannot connect to my MAC from my iPhone. This is the code

 ```
 btnPress() {
    BleManager.scan([], 60)
    .then(() => {
        console.log('scan started');
    });

    DeviceEventEmitter.addListener('BleManagerDiscoverPeripheral', (args) => {
        console.log(args);
        BleManager.connect('F71DA437-87A4-5E34-BC08-836D06B2FEAF')
        .then(() => {  
            console.log('success')
        })
        .catch((error) => {
            console.log(error);
        });
    })
  }
```
