### ISSUE TITLE
java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@52e08e33: GattService registerScanner

### ISSUE THREAD

**Issue by fanzhiri** [innoveit/react-native-ble-manager#911]
i run on my real phone which is android(12) ,and i do have android.permission.BLUETOOTH_SCAN in AndroidManifest 。

<uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation" />

09-30 14:28:45.949  1783  2019 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-30 14:28:45.949  1783  2019 E AndroidRuntime: Process: com.BuildKnow, PID: 1783
09-30 14:28:45.949  1783  2019 E AndroidRuntime: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@52e08e33: GattService registerScanner
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2404)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2346)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1881)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:538)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:294)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:156)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at it.innove.LollipopScanManager.scan(LollipopScanManager.java:81)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at it.innove.BleManager.scan(BleManager.java:223)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:955)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:206)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:296)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-30 14:28:45.949  1783  2019 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:930)

**Comment by gorhgorh** [comment]
hi there, just been here not long ago, for android 12 you need to EXPLICITLY ask for the perms (it will trigger a dialog)

https://reactnative.dev/docs/permissionsandroid

in my case I had another bug (but i use an old RN version where the "android.permission.BLUETOOTH_SCAN" was not in the permission of the react native object, so i just used the full string

```
const requestScanPermission = async (valPerm) => { // valPerm is the callback i use to trackwhat perm is granted
  try {
    const granted = await PermissionsAndroid.request(
      'android.permission.BLUETOOTH_SCAN',
      {
        title: 'Ble scan permissions',
        message:
          'this app need BLE Scan to find peripherals',
        buttonNeutral: "Ask Me Later (app won't work)",
        buttonNegative: 'Cancel',
        buttonPositive: 'OK'
      }
    )
    console.log('granted:scan', granted)
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log('You can use the scan')
    } else {
      console.log('Scan permission denied')
    }
    if (valPerm) valPerm(true)
  } catch (err) {
    console.warn(err)
  }
}
```
