### ISSUE TITLE
React-Native BLE Manager works on Android but not IOS (could not find service with uuid)

### ISSUE THREAD

**Issue by huseyinsafaunlu** [innoveit/react-native-ble-manager#912]
I coded a JavaScript react-native project and ran it on my **Android phone & iPhone**.

***It works on android phone but it doesn't work on iPhone.***

 - I am Using **BLE manager** Library.
 - I can find & connect devices using ios and android.
 - I can subscrible and send data using anroid.
 - I know that there are no mistakes on code because it works on Android.
 -  ***I can't start notifications and send data using the same react native project on IOS***
 - ***I think it is because of BLE manager library but don't know how to solve it***

It works perfectly on android. As shown below. 

                ANDROID IMAGE(Console below Code Top)

[![enter image description here][1]][1]

Then I uploaded the same project on my iPhone. I get the following UUID mismatch. Code is the same but can't communicate.

                 IOS IMAGE (Console Top Code Below)
[![enter image description here][2]][2]

**Note LightBlue Info:**

If Someone can tell me what to write on ID,ServiceUUID,CharUUID It would be lovely.

[![LightBlue Info][3]][3]

----------------------------------------------------------------
----------------------------------------------------------------
----------------------------------------------------------------
***UPDATE******

I tried this:

As seen on the picture below, I connected to device using ID, But can't find service with UUID

[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/8YGgz.png
  [2]: https://i.stack.imgur.com/B8iJ4.jpg
  [3]: https://i.stack.imgur.com/QwLW9.jpg
  [4]: https://i.stack.imgur.com/TdUYG.jpg

**Comment by marcosinigaglia** [comment]
The device id is different in iOS, is random, you can't use directly.

**Comment by huseyinsafaunlu** [comment]
Hi @marcosinigaglia  I tried as shown in picture right below of the question. Still didn't work . I connected to peripheral. I'm writing the correct service UUID but still don't work.
