### ISSUE TITLE
Throw (Permission error) on android 12.

### ISSUE THREAD

**Issue by dsnarwariya0102** [innoveit/react-native-ble-manager#919]
Hello

My project was on react native version 0.70.3 and buildToolsVersion = "31.0.0" when app install on android 11 all permission work fine but when app install android 12 do not turn on device blutooth. and its throw an error and release build app crash while installing.

![1667975823794](https://user-images.githubusercontent.com/63146475/200757387-bc90eb3d-13d3-4607-af94-cd3672cbbe7b.JPEG)

**Comment by Jack-QMY** [comment]
I just solved this, I need to dynamically obtain bluetooth permissions, use react-native-permissions to obtain
![image](https://user-images.githubusercontent.com/57746139/200768744-e106ddd5-4177-44b4-80bf-35f4bb8d6630.png)
