### ISSUE TITLE
Often  bluetoothgatt is null

### ISSUE THREAD

**Issue by a709691139** [innoveit/react-native-ble-manager#92]
First open the app, successfully connected bluetooth,
then close the app, reopen app,    bluetoothgatt is null,
To click several times in order to be successful

**Comment by marcosinigaglia** [comment]
Hi, is the device still connected?

**Comment by a709691139** [comment]
close the app,  Already disconnected

**Comment by a709691139** [comment]
Hope there is a function :  restart bluetooth

**Comment by marcosinigaglia** [comment]
Have you solve the problem?

**Comment by a709691139** [comment]
I used this method ： When I connect to Bluetooth,  i save it。 
After re opening,  use the "disconnect and stopNotification"

**Comment by shubhapp** [comment]
When i am trying to convert hex to byte array using below code . It is working 
`byte[] getBytes(String s){
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                    + Character.digit(s.charAt(i+1), 16));
        }
        return data;
    }`
