### ISSUE TITLE
ios connection automatically disconnected?

### ISSUE THREAD

**Issue by Jack-QMY** [innoveit/react-native-ble-manager#920]
Hi, fellow developers, I have a question. I have already obtained the Bluetooth id on the ios platform, and the connection has been successful using BleManager.connect(). There is also no disconnect() related method called  

ios 15.2  react-native v0.68.2     react-native-ble-manager: "8.4.3",

**Comment by Marvedog** [comment]
Have you verified that you have the correct connection interval on the peripherals? We had the same issue and the issue was wrong configuration of the peripheral not according to ios guidelines. 

https://developer.apple.com/library/archive/qa/qa1931/_index.html
