### ISSUE TITLE
Cannot get scanned devices 

### ISSUE THREAD

**Issue by AzranAzwer** [innoveit/react-native-ble-manager#922]
This library is not working giving me undefined 

Installed as per documentation

**Comment by rohithnair1996** [comment]
Any Solution?

**Comment by matgardon** [comment]
hi, your problems may not be related to this lib but to the android 13 changes to scan behavior, check out issue #943.

**Comment by AzranAzwer** [comment]
Hi, This is iOS related issue and I have fixed this.

`start(options)` method is not responding if i use before the scan function.
it worked when i wrapped the `app.js` file by creating context provider and 
in context provider, i used the `start(options)` method.

simply, I called the `start(options)` method when load the application.
