### ISSUE TITLE
[Feature Request] support custom PHY on android while connecting to GATT

### ISSUE THREAD

**Issue by matgardon** [innoveit/react-native-ble-manager#926]
Hi,  this issue is related to [this one](https://github.com/innoveit/react-native-ble-manager/issues/855), but actually the coded phy support linked to BLE 5 is also supported by android APIs for connection & advertising, not just scanning.

So the Android API supports a custom phy in the `connectGatt` method now, [see the official doc here](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#connectGatt(android.content.Context,%20boolean,%20android.bluetooth.BluetoothGattCallback,%20int,%20int,%20android.os.Handler)).

I think that would make sense for BLE5 interactions to support it, as 2M is crazy fast compared to 1M for specific use-cases (where you control both BLE chips & know they both support 2M data rates).

for more context on 2M : https://punchthrough.com/crash-course-in-2m-bluetooth-low-energy-phy/

Also, that could optionally be the occasion to let users manually change the transport mode & autoConnect flag ?

Thank you for your hard work in any case.

**Comment by marcosinigaglia** [comment]
[Done](https://github.com/innoveit/react-native-ble-manager/releases/tag/v.10.1.0)
