### ISSUE TITLE
Wrong connectGatt version used for Android M and Android N (?)

### ISSUE THREAD

**Issue by Marvedog** [innoveit/react-native-ble-manager#931]
**Describe the bug**
This is primarily a question that needs clarification as I am not that familiar with Android Bluetooth internals.

According to the Android docs, the `conenctGatt` method used here

https://github.com/innoveit/react-native-ble-manager/blob/master/android/src/main/java/it/innove/Peripheral.java#L109

Was made available in API level 26.

https://developer.android.com/reference/android/bluetooth/BluetoothDevice#connectGatt(android.content.Context,%20boolean,%20android.bluetooth.BluetoothGattCallback,%20int,%20int,%20android.os.Handler)

Can it be clarified why it is used for Android M and above? 

**To Reproduce**
1. Apply fix in #916 
2. Attempt to connect w/ Android N device

**Expected behavior**
A proper connection.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia
 - OS: Android Nougat (7.1.1)
 - react-native-ble-manager version: master 
 - react-native version: 0.68.x

**Additional context**
N/A

**Comment by marcosinigaglia** [comment]
Hi @Marvedog , I'm not expert too, I checked with Android Studio and it also suggest  the  `>= Build.VERSION_CODES.M` check. I think the the correct doc reference is that: https://developer.android.com/reference/android/bluetooth/BluetoothDevice#connectGatt(android.content.Context,%20boolean,%20android.bluetooth.BluetoothGattCallback,%20int)

**Comment by Marvedog** [comment]
I am able to make it work with the current implementation, but it is weird that the documentation suggests this.
