### ISSUE TITLE
function(BleManager.scan) is not call in Android 12

### ISSUE THREAD

**Issue by VijaySharma12** [innoveit/react-native-ble-manager#937]
Code:
BleManager.scan([], 5, true).then((results) => {
        console.log('start scan ',results)
        setIsScanning(true);
      }).catch(err => {
        console.error( 'Erorrr start scan catch block',err);
        
      });
      
      This function is not not work on **android 12** renaming versions are working fine as like android 10 ,11
      npm version - "react-native-ble-manager": "^8.5.0",
      React native version:  "0.64.2"
      React version:  "17.0.1"

**Comment by marcosinigaglia** [comment]
Check the app permission https://github.com/innoveit/react-native-ble-manager/issues/919
