### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ironicbrew** [innoveit/react-native-ble-manager#940]
**Before open an issue**
✅ Check the closed issues, your question maybe is not new.
✅ We can't debug or reproduce hardware issue.
✅ If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**

Example from the repo does not work when cloned directly from the repo

**To Reproduce**

In a new directory:
```git clone <repo url>```
```cd react-native-ble-manager/example ```
```npm i --force // Without --force throws a bunch of conflicting peer dependencies which feels like separate issue```
```npx pod-install```
```Error: CocoaPods could not find compatible versions for pod "RCT-Folly"```

I'm able to get beyonnd this stoppingn point by changing ```platform :ios, '11.0'`` --> ```'13.0'``` and running ```pod-install```

But then I get the following error which is beyond my current skill with react-native to troubleshoot

```
The following build commands failed:
        CompileC
```

**Expected behavior**

Should be able to install pods successfully and run example as a standalone working implementation

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13 (Simulator)
 - OS: iOS 16.2 (Simulator)
 - react-native-ble-manager version: ```8.5.0```
 - react-native version: Using ```npx``` I'm getting ```8.0.6```

**Additional context**

```npx react-native info```
```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 59.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/robmclean/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Recommended way of interacting with example in docs doesn't work as the ```/example``` directory doesn't ship with the library when installing to a repo with ```npm``` or ```yarn```. I did get the example code to work by copy pasting the ```example/App.js``` code into an existing project but this feels like a bit of a workaround from typical example UX and I think the only barrier is tweaking a couple of dependancies in ```/example```. Or updating the docs to reflect a working way of interacting with the example.

**Comment by marcosinigaglia** [comment]
Hi @ironicbrew probably the example projects is not fine with the latest updates. Is better if you start an empty project and copy only the js part.

**Comment by ironicbrew** [comment]
> Hey thanks for the reply. I can confirm copying only the js part into a new project works well (minus some easily altered [deprecated](https://reactnative.dev/docs/appstate#removeeventlistener) syntax).
> 
> Any interest in a PR from me to update the example or is copy pasting the JS the prefered method? Or would a patch of just the deprecated `removeEventListener` method call be more appropriate if at all?
> 
> For the [example docs](https://reactnative.dev/docs/appstate#removeeventlistener) am I correct that the currently documented easiest way doesn't work or am I misunderstanding the docs? The example content doesn't ship with the package when you `npm/yarn i` which I believe is why it doesn't work as documented.

@marcosinigaglia Open to my submitting a PR to update the example?

**Comment by marcosinigaglia** [comment]
Sure, your update is welcome

**Comment by ironicbrew** [comment]
@marcosinigaglia Cheers! PR ready: #960
