### ISSUE TITLE
SERVICE UUID AND CHARACTERISTIC UUID

### ISSUE THREAD

**Issue by mohsinmughal1630** [innoveit/react-native-ble-manager#951]
const SERVICE_UUID = "0000FFE0-0000-1000-8000-00805F9B34FB";
const CHARACTER_UUID = "0000FFE1-0000-1000-8000-00805F9B34FB";

That is my device service uuid and character uuid which i get from device developer but from when this library i send data getting this error "**Error writing 0000FFE1-0000-1000-8000-00805F9B34FB status = 10**"

Please help me what i doing wrong my code

  BleManager.retrieveServices(props.route.params.bluetoothData.id).then(
      (peripheralData) => {
        const mData = `${firstName} \n${lastName}`

        const data = stringToBytes(mData);
            BleManager.write(
                props.route.params.bluetoothData.id,
                SERVICE_UUID,
                CHARACTER_UUID,
                data
              )
                .then(() => {
                  // Success code
                  console.log("Write: " + data);
                })
                .catch((error) => {
               
                  console.log(error);
                });
        }
      
      
    ).catch((err)=>{
        dispatch(startLoader(false));
        Alert.alert("Error!", err)
    });

**Comment by mohsinmughal1630** [comment]
Please help me with this humble request

**Comment by mohsinmughal1630** [comment]
???

**Comment by sefam-stoussaint** [comment]
Hello,
I think your UUIDs should be "FFE0" and "FFE1"

**Comment by aje** [comment]
Your data is wrong, it should be like: 

```
import { Buffer } from 'buffer';
const buffer = Buffer.from('test');
```
