### ISSUE TITLE
[Android] scan is not working.

### ISSUE THREAD

**Issue by star4680** [innoveit/react-native-ble-manager#959]
**Describe the bug**

BLE SCAN is no longer operational.
This case occurs intermittently and will not function normally until the Bluetooth setting is cycled on the phone.

I checked the ADB log and found the following information.
```
02-06 11:11:44.609 27110 27154 D ReactNativeBleManager: scan
02-06 11:11:44.611 27110 27154 D BluetoothAdapter: isLeEnabled(): ON
02-06 11:11:44.612 11947 12308 D BtGatt.GattService: registerScanner() - UUID=07afbd9c-fa21-439d-9583-4d2f234e3e68
02-06 11:11:44.613 11947 12273 V bt_stack: [VERBOSE1:bta_gattc_act.cc(175)] bta_gattc_register: state:2
02-06 11:11:44.613 11947 12273 I bt_stack: [INFO:gatt_api.cc(957)] GATT_Register 4d11f63f-8657-131e-a95e-b70f9bcd18d2
02-06 11:11:44.613 11947 12273 E bt_stack: [ERROR:gatt_api.cc(982)] can't Register GATT client, MAX client reached: 32
02-06 11:11:44.613 11947 12273 E bt_stack: [ERROR:bta_gattc_act.cc(186)] Register with GATT stack failed.
02-06 11:11:44.613 11947 12273 I bt_stack: [INFO:gatt_api.cc(957)] GATT_Register 4d11f63f-8657-131e-a95e-b70f9bcd18d2
02-06 11:11:44.613 11947 12273 E bt_stack: [ERROR:gatt_api.cc(982)] can't Register GATT client, MAX client reached: 32
02-06 11:11:44.613 11947 12273 E bt_stack: [ERROR:bta_gattc_act.cc(186)] Register with GATT stack failed.
02-06 11:11:44.613 11947 11986 D BtGatt.GattService: onScannerRegistered() - UUID=07afbd9c-fa21-439d-9583-4d2f234e3e68, scannerId=0, status=133
02-06 11:11:44.613 27110 27127 D BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
```

**To Reproduce**
1. Attempted to connect BLE, but "CONNECTION ERROR" occurred and "BleManagerDisconnectPeripheral" handler was called.
2. SCAN was called to retry BLE Connect, but the "BleManagerStopScan" handler was called immediately.
3. The same situation will occur if you restart the app later.

**Smartphone (please complete the following information):**
 - Device: Galaxy s8
 - OS: Android 9 
 - react-native-ble-manager version: 8.6.0
 - react-native version: 0.63.3

**Comment by matgardon** [comment]
Hi @star4680, I think your logs are pretty straightforward: you have too many BLE devices registered on you phone/device this app is running on, so can't connect to another one until you clean up your local ble bonds.
 (apparently 32 BLE devices is the max on your phone).
 
`02-06 11:11:44.613 11947 12273 E bt_stack: [ERROR:gatt_api.cc(982)] can't Register GATT client, MAX client reached: 32`
