### ISSUE TITLE
Advertising does not hold serviceUUIDs

### ISSUE THREAD

**Issue by medonja** [innoveit/react-native-ble-manager#967]
**Describe the bug**
My advertisement does not hold a serviceUUIDs for any of the found Bluetooth devices returned in the BleManagerDiscoverPeripheral handler. 
This is how a typical response looks like:

` {"advertising": {"isConnectable": true, "manufacturerData": {"CDVType": "ArrayBuffer", "bytes": [Array], "data": "AgEaC/9MAAkGAzHAqACzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}}, "id": "13:B2:6B:EA:63:B1", "name": null, "rssi": -53}
`

**Expected behavior**
I expected the advertising to have the exact attributes as describe here: https://github.com/innoveit/react-native-ble-manager#blemanagerdiscoverperipheral
It seems also that some attributes have a slightly different name than described in the documentation.,

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 (but also a somewhat older Android device such as the Samsung A50)
 - OS: Android 13
 - react-native-ble-manager version: 8.8.0
 - react-native version: 0.68.2

**Comment by tobiyas09** [comment]
I have the same problem on v8.8.0, but if you try to run the example on the master branch it returns serviceUUIDs. 
Maybe they fixed this and we will get this with the next release?

**Comment by medonja** [comment]
No idea, but I resorted to react-native-ble-plx meanwhile... a pity.

**Comment by marcosinigaglia** [comment]
Hi, you need to call retrieveServices to have the service UUIDS.

**Comment by tobiyas09** [comment]
> Hi, you need to call retrieveServices to have the service UUIDS.

Hi, I don't think that was the problem, scan results didn't have serviceUUIDs in AdvertisingData. The RetrieveServices method needs to be called before writing, reading or starting a notification. 
What fixed it for me was switching forceLegacy to  **false** in the start method.

**Comment by mokaty1818795** [comment]
> I have the same problem on v8.8.0, but if you try to run the example on the master branch it returns serviceUUIDs. Maybe they fixed this and we will get this with the next release?

did you get the solution ?

**Comment by tobiyas09** [comment]
> did you get the solution ?

Yes, I put forceLegacy to false in the start method

**Comment by mokaty1818795** [comment]
> > did you get the solution ?
> 
> Yes, I put forceLegacy to false in the start method

this is my code snipped
import React, {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from 'react';
import {NativeEventEmitter, NativeModules} from 'react-native';
import BleManager, {
  BleScanCallbackType,
  BleScanMatchMode,
  BleScanMode,
  Peripheral,
  PeripheralInfo,
} from 'react-native-ble-manager';
import {Buffer} from 'buffer';
import {BluetoothEventTypes} from './event-types';
import {handleAndroidPermissions} from '../utils/bluetooth-permission';

declare module 'react-native-ble-manager' {
  interface Peripheral {
    connected?: boolean;
    connecting?: boolean;
  }
}

type BluetoothContextType = {
  devices: Map<string, Peripheral>;
  scanning: boolean;
  scanDevices: () => void;
  connectDevice: (id: string) => Promise<void>;
  connectedDevice: PeripheralInfo | null;
  disconnect: () => void;
  printContent: (input: string) => Promise<void>;
};

type BluetoothProviderType = {
  children: ReactNode;
};

const bluetoothManagerModule = NativeModules.BleManager;
const bluetoothManagerEmitter = new NativeEventEmitter(bluetoothManagerModule);

const SECONDS_TO_SCAN_FOR = 5;
const SERVICE_UUIDS: string[] = [];
const ALLOW_DUPLICATES = true;

const BluetoothContext = createContext({} as BluetoothContextType);

const BluetoothProvider = ({children}: BluetoothProviderType) => {
  const [scanning, setScaning] = useState(false);
  const [peripherals, setPeripherals] = useState(
    new Map<Peripheral['id'], Peripheral>(),
  );
  const [connectedDevice, setConnectedDevice] = useState<PeripheralInfo | null>(
    null,
  );

  const addOrUpdatePeripheral = (id: string, updatedPeripheral: Peripheral) => {
    setPeripherals(map => new Map(map.set(id, updatedPeripheral)));
  };

  const handleRetrieveConnecteds = async () => {
    const connectDevices = await BleManager.getConnectedPeripherals();
    if (connectDevices.length === 0) {
      console.warn('[retrieveConnected] No connected peripherals found.');
      return;
    }

    console.debug('[retrieveConnected] connectedPeripherals', connectDevices);

    setConnectedDevice(connectDevices[0]);

    for (var i = 0; i < connectDevices.length; i++) {
      var peripheral = connectDevices[i];
      addOrUpdatePeripheral(peripheral.id, {...peripheral, connected: true});
    }
  };

  const disconnect = async () => {
    if (connectedDevice && connectedDevice.connected) {
      await BleManager.disconnect(connectedDevice.id);
    } else {
      throw new Error('Device not connected');
    }
  };

  const connectDevice = async (id: string) => {
    console.debug('[bluetooth-connect] starting...');
    await BleManager.connect(id);
    const peripheralData = await BleManager.retrieveServices(id);

    await handleRetrieveConnecteds();
    setConnectedDevice(peripheralData);
    console.debug(peripheralData.id);
    console.debug(peripheralData.name);
    console.debug(peripheralData.services?.length);
    console.debug(peripheralData.characteristics?.length);
    console.debug('[bluetooth-connect] sucsess');
  };

  const handleStopScan = () => {
    setScaning(false);
    console.debug('[handleStopScan] scan is stopped.');
  };

  const handleAddNewDevice = (peripheral: Peripheral) => {
    console.debug('[bluetooth-module] found new device:', peripheral);
    if (!peripheral.name) {
      peripheral.name = 'NO NAME';
    }
    addOrUpdatePeripheral(peripheral.id, peripheral);
  };

  const scanDevices = () => {
    if (!scanning) {
      setPeripherals(new Map<Peripheral['id'], Peripheral>());
      try {
        console.debug('[bluetooth-context] scanning...');
        setScaning(true);

        BleManager.scan(SERVICE_UUIDS, SECONDS_TO_SCAN_FOR, ALLOW_DUPLICATES, {
          matchMode: BleScanMatchMode.Sticky,
          scanMode: BleScanMode.LowLatency,
          callbackType: BleScanCallbackType.AllMatches,
        })
          .then((results) => {
            console.debug('[bluetooth-context] scan successfully.', results);
            console.debug('[bluetooth-context] scan results:');
          })
          .catch(err => {
            console.error('[bluetooth-context] scan error', err);
          });
      } catch (error) {
        console.error('[bluetooth-context] scan error thrown', error);
      }
    }
  };

  const printContent = async (input: any) => {
    if (connectedDevice) {
      const canWrite = connectedDevice.characteristics
        ?.map(c => {
          return {
            characs: c.properties,
            service: c.service,
            characId: c.characteristic,
          };
        })
        .filter(c => c.characs.Write === 'Write');

      if (!canWrite) {
        throw new Error('Device cant write');
      }

      const buff = Buffer.from(input);
      await BleManager.writeWithoutResponse(
        connectedDevice.id,
        canWrite[0].service,
        canWrite[0].characId,
        buff.toJSON().data,
      );
      console.log('[bluetooth-print] success');
    } else {
      throw new Error('no device connected');
    }
  };

  useEffect(() => {
    BleManager.enableBluetooth();
    BleManager.start({showAlert: false})
      .then(() => console.debug('BleManager started.'))
      .catch(error => console.error('BeManager could not be started.', error));

    const listeners = [
      bluetoothManagerEmitter.addListener(
        BluetoothEventTypes.FOUND_NEW_DEVICE,
        handleAddNewDevice,
      ),
      bluetoothManagerEmitter.addListener(
        BluetoothEventTypes.STOP_SCAN,
        handleStopScan,
      ),
      bluetoothManagerEmitter.addListener(
        BluetoothEventTypes.DISCONNECT_DEVICE,
        () => setConnectedDevice(null),
      ),
      bluetoothManagerEmitter.addListener(
        BluetoothEventTypes.UPDATE_DEVICE_PROPERTY,
        () => {
          console.debug('[UPDATE NOW]');
        },
      ),
    ];
    console.debug('[bluetooth-context] starting...');
    handleAndroidPermissions();

    return () => {
      console.debug('[bluetooth-context] stoping... removing listeners');
      for (const listener of listeners) {
        listener.remove();
      }
    };
  });

  return (
    <BluetoothContext.Provider
      value={{
        devices: peripherals,
        scanning,
        scanDevices,
        connectDevice,
        connectedDevice,
        disconnect,
        printContent,
      }}>
      {children}
    </BluetoothContext.Provider>
  );
};

function useBluetooth() {
  const context = useContext(BluetoothContext);
  return context;
}

export {BluetoothProvider, useBluetooth};

**Comment by mokaty1818795** [comment]
> > did you get the solution ?
> 
> Yes, I put forceLegacy to false in the start method

i did and still get the same issue
