### ISSUE TITLE
Error for over Android SDK 31

### ISSUE THREAD

**Issue by fullstact69** [innoveit/react-native-ble-manager#968]
Need
android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@44deb9ec:GattService registerScanner

![1677577379610](https://user-images.githubusercontent.com/53449197/221814721-57cf56b2-4eb3-4132-a579-7308cc0ae3a0.JPEG)

Below is the permissions in Manifest

    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"  android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    
 Need to know why it is happend in usage of this react-native-ble-manager module.

**Comment by sshestopalov** [comment]
You must request `android.permission.BLUETOOTH_SCAN` and `android.permission.BLUETOOTH_CONNECT` permissions in runtime using built-in [AndroidPermissions](https://reactnative.dev/docs/permissionsandroid) or third-party library like [react-native-permissions](https://github.com/zoontek/react-native-permissions)
