### ISSUE TITLE
BleManager.disconnect not working on Android

### ISSUE THREAD

**Issue by hzcfy** [innoveit/react-native-ble-manager#985]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
- We can't debug or reproduce hardware issue.
- If the library is not working 99% you did something wrong, in the code, installation or in the phone permissions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - react-native-ble-manager version:  8.8.0
 - react-native version: 0.71.3

**Additional context**

**Comment by schimini** [comment]
@hzcfy can you provide any context and update the issue description?

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by schimini** [comment]
Ahah I've translated this and this is an automatic email response. Hope you have a nice vacation!

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
