### ISSUE TITLE
BleManagerConnectPeripheral and BleManagerDisconnectPeripheral don't work properly

### ISSUE THREAD

**Issue by lzagar-itm** [innoveit/react-native-ble-manager#986]
**Describe the bug**
`BleManagerConnectPeripheral` event doesn't work on Android or iOS.
`BleManagerDisconnectPeripheral` event doesn't work on iOS when bluetooth if turned off.

**Expected behavior**
Events should be triggering when device is connected or disconnected.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro, Samsung Galaxy 8
 - OS: iOS 16, Android 9
 - react-native-ble-manager version: 8.8.0
 - react-native version: 0.70.5

**Comment by nazmeln** [comment]
I have the same issue
