### ISSUE TITLE
Android could not read BLE service info

### ISSUE THREAD

**Issue by wangyixian** [innoveit/react-native-ble-manager#99]
First, startNotification on the notification service.
BleManager.startNotification(peripheralId, '0000fff0-0000-1000-8000-00805f9b34fb', '0000fff2-0000-1000-8000-00805f9b34fb')

Second, read the notification service.
BleManager.read(peripheralId, '0000fff0-0000-1000-8000-00805f9b34fb', '0000fff2-0000-1000-8000-00805f9b34fb')

Then, write the search command into the write service. This step is return success.
 let data = base64.fromByteArray(Utils.str2Bytes('000000'));
BleManager.write(peripheralId, '', '0000fff2-0000-1000-8000-00805f9b34fb')', '0000fff1-0000-1000-8000-00805f9b34fb', data)

Could not read service info by android, but ios is ok.
Android version is 5.1

**Comment by marcosinigaglia** [comment]
Hi, you don't need to use notification if you read the value directly.

**Comment by wangyixian** [comment]
Thank you.
But the BLE device is designed as follow:
Write '000000' string into the write service fff1, 
then get the device state by read the notification service fff2.

Could you give me a sample about read function.

**Comment by marcosinigaglia** [comment]
You have to handle the BleManagerDidUpdateValueForCharacteristic event to read the values from the service in notification.

**Comment by wangyixian** [comment]
Thank you very much.
I resolved this problem by handle the BleManagerDidUpdateValueForCharacteristic event.

**Comment by hbenkhay** [comment]
I want to use notifications , I need an example to use BleManagerDidUpdateValueForCharacteristic,
does this event return an object ? can you help me please
